/* Generated by scripts/build-scene-explorer-data.py.
 * Sources: docs/ps1/scene-status.md, site/scenes/<slug>/index.md,
 *          generated/ps1/foreground/<SLUG>.FG2.
 * Re-run as part of release.sh; do not edit by hand. */

#ifndef SCENE_EXPLORER_DATA_H
#define SCENE_EXPLORER_DATA_H

#include "mytypes.h"

struct TSceneExplorerEntry {
    const char *slug;          /* internal scene identifier (e.g. "fishing1") */
    uint16      display_name_offset; /* byte offset into SCEXPL.DAT strings */
    uint16      frame_count;   /* from FG2 header */
    uint8       family_index;  /* index into sceneExplorerFamilyName() */
    uint8       validated;     /* 1 if scene-status visuals are checked */
    uint8       _pad;
};

#ifdef SCENE_EXPLORER_DATA_DEFINE
const struct TSceneExplorerEntry gSceneExplorer[] = {
    { "fishing1", 0, 156, 0, 1, 0 },
    { "fishing2", 49, 295, 0, 1, 0 },
    { "fishing3", 94, 329, 0, 1, 0 },
    { "fishing4", 146, 133, 0, 1, 0 },
    { "fishing5", 211, 69, 0, 1, 0 },
    { "fishing6", 262, 112, 0, 1, 0 },
    { "fishing7", 318, 80, 0, 1, 0 },
    { "fishing8", 388, 133, 0, 1, 0 },
    { "johnny1", 438, 112, 1, 1, 0 },
    { "johnny2", 459, 146, 1, 1, 0 },
    { "johnny3", 521, 210, 1, 1, 0 },
    { "johnny4", 568, 94, 1, 1, 0 },
    { "johnny5", 612, 91, 1, 1, 0 },
    { "johnny6", 645, 82, 1, 1, 0 },
    { "mary1", 704, 821, 2, 1, 0 },
    { "mary2", 742, 234, 2, 1, 0 },
    { "mary3", 829, 256, 2, 1, 0 },
    { "mary4", 887, 154, 2, 1, 0 },
    { "mary5", 947, 150, 2, 1, 0 },
    { "visitor1", 990, 67, 3, 1, 0 },
    { "visitor3", 1034, 145, 3, 1, 0 },
    { "visitor4", 1103, 55, 3, 1, 0 },
    { "visitor5", 1163, 180, 3, 1, 0 },
    { "visitor6", 1217, 121, 3, 1, 0 },
    { "visitor7", 1271, 91, 3, 1, 0 },
    { "activity1", 1342, 194, 4, 1, 0 },
    { "activity10", 1389, 256, 4, 1, 0 },
    { "activity11", 1432, 208, 4, 1, 0 },
    { "activity12", 1477, 252, 4, 1, 0 },
    { "activity4", 1528, 190, 4, 1, 0 },
    { "activity5", 1572, 169, 4, 1, 0 },
    { "activity6", 1619, 105, 4, 1, 0 },
    { "activity7", 1668, 57, 4, 1, 0 },
    { "activity8", 1708, 87, 4, 1, 0 },
    { "activity9", 1763, 255, 4, 1, 0 },
    { "miscgag1", 1836, 69, 5, 1, 0 },
    { "miscgag2", 1868, 84, 5, 1, 0 },
    { "suzy1", 1920, 177, 5, 1, 0 },
    { "suzy2", 1963, 133, 5, 1, 0 },
    { "stand1", 2018, 18, 6, 1, 0 },
    { "stand10", 2065, 87, 6, 1, 0 },
    { "stand11", 2110, 87, 6, 1, 0 },
    { "stand12", 2157, 238, 6, 1, 0 },
    { "stand15", 2197, 34, 6, 1, 0 },
    { "stand16", 2239, 36, 6, 1, 0 },
    { "stand2", 2283, 78, 6, 1, 0 },
    { "stand3", 2321, 91, 6, 1, 0 },
    { "stand4", 2373, 107, 6, 1, 0 },
    { "stand5", 2426, 131, 6, 1, 0 },
    { "stand6", 2494, 118, 6, 1, 0 },
    { "stand7", 2545, 47, 6, 1, 0 },
    { "stand8", 2580, 44, 6, 1, 0 },
    { "stand9", 2643, 47, 6, 1, 0 },
    { "walkstuf1", 2696, 216, 7, 1, 0 },
    { "walkstuf2", 2760, 57, 7, 1, 0 },
    { "walkstuf3", 2793, 439, 7, 1, 0 },
    { "building1", 2831, 106, 8, 1, 0 },
    { "building2", 2882, 334, 8, 1, 0 },
    { "building3", 2956, 360, 8, 1, 0 },
    { "building4", 2998, 428, 8, 1, 0 },
    { "building5", 3058, 474, 8, 1, 0 },
    { "building6", 3102, 307, 8, 1, 0 },
    { "building7", 3162, 460, 8, 1, 0 },
};
const int gSceneExplorerCount = (int)(sizeof(gSceneExplorer) / sizeof(gSceneExplorer[0]));

const int gSceneExplorerFamilyStart[] = {
    0,
    8,
    14,
    19,
    25,
    35,
    39,
    53,
    56,
};
const int gSceneExplorerFamilyCount = (int)(sizeof(gSceneExplorerFamilyStart) / sizeof(gSceneExplorerFamilyStart[0]));
#else
extern const struct TSceneExplorerEntry gSceneExplorer[];
extern const int gSceneExplorerCount;
extern const int gSceneExplorerFamilyStart[];
extern const int gSceneExplorerFamilyCount;
#endif

const char *sceneExplorerDisplayName(int index);
const char *sceneExplorerFamilyName(int familyIndex);
const char *sceneExplorerSelectedDisplayName(void);

#endif
