/* Generated by scripts/build-scene-explorer-data.py.
 * Sources: docs/ps1/scene-status.md, site/scenes/<slug>/index.md,
 *          generated/ps1/foreground/<SLUG>.FG2.
 * Re-run as part of release.sh; do not edit by hand. */

#ifndef SCENE_EXPLORER_DATA_H
#define SCENE_EXPLORER_DATA_H

#include "mytypes.h"

struct TSceneExplorerEntry {
    const char *slug;          /* internal scene identifier (e.g. "fishing1") */
    const char *display_name;  /* shown on the menu line */
    const char *family;        /* display family group */
    const char *pack;          /* CD-relative FG2 path */
    const char *thumb_psb;     /* CD-relative thumbnail PSB path */
    uint16      frame_count;   /* from FG2 header */
    uint8       validated;     /* 1 if scene-status visuals are checked */
    uint8       _pad;
};

#ifdef SCENE_EXPLORER_DATA_DEFINE
const struct TSceneExplorerEntry gSceneExplorer[] = {
    { "fishing1", "FISHING 1  -  Catches a starfish, throws it back", "Fishing", "FG/FISHING1.FG2", "BMP/SCEXPL_FISHING1.PSB", 156, 1, 0 },
    { "fishing2", "FISHING 2  -  Hooks a Titanic life preserver", "Fishing", "FG/FISHING2.FG2", "BMP/SCEXPL_FISHING2.PSB", 295, 1, 0 },
    { "fishing3", "FISHING 3  -  Octopus steals the fish and walks off", "Fishing", "FG/FISHING3.FG2", "BMP/SCEXPL_FISHING3.PSB", 329, 1, 0 },
    { "fishing4", "FISHING 4  -  Hooks a shark, gets pulled around like a speedboat", "Fishing", "FG/FISHING4.FG2", "BMP/SCEXPL_FISHING4.PSB", 133, 1, 0 },
    { "fishing5", "FISHING 5  -  Eaten by a shark, then spat back out", "Fishing", "FG/FISHING5.FG2", "BMP/SCEXPL_FISHING5.PSB", 69, 1, 0 },
    { "fishing6", "FISHING 6  -  Fish spits water in his face, thrown back", "Fishing", "FG/FISHING6.FG2", "BMP/SCEXPL_FISHING6.PSB", 112, 1, 0 },
    { "fishing7", "FISHING 7  -  Catches a starfish (right-side variant), throws it back", "Fishing", "FG/FISHING7.FG2", "BMP/SCEXPL_FISHING7.PSB", 80, 1, 0 },
    { "fishing8", "FISHING 8  -  Catches a fish (right-side variant)", "Fishing", "FG/FISHING8.FG2", "BMP/SCEXPL_FISHING8.PSB", 133, 1, 0 },
    { "johnny1", "JOHNNY 1  -  The End", "Johnny", "FG/JOHNNY1.FG2", "BMP/SCEXPL_JOHNNY1.PSB", 112, 1, 0 },
    { "johnny2", "JOHNNY 2  -  Bottle washes up; Johnny puts an SOS note inside", "Johnny", "FG/JOHNNY2.FG2", "BMP/SCEXPL_JOHNNY2.PSB", 146, 1, 0 },
    { "johnny3", "JOHNNY 3  -  Writes and sends a letter to Suzy", "Johnny", "FG/JOHNNY3.FG2", "BMP/SCEXPL_JOHNNY3.PSB", 210, 1, 0 },
    { "johnny4", "JOHNNY 4  -  His own SOS bottle washes back", "Johnny", "FG/JOHNNY4.FG2", "BMP/SCEXPL_JOHNNY4.PSB", 94, 1, 0 },
    { "johnny5", "JOHNNY 5  -  Sends an SOS bottle", "Johnny", "FG/JOHNNY5.FG2", "BMP/SCEXPL_JOHNNY5.PSB", 91, 1, 0 },
    { "johnny6", "JOHNNY 6  -  At his office desk, daydreaming of the island", "Johnny", "FG/JOHNNY6.FG2", "BMP/SCEXPL_JOHNNY6.PSB", 82, 1, 0 },
    { "mary1", "MARY 1  -  Date with Mary the mermaid", "Mary", "FG/MARY1.FG2", "BMP/SCEXPL_MARY1.PSB", 821, 1, 0 },
    { "mary2", "MARY 2  -  Mary visits while Johnny fishes; he mistakes her for a fish, catches a boot", "Mary", "FG/MARY2.FG2", "BMP/SCEXPL_MARY2.PSB", 234, 1, 0 },
    { "mary3", "MARY 3  -  Mary and Johnny exchange gifts and plan a date", "Mary", "FG/MARY3.FG2", "BMP/SCEXPL_MARY3.PSB", 256, 1, 0 },
    { "mary4", "MARY 4  -  Mary's feelings hurt as Johnny works on the raft", "Mary", "FG/MARY4.FG2", "BMP/SCEXPL_MARY4.PSB", 154, 1, 0 },
    { "mary5", "MARY 5  -  Packs the raft and says goodbye", "Mary", "FG/MARY5.FG2", "BMP/SCEXPL_MARY5.PSB", 150, 1, 0 },
    { "visitor1", "VISITOR 1  -  Misses a speedboat passing by", "Visitors", "FG/VISITOR1.FG2", "BMP/SCEXPL_VISITOR1.PSB", 67, 1, 0 },
    { "visitor3", "VISITOR 3  -  Waves down what looks like a small boat, but it's huge", "Visitors", "FG/VISITOR3.FG2", "BMP/SCEXPL_VISITOR3.PSB", 145, 1, 0 },
    { "visitor4", "VISITOR 4  -  Shakes the palm; coconut rolls into the ocean", "Visitors", "FG/VISITOR4.FG2", "BMP/SCEXPL_VISITOR4.PSB", 55, 1, 0 },
    { "visitor5", "VISITOR 5  -  Throws a coconut at a plane; it crashes", "Visitors", "FG/VISITOR5.FG2", "BMP/SCEXPL_VISITOR5.PSB", 180, 1, 0 },
    { "visitor6", "VISITOR 6  -  Shakes tree, cracks coconut on it, eats", "Visitors", "FG/VISITOR6.FG2", "BMP/SCEXPL_VISITOR6.PSB", 121, 1, 0 },
    { "visitor7", "VISITOR 7  -  Cracks a coconut on the tree, eats it (no-shake variant)", "Visitors", "FG/VISITOR7.FG2", "BMP/SCEXPL_VISITOR7.PSB", 91, 1, 0 },
    { "activity1", "ACTIVITY 1  -  Climbs the palm and belly-flops", "Activities", "FG/ACTIVITY1.FG2", "BMP/SCEXPL_ACTIVITY1.PSB", 194, 1, 0 },
    { "activity10", "ACTIVITY 10  -  Reads; seagull steals book", "Activities", "FG/ACTIVITY10.FG2", "BMP/SCEXPL_ACTIVITY10.PSB", 256, 1, 0 },
    { "activity11", "ACTIVITY 11  -  Bird steals Johnny's clothes", "Activities", "FG/ACTIVITY11.FG2", "BMP/SCEXPL_ACTIVITY11.PSB", 208, 1, 0 },
    { "activity12", "ACTIVITY 12  -  Bird on head, Johnny clubs himself", "Activities", "FG/ACTIVITY12.FG2", "BMP/SCEXPL_ACTIVITY12.PSB", 252, 1, 0 },
    { "activity4", "ACTIVITY 4  -  Climbs the palm and dives in", "Activities", "FG/ACTIVITY4.FG2", "BMP/SCEXPL_ACTIVITY4.PSB", 190, 1, 0 },
    { "activity5", "ACTIVITY 5  -  Rain dance, struck by lightning", "Activities", "FG/ACTIVITY5.FG2", "BMP/SCEXPL_ACTIVITY5.PSB", 169, 1, 0 },
    { "activity6", "ACTIVITY 6  -  Reads, falls asleep, coconut bonk", "Activities", "FG/ACTIVITY6.FG2", "BMP/SCEXPL_ACTIVITY6.PSB", 105, 1, 0 },
    { "activity7", "ACTIVITY 7  -  Reads a book upside-down", "Activities", "FG/ACTIVITY7.FG2", "BMP/SCEXPL_ACTIVITY7.PSB", 57, 1, 0 },
    { "activity8", "ACTIVITY 8  -  Bathes, then walks behind tree to dress", "Activities", "FG/ACTIVITY8.FG2", "BMP/SCEXPL_ACTIVITY8.PSB", 87, 1, 0 },
    { "activity9", "ACTIVITY 9  -  Rain dance, boat with couple passes, costume drops, naked", "Activities", "FG/ACTIVITY9.FG2", "BMP/SCEXPL_ACTIVITY9.PSB", 255, 1, 0 },
    { "miscgag1", "MISCGAG 1  -  Heat melts Johnny", "Misc & Suzy", "FG/MISCGAG1.FG2", "BMP/SCEXPL_MISCGAG1.PSB", 69, 1, 0 },
    { "miscgag2", "MISCGAG 2  -  Goes to bathe; a shark scares him off", "Misc & Suzy", "FG/MISCGAG2.FG2", "BMP/SCEXPL_MISCGAG2.PSB", 84, 1, 0 },
    { "suzy1", "SUZY 1  -  Suzy finds a letter from Johnny", "Misc & Suzy", "FG/SUZY1.FG2", "BMP/SCEXPL_SUZY1.PSB", 177, 1, 0 },
    { "suzy2", "SUZY 2  -  Johnny drifts in on his raft and meets Suzy", "Misc & Suzy", "FG/SUZY2.FG2", "BMP/SCEXPL_SUZY2.PSB", 133, 1, 0 },
    { "stand1", "STAND 1  -  Standing at the edge of the island", "Standing", "FG/STAND1.FG2", "BMP/SCEXPL_STAND1.PSB", 18, 1, 0 },
    { "stand10", "STAND 10  -  Looks at his raft, looks around", "Standing", "FG/STAND10.FG2", "BMP/SCEXPL_STAND10.PSB", 87, 1, 0 },
    { "stand11", "STAND 11  -  Left side of island, looks around", "Standing", "FG/STAND11.FG2", "BMP/SCEXPL_STAND11.PSB", 87, 1, 0 },
    { "stand12", "STAND 12  -  Looks forward, adjusts hat", "Standing", "FG/STAND12.FG2", "BMP/SCEXPL_STAND12.PSB", 238, 1, 0 },
    { "stand15", "STAND 15  -  Looks around with a spyglass", "Standing", "FG/STAND15.FG2", "BMP/SCEXPL_STAND15.PSB", 34, 1, 0 },
    { "stand16", "STAND 16  -  Spyglass, right side of island", "Standing", "FG/STAND16.FG2", "BMP/SCEXPL_STAND16.PSB", 36, 1, 0 },
    { "stand2", "STAND 2  -  Standing, adjusting pants", "Standing", "FG/STAND2.FG2", "BMP/SCEXPL_STAND2.PSB", 78, 1, 0 },
    { "stand3", "STAND 3  -  Standing at edge of island, adjusts hat", "Standing", "FG/STAND3.FG2", "BMP/SCEXPL_STAND3.PSB", 91, 1, 0 },
    { "stand4", "STAND 4  -  Standing at front of island, adjusts hat", "Standing", "FG/STAND4.FG2", "BMP/SCEXPL_STAND4.PSB", 107, 1, 0 },
    { "stand5", "STAND 5  -  Standing at front of island, looking out over the ocean", "Standing", "FG/STAND5.FG2", "BMP/SCEXPL_STAND5.PSB", 131, 1, 0 },
    { "stand6", "STAND 6  -  Looks out at the ocean, scratches head", "Standing", "FG/STAND6.FG2", "BMP/SCEXPL_STAND6.PSB", 118, 1, 0 },
    { "stand7", "STAND 7  -  Looks right, lifts hat", "Standing", "FG/STAND7.FG2", "BMP/SCEXPL_STAND7.PSB", 47, 1, 0 },
    { "stand8", "STAND 8  -  Right side of island, looks around, scratches head", "Standing", "FG/STAND8.FG2", "BMP/SCEXPL_STAND8.PSB", 44, 1, 0 },
    { "stand9", "STAND 9  -  By the palm, looks around, adjusts pants", "Standing", "FG/STAND9.FG2", "BMP/SCEXPL_STAND9.PSB", 47, 1, 0 },
    { "walkstuf1", "WALKSTUF 1  -  Parties on a yacht, comes back drunk, passes out", "Walking", "FG/WALKSTUF1.FG2", "BMP/SCEXPL_WALKSTUF1.PSB", 216, 1, 0 },
    { "walkstuf2", "WALKSTUF 2  -  Works on the raft", "Walking", "FG/WALKSTUF2.FG2", "BMP/SCEXPL_WALKSTUF2.PSB", 57, 1, 0 },
    { "walkstuf3", "WALKSTUF 3  -  Jogs around the island", "Walking", "FG/WALKSTUF3.FG2", "BMP/SCEXPL_WALKSTUF3.PSB", 439, 1, 0 },
    { "building1", "BUILDING 1  -  Sandcastle slumps, Johnny stomps it", "Building", "FG/BUILDING1.FG2", "BMP/SCEXPL_BUILDING1.PSB", 106, 1, 0 },
    { "building2", "BUILDING 2  -  Lilliputians take over the sandcastle and launch airplanes", "Building", "FG/BUILDING2.FG2", "BMP/SCEXPL_BUILDING2.PSB", 334, 1, 0 },
    { "building3", "BUILDING 3  -  Rolls over and takes a nap", "Building", "FG/BUILDING3.FG2", "BMP/SCEXPL_BUILDING3.PSB", 360, 1, 0 },
    { "building4", "BUILDING 4  -  Lilliputians tie Johnny down while he sleeps", "Building", "FG/BUILDING4.FG2", "BMP/SCEXPL_BUILDING4.PSB", 428, 1, 0 },
    { "building5", "BUILDING 5  -  Builds a fire and sits by it", "Building", "FG/BUILDING5.FG2", "BMP/SCEXPL_BUILDING5.PSB", 474, 1, 0 },
    { "building6", "BUILDING 6  -  Lilliputians tie Johnny up (no-bird variant)", "Building", "FG/BUILDING6.FG2", "BMP/SCEXPL_BUILDING6.PSB", 307, 1, 0 },
    { "building7", "BUILDING 7  -  Builds a fire, grills a fish, eats it", "Building", "FG/BUILDING7.FG2", "BMP/SCEXPL_BUILDING7.PSB", 460, 1, 0 },
};
const int gSceneExplorerCount = (int)(sizeof(gSceneExplorer) / sizeof(gSceneExplorer[0]));

const int gSceneExplorerFamilyStart[] = {
    0,
    8,
    14,
    19,
    25,
    35,
    39,
    53,
    56,
};
const int gSceneExplorerFamilyCount = (int)(sizeof(gSceneExplorerFamilyStart) / sizeof(gSceneExplorerFamilyStart[0]));
#else
extern const struct TSceneExplorerEntry gSceneExplorer[];
extern const int gSceneExplorerCount;
extern const int gSceneExplorerFamilyStart[];
extern const int gSceneExplorerFamilyCount;
#endif

#endif
