/* Auto-generated by scripts/generate-restore-pilot-header.py */
#ifndef PS1_RESTORE_PILOT_SPEC_H
#define PS1_RESTORE_PILOT_SPEC_H

#include "mytypes.h"

#define PS1_RESTORE_PILOT_ADS_NAME "STAND.ADS"
#define PS1_RESTORE_PILOT_ADS_TAG 1u
#define PS1_RESTORE_PILOT_ADS_TAG_COUNT 3u
#define PS1_RESTORE_PILOT_SCENE_INDEX 38u
#define PS1_RESTORE_PILOT_RECT_X 248u
#define PS1_RESTORE_PILOT_RECT_Y 196u
#define PS1_RESTORE_PILOT_RECT_WIDTH 352u
#define PS1_RESTORE_PILOT_RECT_HEIGHT 140u
#define PS1_RESTORE_PILOT_RECT_COUNT 2u
#define PS1_RESTORE_PILOT_TTM_COUNT 2u

struct TPs1RestorePilotRect {
    uint16 x;
    uint16 y;
    uint16 width;
    uint16 height;
};

struct TPs1RestorePilotTtm {
    const char *ttmName;
    uint16 clearRegionId;
    struct TPs1RestorePilotRect rect;
};

static const uint16 gPs1RestorePilotAdsTags[PS1_RESTORE_PILOT_ADS_TAG_COUNT] = { 1u, 2u, 3u };

static const struct TPs1RestorePilotRect gPs1RestorePilotRects[PS1_RESTORE_PILOT_RECT_COUNT] = {
    { 248u, 196u, 344u, 139u },
    { 256u, 197u, 344u, 139u },
};

static const struct TPs1RestorePilotTtm gPs1RestorePilotTtms[PS1_RESTORE_PILOT_TTM_COUNT] = {
    { "MJAMBWLK.TTM", 0u, { 248u, 196u, 344u, 139u } },
    { "MJTELE.TTM", 0u, { 256u, 197u, 344u, 139u } },
};

#endif
