/* Generated by scripts/gen-ship-sprite.py — do not edit.
 * Lilliputian galleon, SHIPS.BMP frame 9, scaled, byte-RLE of
 * packed 4bpp nibbles in SHIP.DAT on the CD; 15bpp palette here
 * (index 0 transparent). */
#define PS1_SHIP_SPRITE_W 132
#define PS1_SHIP_SPRITE_H 107
#define PS1_SHIP_SPRITE_RLE_LEN 4902
static const uint16 gPs1ShipPalette[16] = {
    0x0000, 0x5400, 0x02a0, 0x56a0, 0x0015, 0x0421, 0x02b5, 0x6b5a, 0x4210, 0x7c00, 0x03e0, 0x7fe0, 0x001f, 0x7c1f, 0x03ff, 0x7fff
};
