#!/usr/bin/env python3
"""Build PS1 pause-menu text offsets and disc blob."""

import json
import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "data/ps1/menu_text.json"
HEADER_OUTPUT = ROOT / "generated/ps1/ps1_menu_text_data.h"
DAT_OUTPUT = ROOT / "generated/ps1/MENUTEXT.DAT"


def c_id(raw: str) -> str:
    value = re.sub(r"[^A-Za-z0-9]+", "_", raw).strip("_").upper()
    if not value:
        raise RuntimeError(f"invalid menu text id: {raw!r}")
    if value[0].isdigit():
        value = "_" + value
    return "PMT_" + value


def main() -> None:
    entries = json.loads(SOURCE.read_text(encoding="utf-8"))
    blob = bytearray()
    offsets = []
    seen = set()

    for entry in entries:
        text_id = entry["id"]
        if text_id in seen:
            raise RuntimeError(f"duplicate menu text id: {text_id}")
        seen.add(text_id)

        encoded = entry["text"].encode("ascii") + b"\0"
        if len(blob) > 0xFFFF:
            raise RuntimeError("menu text blob exceeds 64 KiB")
        offsets.append((text_id, len(blob)))
        blob.extend(encoded)

    HEADER_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    DAT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    out = []
    out.append("/* Generated by scripts/build-menu-text-data.py.")
    out.append(" * Source: data/ps1/menu_text.json.")
    out.append(" * Re-run after menu text changes; do not edit by hand. */")
    out.append("")
    out.append("#ifndef PS1_MENU_TEXT_DATA_H")
    out.append("#define PS1_MENU_TEXT_DATA_H")
    out.append("")
    out.append('#include "mytypes.h"')
    out.append("")
    out.append("enum Ps1MenuTextId {")
    for text_id, _ in offsets:
        out.append(f"    {c_id(text_id)},")
    out.append("    PMT_COUNT")
    out.append("};")
    out.append("")
    out.append("#ifdef PS1_MENU_TEXT_DEFINE")
    out.append("const uint16 gPs1MenuTextOffsets[PMT_COUNT] = {")
    for text_id, offset in offsets:
        out.append(f"    {offset}, /* {c_id(text_id)} */")
    out.append("};")
    out.append("#else")
    out.append("extern const uint16 gPs1MenuTextOffsets[PMT_COUNT];")
    out.append("#endif")
    out.append("")
    out.append("#endif")
    out.append("")
    HEADER_OUTPUT.write_text("\n".join(out), encoding="utf-8")

    header = bytearray()
    header.extend(b"JCMT")
    header.extend(struct.pack("<HH", 1, len(offsets)))
    DAT_OUTPUT.write_bytes(bytes(header) + bytes(blob))

    print(
        f"Wrote {HEADER_OUTPUT.relative_to(ROOT)} "
        f"({len(offsets)} entries)"
    )
    print(
        f"Wrote {DAT_OUTPUT.relative_to(ROOT)} "
        f"({len(blob)} text bytes)"
    )


if __name__ == "__main__":
    main()
