#!/usr/bin/env python3
"""Build PS1 closed-caption lookup metadata and disc text blob."""

import json
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "data/ps1/captions.json"
HEADER_OUTPUT = ROOT / "generated/ps1/ps1_caption_data.h"
DAT_OUTPUT = ROOT / "generated/ps1/CAPTION.DAT"


def c_string(text: str) -> str:
    return json.dumps(text, ensure_ascii=True)


def main() -> None:
    entries = json.loads(SOURCE.read_text(encoding="utf-8"))
    blob = bytearray()
    rows = []

    for entry in entries:
        caption_id = entry["id"]
        text = entry["text"]
        encoded = text.encode("ascii") + b"\0"
        if len(blob) > 0xFFFF:
            raise RuntimeError("caption text blob exceeds 64 KiB")
        rows.append((caption_id, len(blob)))
        blob.extend(encoded)

    HEADER_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    DAT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    out = []
    out.append("/* Generated by scripts/build-caption-data.py.")
    out.append(" * Source: data/ps1/captions.json.")
    out.append(" * Re-run after caption text changes; do not edit by hand. */")
    out.append("")
    out.append("#ifndef PS1_CAPTION_DATA_H")
    out.append("#define PS1_CAPTION_DATA_H")
    out.append("")
    out.append("#include <stddef.h>")
    out.append('#include "mytypes.h"')
    out.append("")
    out.append("struct TCaptionDataEntry {")
    out.append("    const char *scene_id;")
    out.append("    uint16      text_offset; /* byte offset into CAPTION.DAT payload */")
    out.append("};")
    out.append("")
    out.append("#ifdef PS1_CAPTION_DATA_DEFINE")
    out.append("const struct TCaptionDataEntry gCaptionData[] = {")
    for caption_id, offset in rows:
        out.append(f"    {{ {c_string(caption_id)}, {offset} }},")
    out.append("    { NULL, 0 }")
    out.append("};")
    out.append(f"const uint16 gCaptionDataCount = {len(rows)};")
    out.append("#else")
    out.append("extern const struct TCaptionDataEntry gCaptionData[];")
    out.append("extern const uint16 gCaptionDataCount;")
    out.append("#endif")
    out.append("")
    out.append("#endif")
    out.append("")
    HEADER_OUTPUT.write_text("\n".join(out), encoding="utf-8")

    header = bytearray()
    header.extend(b"JCCP")
    header.extend(struct.pack("<HH", 1, len(rows)))
    DAT_OUTPUT.write_bytes(bytes(header) + bytes(blob))

    print(
        f"Wrote {HEADER_OUTPUT.relative_to(ROOT)} "
        f"({len(rows)} entries)"
    )
    print(
        f"Wrote {DAT_OUTPUT.relative_to(ROOT)} "
        f"({len(blob)} text bytes)"
    )


if __name__ == "__main__":
    main()
