#!/usr/bin/env python3
"""
extract-scene-mem.py — mine per-scene CACHE clean-rect demand from the
real FG2 pack headers, for the memory simulator (tests/mem_sim.c).

For every generated/ps1/foreground/*.FG2 it reads the header's union
sprite bounds and frame count, then computes — using the EXACT
clean-rect geometry from backdrop_clean.c.inc (wave band unioned with
the foreground bbox, split at y=190, clamped to 640x480) — the
worst-case clean-rect byte total and strip count over the island
position range, at each clean-rect cap. Emits a C table
(tests/scene_mem_table.h) the simulator replays instead of guessing.

FG2 header layout (pack_metadata.c.inc fgParseHeader):
  u16 @6  frameCount
  u16 @16 unionX   u16 @18 unionY
  u16 @20 unionW   u16 @22 unionH
"""
import struct, sys, glob, os

# clean-rect geometry constants (backdrop_clean.c.inc:190-194)
WAVE_MINX, WAVE_MINY, WAVE_ENDX, WAVE_ENDY = 129, 303, 608, 356
UPPER_SPLIT_Y = 190
SCRW, SCRH = 640, 480
# island position range (host/story.c VARPOS_OK)
POSX = range(-222, 20, 8)
POSY = range(-73, 85, 8)

def clamp(v, lo, hi): return lo if v < lo else hi if v > hi else v

def clean_rect_rects(fgx, fgy, fgw, fgh):
    """Replicate fgBackdropSaveCleanBgRectsForPack: return list of (w,h)
    rects (lower + optional upper) unioned with the wave band, clamped."""
    rects = []
    fgex, fgey = fgx + fgw, fgy + fgh
    # lower rect: union(fg-lower, wave band)
    lminx = min(fgx, WAVE_MINX); lminy = min(max(fgy, UPPER_SPLIT_Y), WAVE_MINY)
    lendx = max(fgex, WAVE_ENDX); lendy = max(fgey, WAVE_ENDY)
    lminx = clamp(lminx,0,SCRW); lminy = clamp(lminy,0,SCRH)
    lendx = clamp(lendx,0,SCRW); lendy = clamp(lendy,0,SCRH)
    if lendx > lminx and lendy > lminy:
        rects.append((lendx-lminx, lendy-lminy))
    # upper rect when fg extends above the split line
    if fgy < UPPER_SPLIT_Y:
        uminx = clamp(fgx,0,SCRW); uminy = clamp(fgy,0,SCRH)
        uendx = clamp(fgex,0,SCRW); uendy = clamp(UPPER_SPLIT_Y,0,SCRH)
        if uendx > uminx and uendy > uminy:
            rects.append((uendx-uminx, uendy-uminy))
    return rects

def rect_bytes(rects):
    return sum(w*h*2 for (w,h) in rects)

def strip_count(rects, cap):
    """grSaveCleanBgRectsSplit: each rect -> ceil(h / floor(cap/(w*2)))."""
    n = 0
    for (w,h) in rects:
        bpr = w*2
        if bpr == 0: continue
        maxrows = cap // bpr
        if maxrows == 0: maxrows = 1
        n += (h + maxrows - 1) // maxrows
    return n

def worst_over_positions(ux, uy, uw, uh, cap):
    """Max clean-rect bytes & strips across the island position sweep
    (fgBounds = union + island offset, screen coords)."""
    best_bytes = best_strips = 0
    for px in POSX:
        for py in POSY:
            rects = clean_rect_rects(ux+px, uy+py, uw, uh)
            best_bytes = max(best_bytes, rect_bytes(rects))
            best_strips = max(best_strips, strip_count(rects, cap))
    return best_bytes, best_strips

def read_fg2(path):
    with open(path,'rb') as f: h = f.read(40)
    if len(h) < 40: return None
    frames = struct.unpack_from('<H', h, 6)[0]
    ux,uy,uw,uh = struct.unpack_from('<HHHH', h, 16)
    return frames, ux, uy, uw, uh

def main(argv):
    fgdir = argv[1] if len(argv)>1 else "generated/ps1/foreground"
    out   = argv[2] if len(argv)>2 else "tests/scene_mem_table.h"
    rows = []
    for path in sorted(glob.glob(os.path.join(fgdir,"*.FG2"))):
        r = read_fg2(path)
        if not r: continue
        frames,ux,uy,uw,uh = r
        name = os.path.basename(path)[:-4]
        # report worst-case clean-rect bytes + strips at 48K/64K/96K caps
        b96,s96 = worst_over_positions(ux,uy,uw,uh, 96*1024)
        b64,s64 = worst_over_positions(ux,uy,uw,uh, 64*1024)
        b48,s48 = worst_over_positions(ux,uy,uw,uh, 48*1024)
        rows.append((name,frames,ux,uy,uw,uh,b96,s96,s64,s48))
    rows.sort(key=lambda r:-r[6])
    with open(out,'w') as o:
        o.write("/* GENERATED by scripts/extract-scene-mem.py — per-scene clean-rect\n")
        o.write(" * demand mined from the real FG2 pack headers (union bounds +\n")
        o.write(" * the backdrop_clean.c.inc geometry, worst case over island pos). */\n")
        o.write("#ifndef SCENE_MEM_TABLE_H\n#define SCENE_MEM_TABLE_H\n")
        o.write("typedef struct { const char*name; unsigned frames; unsigned cleanBytes;\n")
        o.write("                 unsigned strips96, strips64, strips48; } SceneMem;\n")
        o.write("static const SceneMem SCENE_MEM[] = {\n")
        for (name,frames,ux,uy,uw,uh,b96,s96,s64,s48) in rows:
            o.write('  {"%s",%u,%u,%u,%u,%u},\n'%(name,frames,b96,s96,s64,s48))
        o.write("};\n#define SCENE_MEM_COUNT ((int)(sizeof(SCENE_MEM)/sizeof(SCENE_MEM[0])))\n")
        o.write("#endif\n")
    print("scenes=%d  out=%s" % (len(rows), out))
    print("top clean-rect demand (worst-case over island position):")
    for r in rows[:12]:
        print("  %-12s frames=%-4u clean=%-7u strips@96K=%-2u @64K=%-2u @48K=%-2u" %
              (r[0],r[1],r[6],r[7],r[8],r[9]))
    # Slot-exhaustion verdict per config (GR_MAX_CLEAN_RECTS slots).
    max96 = max(r[7] for r in rows); max64 = max(r[8] for r in rows); max48 = max(r[9] for r in rows)
    over_fixed = [r[0] for r in rows if r[7] > 16]
    over_hist  = [r[0] for r in rows if r[9] > 8]
    over_hist64= [r[0] for r in rows if r[8] > 8]
    print("\n=== SLOT-EXHAUSTION VERDICT (worst case over every scene x island position) ===")
    print("FIXED   (96K cap, 16 slots): max strips=%d -> %d scenes exceed 16 %s" %
          (max96, len(over_fixed), "" if not over_fixed else over_fixed[:6]))
    print("HISTORIC(48K cap,  8 slots): max strips=%d -> %d scenes exceed 8  %s" %
          (max48, len(over_hist), over_hist[:6]))
    print("HISTORIC(64K cap,  8 slots): max strips=%d -> %d scenes exceed 8  %s" %
          (max64, len(over_hist64), over_hist64[:6]))
    print("=> %s" % ("FIXED config cannot slot-exhaust on ANY scene." if not over_fixed
                      else "WARNING: fixed config can slot-exhaust!"))
    return 0

if __name__=="__main__":
    raise SystemExit(main(sys.argv))
