#!/usr/bin/env python3
"""Generate src/platform/ps1/ps1_ship_sprite.h from SHIPS.BMP frame 9.

Boot loading indicator asset: the big Lilliputian galleon (frame 9,
user-picked "9A"), FULL SIZE (168x136). Stored as byte-RLE of the packed
4bpp nibbles (count,value pairs — ~6.9 KB vs 11.4 KB raw; the EXE has a
hard static-image ceiling) plus the 16-entry palette pre-converted to
PS1 15bpp. ps1_boot_progress.c decodes it into a heap buffer at boot.
Index 0 (magenta) is transparent -> black; the frame faces right, so no
mirroring. Embedding avoids any CD dependency for the indicator itself.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIMS = [(32, 8), (24, 8), (32, 10), (160, 34), (160, 34), (160, 34),
        (160, 34), (168, 102), (168, 136), (168, 136)]
FRAME = 9
TARGET_H = 107  # scale the whole galleon (flags intact) down from 136
                # so its top edge clears the bottom of the title artwork

def main():
    data = (ROOT / 'jc_resources/extracted/bmp/SHIPS.BMP').read_bytes()
    pal = (ROOT / 'jc_resources/extracted/pal/JOHNCAST.PAL').read_bytes()

    off = sum(w * h // 2 for w, h in DIMS[:FRAME])
    w, h = DIMS[FRAME]
    raw = data[off:off + w * h // 2]

    # Box-sample with majority vote per destination pixel (keeps the
    # 16-color indexed stream crisp — no anti-aliased inbetweens).
    nyb = []
    for b in raw:
        nyb += [(b >> 4) & 0xF, b & 0xF]
    H = TARGET_H
    W = (w * TARGET_H // h) & ~1
    small = []
    for Y in range(H):
        y0, y1 = Y * h // H, max(Y * h // H + 1, (Y + 1) * h // H)
        for X in range(W):
            x0, x1 = X * w // W, max(X * w // W + 1, (X + 1) * w // W)
            counts = {}
            for sy in range(y0, y1):
                for sx in range(x0, x1):
                    v = nyb[sy * w + sx]
                    if v:
                        counts[v] = counts.get(v, 0) + 1
            area = (y1 - y0) * (x1 - x0)
            if sum(counts.values()) * 2 >= area:
                small.append(max(counts, key=counts.get))
            else:
                small.append(0)
    raw = bytes((small[i] << 4) | small[i + 1] for i in range(0, len(small), 2))
    w, h = W, H

    rle = bytearray()
    i = 0
    while i < len(raw):
        j = i
        while j < len(raw) and j - i < 255 and raw[j] == raw[i]:
            j += 1
        rle += bytes((j - i, raw[i]))
        i = j

    palette = []
    for idx in range(16):
        r = pal[idx * 3] * 255 // 63
        g = pal[idx * 3 + 1] * 255 // 63
        b = pal[idx * 3 + 2] * 255 // 63
        if idx == 0:
            palette.append(0x0000)              # transparent -> black
        else:
            v = ((b >> 3) << 10) | ((g >> 3) << 5) | (r >> 3)
            palette.append(v if v else 0x0421)  # avoid 0 for opaque black

    # RLE payload ships on the CD (SHIP.DAT) — embedding it in the EXE
    # pushed the diagnostics-heavy regtest builds over the static-image
    # ceiling. The header keeps only dims + palette; the boot indicator
    # streams SHIP.DAT into the (boot-idle) scene-explorer chunk buffer.
    (ROOT / 'jc_resources' / 'SHIP.DAT').write_bytes(bytes(rle))
    out = (
        '/* Generated by scripts/gen-ship-sprite.py — do not edit.\n'
        ' * Lilliputian galleon, SHIPS.BMP frame 9, scaled, byte-RLE of\n'
        ' * packed 4bpp nibbles in SHIP.DAT on the CD; 15bpp palette here\n'
        ' * (index 0 transparent). */\n'
        '#define PS1_SHIP_SPRITE_W %d\n'
        '#define PS1_SHIP_SPRITE_H %d\n'
        '#define PS1_SHIP_SPRITE_RLE_LEN %d\n'
        'static const uint16 gPs1ShipPalette[16] = {\n    %s\n};\n'
    ) % (w, h, len(rle),
         ', '.join(f'0x{v:04x}' for v in palette))
    (ROOT / 'src/platform/ps1/ps1_ship_sprite.h').write_text(out)
    print(f'wrote ps1_ship_sprite.h + SHIP.DAT ({w}x{h}, rle {len(rle)} bytes)')

if __name__ == '__main__':
    main()
