#!/usr/bin/env python3
"""
generate-pack-metrics.py — produces src/generated/pack_header_metrics.{h,c}
from the scene-analysis JSON.

Per plan v9 step 5 / Phase 1 deliverable. The generated header is consumed
by mem_region_verify.c (the memVerifyAllScenesFitTransient and
memVerifyAllScenesPinnedFitCache boot-time checks).

Usage:
    python3 scripts/generate-pack-metrics.py \\
        --json docs/ps1/research/generated/scene_analysis_output_2026-03-21.json \\
        --out-h src/generated/pack_header_metrics.h \\
        --out-c src/generated/pack_header_metrics.c

The script reads per-scene peak_memory_bytes (the CACHE pinned working
set) and a conservative clean-rect estimate (the TRANSIENT worst-case
floor). For frame/prefetch/window/scratch buffer maxima, the analyzer
JSON doesn't currently expose those — placeholders of 0 are emitted
with a TODO comment, since those buffers are still on libc malloc as
of Phase 1's current commit set.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


HEADER_TEMPLATE = """/*
 * src/generated/pack_header_metrics.h
 *
 * GENERATED BY scripts/generate-pack-metrics.py — DO NOT EDIT BY HAND.
 *
 * Source: {source_json}
 * Scenes: {scene_count}
 *
 * Plan v9 references: step 5 (offline metrics), step 22 (CRC verify
 * gated by JC_VERIFY_PACK_HASHES, not yet emitted).
 */

#ifndef MEM_REGION_PACK_HEADER_METRICS_H
#define MEM_REGION_PACK_HEADER_METRICS_H

#include <stddef.h>
#include <stdint.h>

struct PackHeaderMetric {{
    const char *packName;
    uint32_t    maxFrameBytes;
    uint32_t    maxPrefetchBytes;
    uint32_t    maxStreamWindowBytes;
    uint32_t    maxStreamScratchBytes;
    uint32_t    transientWorstCase;
    uint32_t    cachePinnedWorstCase;
    uint32_t    headerCrc;
}};

extern const struct PackHeaderMetric kPackHeaderMetrics[];
extern const size_t kPackHeaderMetricsCount;

#endif
"""


C_TEMPLATE = """/*
 * src/generated/pack_header_metrics.c
 *
 * GENERATED BY scripts/generate-pack-metrics.py — DO NOT EDIT BY HAND.
 *
 * Source: {source_json}
 * Scenes: {scene_count}
 *
 * Frame/prefetch/window/scratch maxes are 0 placeholders (those
 * buffers are still on libc malloc as of the current Phase 1 commit
 * set; the analyzer JSON doesn't expose them yet). CRC is 0 until
 * Phase 1 step 22 lands.
 */

#include "pack_header_metrics.h"

const struct PackHeaderMetric kPackHeaderMetrics[] = {{
{entries}
}};

const size_t kPackHeaderMetricsCount =
    sizeof(kPackHeaderMetrics) / sizeof(kPackHeaderMetrics[0]);
"""


def estimate_clean_rect_bytes(memory_block: dict) -> int:
    """Conservative upper bound on per-scene clean-rect snapshot size.

    The analyzer JSON doesn't directly report clean-rect size, so we
    approximate from bmp_indexed_bytes (largest static draw) plus a
    32 KB safety margin for setup-segment scratch.
    """
    bmp = memory_block.get("bmp_indexed_bytes", 0)
    # Clean-rect is up to ~181 KB observed (FISHING1). Estimate as
    # min(bmp / 2, 200 KB) — bmp data informs the visible region.
    estimate = min(bmp // 2, 200 * 1024)
    # Setup segment scratch is ~32 KB worst case observed.
    return estimate + 32 * 1024


def make_entry(scene: dict) -> str:
    """One C struct initializer line for kPackHeaderMetrics[]."""
    name = f'{scene.get("ads_name", "?")}:{scene.get("ads_tag", 0)}'
    mem = scene.get("memory", {})
    peak = mem.get("peak_memory_bytes", 0)
    transient = estimate_clean_rect_bytes(mem)
    return (
        f'    {{ "{name}", 0u, 0u, 0u, 0u, '
        f'{transient}u, {peak}u, 0u }},'
    )


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--json", required=True, type=Path,
                    help="scene_analysis JSON input")
    ap.add_argument("--out-h", required=True, type=Path,
                    help="output .h path")
    ap.add_argument("--out-c", required=True, type=Path,
                    help="output .c path")
    args = ap.parse_args(argv)

    with args.json.open() as f:
        data = json.load(f)

    # The analyzer's scene list is under derived/scene_indices via
    # candidate_scene_clusters, but the per-scene records live under
    # a top-level "scenes" key (sample structure per the 2026-03-21
    # snapshot). Try both layouts for forward-compat.
    scenes = data.get("scenes")
    if not scenes:
        scenes = []
        for cluster in data.get("derived", {}).get("candidate_scene_clusters", []):
            # Cluster doesn't contain individual scene records; the
            # full per-scene list is referenced by indices. If the
            # JSON doesn't expose scenes directly, the generator
            # emits an empty table and warns.
            pass
        if not scenes:
            print(
                "WARN: per-scene records not found in JSON top level; "
                "generator emits an empty stub table. Update analyzer "
                "JSON layout or this script.",
                file=sys.stderr,
            )

    entries = "\n".join(make_entry(s) for s in scenes)
    if not entries:
        entries = '    { "stub", 0u, 0u, 0u, 0u, 0u, 0u, 0u },'

    h = HEADER_TEMPLATE.format(
        source_json=args.json,
        scene_count=len(scenes),
    )
    c = C_TEMPLATE.format(
        source_json=args.json,
        scene_count=len(scenes),
        entries=entries,
    )

    args.out_h.parent.mkdir(parents=True, exist_ok=True)
    args.out_c.parent.mkdir(parents=True, exist_ok=True)
    args.out_h.write_text(h)
    args.out_c.write_text(c)

    print(f"wrote {args.out_h} ({len(scenes)} scenes)")
    print(f"wrote {args.out_c}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
