#!/usr/bin/env python3
"""Generate a C header from the selected restore pilot spec."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


DEFAULT_SPEC = Path("docs/ps1/research/restore_pilot_spec_2026-03-18.json")
DEFAULT_HEADER = Path("src/foreground_pilot/ps1_restore_pilot_spec.h")


def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_header(spec: dict) -> str:
    selected = spec["selected_scene"]
    rect = spec["restore_template"]["union_rect"]
    rects = spec["restore_template"]["unique_rects"]
    ttm_details = spec["ttm_details"]
    ads_tags = spec["recommended_runtime_scope"]["ads_tags"]

    lines = [
        "/* Auto-generated by scripts/generate-restore-pilot-header.py */",
        "#ifndef PS1_RESTORE_PILOT_SPEC_H",
        "#define PS1_RESTORE_PILOT_SPEC_H",
        "",
        "#include \"mytypes.h\"",
        "",
        "#define PS1_RESTORE_PILOT_ADS_NAME " + c_string(selected["ads_name"]),
        f"#define PS1_RESTORE_PILOT_ADS_TAG {selected['ads_tag']}u",
        f"#define PS1_RESTORE_PILOT_ADS_TAG_COUNT {len(ads_tags)}u",
        f"#define PS1_RESTORE_PILOT_SCENE_INDEX {selected['scene_index']}u",
        f"#define PS1_RESTORE_PILOT_RECT_X {rect['x']}u",
        f"#define PS1_RESTORE_PILOT_RECT_Y {rect['y']}u",
        f"#define PS1_RESTORE_PILOT_RECT_WIDTH {rect['width']}u",
        f"#define PS1_RESTORE_PILOT_RECT_HEIGHT {rect['height']}u",
        f"#define PS1_RESTORE_PILOT_RECT_COUNT {len(rects)}u",
        f"#define PS1_RESTORE_PILOT_TTM_COUNT {len(ttm_details)}u",
        "",
        "struct TPs1RestorePilotRect {",
        "    uint16 x;",
        "    uint16 y;",
        "    uint16 width;",
        "    uint16 height;",
        "};",
        "",
        "struct TPs1RestorePilotTtm {",
        "    const char *ttmName;",
        "    uint16 clearRegionId;",
        "    struct TPs1RestorePilotRect rect;",
        "};",
        "",
        f"static const uint16 gPs1RestorePilotAdsTags[PS1_RESTORE_PILOT_ADS_TAG_COUNT] = {{ {', '.join(f'{tag}u' for tag in ads_tags)} }};",
        "",
        "static const struct TPs1RestorePilotRect gPs1RestorePilotRects[PS1_RESTORE_PILOT_RECT_COUNT] = {",
    ]
    for row in rects:
        lines.append(f"    {{ {row['x']}u, {row['y']}u, {row['width']}u, {row['height']}u }},")
    lines.extend(
        [
            "};",
            "",
            "static const struct TPs1RestorePilotTtm gPs1RestorePilotTtms[PS1_RESTORE_PILOT_TTM_COUNT] = {",
        ]
    )
    for row in ttm_details:
        region_ids = row.get("clear_region_ids") or [0]
        union_rect = row["union_rect"]
        lines.append(
            "    { "
            + c_string(row["ttm_name"])
            + f", {region_ids[0]}u, "
            + "{ "
            + f"{union_rect['x']}u, {union_rect['y']}u, {union_rect['width']}u, {union_rect['height']}u"
            + " } },"
        )
    lines.extend(["};", "", "#endif"])
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--spec", type=Path, default=DEFAULT_SPEC)
    ap.add_argument("--header", type=Path, default=DEFAULT_HEADER)
    return ap


def main() -> int:
    args = build_parser().parse_args()
    spec = load_json(args.spec)
    header = build_header(spec)
    args.header.write_text(header, encoding="utf-8")
    print(
        json.dumps(
            {
                "spec": str(args.spec),
                "header": str(args.header),
                "ads_name": spec["selected_scene"]["ads_name"],
                "ads_tag": spec["selected_scene"]["ads_tag"],
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
