#!/usr/bin/env python3
"""
Resolve a holidays picks JSON into a clean directory of selected PNGs,
ready for Phase D packaging into HOLIDAY.PSB.

Input:
  scratch/holidays-picks.json (or path passed via --picks)
  scratch/holidays-art/<id>-<short>-v{1..5}.png

Output:
  scratch/holidays-selected/<id>-<short>.png   (one PNG per holiday id)

Validation:
  * picks JSON must be a flat {id: variant} mapping
  * every reviewable holiday id (existing_sprite is null) must appear
  * every variant value must be 1..5
  * the corresponding PNG must exist on disk

Run:
  python3 scripts/holidays-resolve-picks.py
  python3 scripts/holidays-resolve-picks.py --picks scratch/holidays-picks-default.json
  python3 scripts/holidays-resolve-picks.py --strict   # exit 1 on any missing
"""
import argparse
import json
import shutil
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("error: PyYAML not installed\n")
    sys.exit(2)

REPO = Path(__file__).resolve().parent.parent
YAML_PATH = REPO / "holidays.yml"
ART_DIR = REPO / "scratch" / "holidays-art"
OUT_DIR = REPO / "scratch" / "holidays-selected"
DEFAULT_PICKS = REPO / "scratch" / "holidays-picks.json"


def slugify(name: str) -> str:
    return name.replace(" ", "_").replace("'", "").replace(".", "")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--picks", type=Path, default=DEFAULT_PICKS,
        help="picks JSON path (default: scratch/holidays-picks.json)")
    ap.add_argument(
        "--out", type=Path, default=OUT_DIR,
        help="output directory (default: scratch/holidays-selected/)")
    ap.add_argument(
        "--strict", action="store_true",
        help="exit non-zero on any missing pick or missing PNG")
    args = ap.parse_args()

    def show_path(p: Path) -> str:
        """Render a path as repo-relative when possible, else absolute."""
        try:
            return str(p.relative_to(REPO))
        except ValueError:
            return str(p)

    if not args.picks.exists():
        # Fall back to default picks file generated by holidays-default-picks.py
        fallback = REPO / "scratch" / "holidays-picks-default.json"
        if fallback.exists():
            print(f"note: {show_path(args.picks)} not found; "
                  f"falling back to {show_path(fallback)}")
            args.picks = fallback
        else:
            sys.stderr.write(
                f"error: picks file not found: {args.picks}\n"
                f"       run python3 scripts/holidays-default-picks.py to "
                f"generate a default first.\n")
            sys.exit(2)

    picks = json.loads(args.picks.read_text(encoding="utf-8"))
    if not isinstance(picks, dict):
        sys.stderr.write("error: picks JSON must be a flat object\n")
        sys.exit(2)
    # Coerce both keys and values to strings — the HTML preview saves
    # them as strings, but a hand-written picks file might use ints
    # (and the resolver should accept either).
    picks = {str(k): str(v) for k, v in picks.items()}

    holidays = yaml.safe_load(open(YAML_PATH, "r", encoding="utf-8"))
    reviewable = [h for h in holidays if h.get("existing_sprite") is None]

    # Validate the picks BEFORE touching the output dir, so a strict
    # failure leaves the previously-good staged picks intact.
    missing_picks = []
    invalid_variants = []
    missing_pngs = []
    plan: list[tuple[Path, Path]] = []  # (src, dst) for actual copies

    for h in reviewable:
        hid = str(h["id"])
        slug = slugify(h["short_name"])
        if hid not in picks:
            missing_picks.append((hid, h["name"]))
            continue
        vi = picks[hid]
        try:
            vi_int = int(vi)
        except (TypeError, ValueError):
            invalid_variants.append((hid, h["name"], repr(vi)))
            continue
        if not (1 <= vi_int <= 5):
            invalid_variants.append((hid, h["name"], vi_int))
            continue
        src = ART_DIR / f"{int(hid):02d}-{slug}-v{vi_int}.png"
        if not src.exists():
            missing_pngs.append((hid, h["name"], src.name))
            continue
        dst = args.out / f"{int(hid):02d}-{slug}.png"
        plan.append((src, dst))

    has_issues = bool(missing_picks or invalid_variants or missing_pngs)
    if args.strict and has_issues:
        # Don't touch the output directory; leave any prior good staging
        # intact so the user can rebuild from a known-good state.
        print(f"resolved 0 picks (strict, validation failed)")
        # Fall through to issue reporting below.
        resolved = 0
    else:
        args.out.mkdir(parents=True, exist_ok=True)
        # Clean the output dir so stale picks don't linger.
        for old in args.out.glob("*.png"):
            old.unlink()
        resolved = 0
        for src, dst in plan:
            shutil.copy2(src, dst)
            resolved += 1

    if not (args.strict and has_issues):
        print(f"resolved {resolved} picks → {show_path(args.out)}/")
    if missing_picks:
        print(f"\n{len(missing_picks)} reviewable holidays have NO pick:")
        for hid, name in missing_picks:
            print(f"  id={hid:>2}  {name}")
    if invalid_variants:
        print(f"\n{len(invalid_variants)} picks with invalid variant value:")
        for hid, name, v in invalid_variants:
            print(f"  id={hid:>2}  {name}: {v}")
    if missing_pngs:
        print(f"\n{len(missing_pngs)} picks reference a PNG that doesn't exist:")
        for hid, name, png in missing_pngs:
            print(f"  id={hid:>2}  {name}: {png}")

    if args.strict and (missing_picks or invalid_variants or missing_pngs):
        print("\nSTRICT mode: exiting 1 due to issues above.")
        sys.exit(1)


if __name__ == "__main__":
    main()
