"""
Batch-1 holiday renderers — covers IDs 5, 6, 7, 9, 10, 12, 13.

Four hand-authored variants per holiday: v1 literal, v2 minimalist,
v3 busy-scenic, v4 playful. v5 night is auto-generated by
holidays_concepts.py from v1; override here only if a hand-tuned
night version is needed.

Each render function takes a single arg `h` (the holiday entry from
holidays.yml as a parsed dict) and returns a `Sprite` instance at the
holiday's specified dimensions, drawn from the shared 16-color CLUT.
"""

from holidays_art_lib import (
    Sprite, PALETTE,
    TRANSPARENT, WHITE, BLACK, SKIN, TRUNK, GREEN, DGREEN,
    SKY, DEEPBLUE, SAND, RED, YELLOW, ORANGE, PINK, PURPLE, GRAY,
    compose_sand_strip, compose_sky, compose_palm_tree,
    compose_johnny_simple, compose_speech_bubble, compose_outlined_rect,
    compose_star, compose_heart, compose_horizon,
)


# ---------------------------------------------------------------------------
# id 5: Elvis's Birthday  (56×70, palette: white / gold / pink)
# Concept: Johnny in pompadour wig + rhinestone collar; tiny guitar leaned
# against the palm.
# ---------------------------------------------------------------------------

def elvis_v1(h):
    sp = Sprite(56, 70, fill=PINK)
    # Stage backdrop: pink upper, sand lower
    for y in range(0, 48):
        sp.line(0, y, 55, y, PINK)
    compose_sand_strip(sp, 48)
    # Spotlight glow from above (yellow rays)
    for x in range(20, 36, 3):
        sp.line(28, 0, x, 18, YELLOW)
    # Palm at left
    compose_palm_tree(sp, 10, 48, trunk_h=24, frond_r=8)
    # Guitar leaning against the palm — body + neck
    sp.ellipse(12, 38, 18, 47, TRUNK, outline=BLACK)
    sp.line(18, 38, 22, 30, TRUNK)
    sp.line(19, 38, 23, 30, TRUNK)
    sp.px(22, 30, WHITE); sp.px(23, 30, WHITE)
    # Strings (light)
    sp.line(13, 41, 21, 33, WHITE)
    # Johnny center stage
    compose_johnny_simple(sp, 28, 60, hat_color=BLACK, shirt_color=WHITE)
    # Pompadour wig — taller black mass on top of head
    sp.rect(27, 46, 33, 49, BLACK)
    sp.px(26, 48, BLACK); sp.px(34, 48, BLACK)
    sp.px(33, 46, BLACK); sp.px(34, 47, BLACK)
    # Rhinestone collar (yellow flecks at neck)
    sp.px(28, 52, YELLOW); sp.px(30, 52, YELLOW); sp.px(32, 52, YELLOW)
    sp.px(29, 53, WHITE);  sp.px(31, 53, WHITE)
    # Bell-bottom flare on legs (white)
    sp.px(27, 60, WHITE); sp.px(34, 60, WHITE)
    # Music notes drifting up
    for cx, cy in [(42, 12), (48, 22)]:
        sp.line(cx, cy, cx, cy + 4, BLACK)
        sp.ellipse(cx - 2, cy + 3, cx, cy + 5, BLACK)
    return sp


def elvis_v2(h):
    """Minimalist — single big pompadour silhouette + guitar icon."""
    sp = Sprite(56, 70, fill=PINK)
    compose_sand_strip(sp, 56)
    # Big stylized head + pompadour (centered)
    cx = 28
    # Pompadour swoop (black)
    sp.ellipse(cx - 12, 8, cx + 12, 22, BLACK)
    sp.rect(cx - 8, 18, cx + 8, 24, BLACK)
    # Face (skin)
    sp.ellipse(cx - 8, 20, cx + 8, 36, SKIN, outline=BLACK)
    # Sunglasses
    sp.rect(cx - 7, 26, cx - 2, 29, BLACK)
    sp.rect(cx + 2, 26, cx + 7, 29, BLACK)
    sp.line(cx - 2, 27, cx + 2, 27, BLACK)
    # Star above (rhinestone)
    compose_star(sp, cx, 5, 3, YELLOW)
    # Tiny guitar icon below the face
    sp.ellipse(cx - 8, 44, cx + 0, 54, TRUNK, outline=BLACK)
    sp.line(cx, 44, cx + 6, 38, TRUNK)
    sp.line(cx + 1, 44, cx + 7, 38, TRUNK)
    sp.px(cx - 4, 49, BLACK)  # sound hole
    return sp


def elvis_v3(h):
    """Busy/scenic — full island stage scene with Johnny, palms, crowd hint."""
    sp = Sprite(56, 70, fill=PINK)
    # Sky band: pink → orange sunset
    for y in range(0, 30):
        sp.line(0, y, 55, y, PINK if y < 15 else ORANGE)
    # Stage area — yellow strip
    sp.rect(0, 30, 55, 38, YELLOW)
    compose_sand_strip(sp, 38)
    # Two palms framing the stage
    compose_palm_tree(sp, 6, 38, trunk_h=16, frond_r=6)
    compose_palm_tree(sp, 50, 38, trunk_h=16, frond_r=6)
    # Stars in the sky
    compose_star(sp, 12, 6, 2, YELLOW)
    compose_star(sp, 30, 4, 2, WHITE)
    compose_star(sp, 46, 8, 2, YELLOW)
    # Johnny center
    compose_johnny_simple(sp, 25, 56, hat_color=BLACK, shirt_color=WHITE)
    # Pompadour
    sp.rect(24, 42, 30, 45, BLACK)
    sp.px(31, 43, BLACK)
    # Microphone in hand
    sp.line(32, 50, 32, 54, GRAY)
    sp.ellipse(31, 48, 33, 51, BLACK)
    # Rhinestones
    sp.px(25, 50, YELLOW); sp.px(28, 50, YELLOW)
    # Guitar in sand
    sp.ellipse(38, 60, 46, 66, TRUNK, outline=BLACK)
    sp.line(46, 60, 52, 54, TRUNK)
    # Crowd silhouette — little dots on near-side sand
    for x in range(2, 22, 3):
        sp.px(x, 65, BLACK)
        sp.px(x, 66, BLACK)
    # Music notes
    for cx, cy in [(40, 14), (48, 22)]:
        sp.line(cx, cy, cx, cy + 3, BLACK)
        sp.ellipse(cx - 1, cy + 2, cx, cy + 4, BLACK)
    return sp


# ---------------------------------------------------------------------------
# id 6: MLK Day  (88×56, palette: maroon / cream / gold)
# Concept: Johnny at attention beside small podium with paper banner.
# ---------------------------------------------------------------------------

def mlk_v1(h):
    sp = Sprite(88, 56, fill=YELLOW)
    # Sky cream/yellow, ground sand
    sp.rect(0, 0, 87, 39, YELLOW)
    compose_sand_strip(sp, 40)
    # Palm at far left
    compose_palm_tree(sp, 10, 40, trunk_h=22, frond_r=7)
    # Podium (center-ish): vertical stand + top
    podium_x = 40
    sp.rect(podium_x, 28, podium_x + 16, 42, RED, outline=BLACK)
    sp.rect(podium_x - 2, 26, podium_x + 18, 30, RED, outline=BLACK)
    # Banner draped on the podium front (cream paper)
    sp.rect(podium_x + 2, 32, podium_x + 14, 40, WHITE, outline=BLACK)
    # Three horizontal lines suggesting text on the banner
    sp.line(podium_x + 4, 34, podium_x + 12, 34, BLACK)
    sp.line(podium_x + 4, 36, podium_x + 12, 36, BLACK)
    sp.line(podium_x + 4, 38, podium_x + 11, 38, BLACK)
    # Microphone on top of podium
    sp.line(podium_x + 8, 22, podium_x + 8, 26, GRAY)
    sp.ellipse(podium_x + 7, 20, podium_x + 9, 23, BLACK)
    # Johnny standing at attention to the right
    compose_johnny_simple(sp, 64, 48, hat_color=None, shirt_color=RED)
    # Subtle ribbon/banner star above — bg is YELLOW so use WHITE
    compose_star(sp, 78, 8, 2, WHITE)
    return sp


def mlk_v2(h):
    """Minimalist — microphone silhouette against a warm dawn sky with a
    speech-bubble fragment so the speech motif reads at a glance.
    Previous version had a YELLOW star on a YELLOW fill (invisible)."""
    sp = Sprite(88, 56, fill=ORANGE)
    # Warm dawn band: yellow → orange → red, sand at the bottom
    sp.rect(0, 0, 87, 24, YELLOW)
    sp.rect(0, 24, 87, 38, ORANGE)
    sp.rect(0, 38, 87, 50, RED)
    compose_sand_strip(sp, 50)
    cx = 44
    # Mic stand
    sp.line(cx, 18, cx, 50, BLACK)
    sp.line(cx + 1, 18, cx + 1, 50, BLACK)
    # Mic head — black silhouette with a single white highlight
    sp.ellipse(cx - 6, 6, cx + 6, 22, BLACK)
    sp.ellipse(cx - 4, 8, cx + 4, 18, GRAY)
    sp.px(cx - 3, 10, WHITE); sp.px(cx - 3, 11, WHITE)
    # Mesh lines on mic
    sp.line(cx - 4, 12, cx + 4, 12, BLACK)
    sp.line(cx - 4, 15, cx + 4, 15, BLACK)
    # Quote-bubble fragment to the right of the mic
    sp.ellipse(cx + 14, 4, cx + 36, 18, WHITE, outline=BLACK)
    sp.line(cx + 16, 18, cx + 12, 22, BLACK)
    for x in (cx + 19, cx + 22, cx + 25, cx + 28, cx + 31):
        sp.px(x, 10, BLACK)
    # Star to the upper-left in WHITE so it pops against the yellow band
    compose_star(sp, cx - 24, 8, 3, WHITE)
    # Base
    sp.rect(cx - 8, 48, cx + 8, 50, BLACK)
    return sp


def mlk_v3(h):
    """Busy — Johnny addressing a small crowd from a flag-draped podium."""
    sp = Sprite(88, 56, fill=YELLOW)
    sp.rect(0, 0, 87, 39, YELLOW)
    compose_sand_strip(sp, 40)
    # Twin palms
    compose_palm_tree(sp, 6, 40, trunk_h=20, frond_r=6)
    compose_palm_tree(sp, 82, 40, trunk_h=20, frond_r=6)
    # Sun rays (cream) behind podium
    for x in range(20, 70, 6):
        sp.line(44, 4, x, 22, YELLOW)
    # Podium center
    px = 38
    sp.rect(px, 24, px + 12, 42, RED, outline=BLACK)
    sp.rect(px - 2, 22, px + 14, 26, RED, outline=BLACK)
    # Cream banner with three text lines
    sp.rect(px + 1, 28, px + 11, 40, WHITE, outline=BLACK)
    for ty in (30, 33, 36):
        sp.line(px + 3, ty, px + 9, ty, BLACK)
    # Mic
    sp.line(px + 6, 18, px + 6, 22, GRAY)
    sp.ellipse(px + 5, 16, px + 7, 19, BLACK)
    # Johnny behind/beside the podium (tiny head visible)
    sp.rect(px + 3, 18, px + 8, 22, SKIN)
    sp.px(px + 4, 19, BLACK); sp.px(px + 7, 19, BLACK)
    # Crowd silhouettes — heads on the foreground sand
    for x in range(8, 84, 6):
        sp.rect(x, 46, x + 3, 49, BLACK)
        sp.px(x + 1, 45, BLACK); sp.px(x + 2, 45, BLACK)
    # Stars dotted on sky — must use WHITE/ORANGE since the sky is YELLOW
    compose_star(sp, 14, 8, 2, WHITE)
    compose_star(sp, 74, 6, 2, ORANGE)
    return sp


# ---------------------------------------------------------------------------
# id 7: Groundhog Day  (64×48, palette: brown / orange / gray)
# Concept: Groundhog popping out of a sand-burrow, casting long shadow;
# Johnny squints skeptically.
# ---------------------------------------------------------------------------

def groundhog_v1(h):
    sp = Sprite(64, 48, fill=ORANGE)
    # Dawn sky orange top, sand below
    for y in range(0, 24):
        sp.line(0, y, 63, y, ORANGE if y < 14 else YELLOW)
    compose_sand_strip(sp, 24)
    # Burrow mound — darker sand bump in center-left
    sp.ellipse(14, 22, 34, 32, TRUNK, outline=BLACK)
    sp.ellipse(18, 24, 30, 30, BLACK)
    # Groundhog head poking out of burrow
    sp.ellipse(20, 18, 28, 26, TRUNK, outline=BLACK)
    # Ears
    sp.px(21, 18, TRUNK); sp.px(27, 18, TRUNK)
    sp.px(21, 17, BLACK); sp.px(27, 17, BLACK)
    # Eyes
    sp.px(22, 21, BLACK); sp.px(26, 21, BLACK)
    # Nose
    sp.px(24, 23, BLACK)
    # Buck teeth (white)
    sp.px(23, 24, WHITE); sp.px(25, 24, WHITE)
    # Long shadow trailing right across sand
    sp.line(28, 30, 56, 30, GRAY)
    sp.line(30, 31, 56, 31, GRAY)
    sp.line(32, 32, 56, 32, GRAY)
    # Johnny on the right squinting
    compose_johnny_simple(sp, 50, 42, hat_color=None, shirt_color=RED)
    # Replace eye dots with squint lines (one px each)
    sp.px(52, 32, BLACK); sp.px(53, 32, BLACK)
    return sp


def groundhog_v2(h):
    """Minimalist — single groundhog head + shadow."""
    sp = Sprite(64, 48, fill=ORANGE)
    compose_sand_strip(sp, 32)
    # Burrow circle
    sp.ellipse(20, 24, 44, 40, BLACK)
    sp.ellipse(22, 26, 42, 38, TRUNK)
    # Big groundhog head emerging
    sp.ellipse(24, 14, 40, 30, TRUNK, outline=BLACK)
    # Ears
    sp.rect(25, 12, 27, 14, TRUNK)
    sp.rect(37, 12, 39, 14, TRUNK)
    # Eyes (big)
    sp.rect(27, 18, 29, 20, BLACK)
    sp.rect(35, 18, 37, 20, BLACK)
    # Nose / mouth
    sp.px(32, 22, BLACK)
    sp.px(31, 24, BLACK); sp.px(33, 24, BLACK)
    # Long shadow stretching right
    sp.rect(40, 36, 60, 38, GRAY)
    return sp


def groundhog_v3(h):
    """Busy — full island scene, multiple burrow mounds, Johnny + palm."""
    sp = Sprite(64, 48, fill=ORANGE)
    for y in range(0, 22):
        sp.line(0, y, 63, y, ORANGE if y < 12 else YELLOW)
    compose_sand_strip(sp, 22)
    # Sun in sky
    sp.ellipse(48, 4, 60, 16, YELLOW, outline=ORANGE)
    # Palm on left
    compose_palm_tree(sp, 8, 22, trunk_h=14, frond_r=5)
    # Three burrow mounds
    for cx in (20, 36, 52):
        sp.ellipse(cx - 5, 22, cx + 5, 28, TRUNK, outline=BLACK)
        sp.ellipse(cx - 3, 24, cx + 3, 28, BLACK)
    # Groundhog popping out of middle burrow
    sp.ellipse(33, 16, 39, 24, TRUNK, outline=BLACK)
    sp.px(34, 16, TRUNK); sp.px(38, 16, TRUNK)
    sp.px(34, 19, BLACK); sp.px(38, 19, BLACK)  # eyes
    sp.px(36, 21, BLACK)  # nose
    # Long shadow
    sp.line(40, 28, 60, 28, GRAY)
    sp.line(40, 29, 58, 29, GRAY)
    # Johnny on right with skeptical posture
    compose_johnny_simple(sp, 56, 42, hat_color=None, shirt_color=RED)
    # Speech bubble with question mark area
    sp.ellipse(40, 32, 52, 40, WHITE, outline=BLACK)
    sp.px(45, 35, BLACK); sp.px(46, 35, BLACK)
    sp.px(46, 36, BLACK)
    sp.px(46, 38, BLACK)
    return sp


# ---------------------------------------------------------------------------
# id 9: Super Bowl  (96×56, palette: green / white / brown)
# Concept: Johnny in face paint with foam finger; football tee'd up;
# tiny driftwood goalposts.
# ---------------------------------------------------------------------------

def superbowl_v1(h):
    sp = Sprite(96, 56, fill=SKY)
    # Sky upper, green field lower
    sp.rect(0, 0, 95, 23, SKY)
    sp.rect(0, 24, 95, 55, GREEN)
    # Yard lines (white horizontals on the field)
    for y in (32, 40, 48):
        sp.line(0, y, 95, y, WHITE)
    # Goalposts driftwood — left end
    sp.line(8, 18, 8, 32, TRUNK)
    sp.line(9, 18, 9, 32, TRUNK)
    sp.line(4, 18, 12, 18, TRUNK)
    sp.line(4, 14, 4, 18, TRUNK)
    sp.line(12, 14, 12, 18, TRUNK)
    # Goalposts driftwood — right end
    sp.line(86, 18, 86, 32, TRUNK)
    sp.line(87, 18, 87, 32, TRUNK)
    sp.line(82, 18, 90, 18, TRUNK)
    sp.line(82, 14, 82, 18, TRUNK)
    sp.line(90, 14, 90, 18, TRUNK)
    # Football teed up center
    sp.ellipse(44, 36, 56, 42, TRUNK, outline=BLACK)
    # Football laces (white)
    sp.line(48, 39, 52, 39, WHITE)
    sp.px(49, 38, WHITE); sp.px(51, 38, WHITE)
    sp.px(49, 40, WHITE); sp.px(51, 40, WHITE)
    # Tee
    sp.line(50, 42, 50, 46, BLACK)
    sp.line(48, 46, 52, 46, BLACK)
    # Johnny on right with foam finger (red big hand)
    compose_johnny_simple(sp, 70, 50, hat_color=None, shirt_color=GREEN)
    # Face paint stripes
    sp.px(71, 40, GREEN); sp.px(74, 40, GREEN)
    # Foam finger (oversized red glove)
    sp.rect(78, 36, 86, 44, RED, outline=BLACK)
    sp.rect(82, 30, 86, 38, RED, outline=BLACK)  # extended index finger
    sp.line(76, 42, 78, 42, RED)
    return sp


def superbowl_v2(h):
    """Minimalist — single big football icon."""
    sp = Sprite(96, 56, fill=GREEN)
    compose_sand_strip(sp, 50)
    # Yard markings
    for y in (12, 24, 36):
        sp.line(0, y, 95, y, WHITE)
    # Big football (centered)
    cx, cy = 48, 28
    sp.ellipse(cx - 22, cy - 10, cx + 22, cy + 10, TRUNK, outline=BLACK)
    # Laces
    sp.line(cx - 6, cy, cx + 6, cy, WHITE)
    for dx in (-4, -2, 0, 2, 4):
        sp.line(cx + dx, cy - 2, cx + dx, cy + 2, WHITE)
    # White stripes at ends
    sp.line(cx - 18, cy - 4, cx - 18, cy + 4, WHITE)
    sp.line(cx + 18, cy - 4, cx + 18, cy + 4, WHITE)
    return sp


def superbowl_v3(h):
    """Busy — beach stadium scene with cheering Johnnys."""
    sp = Sprite(96, 56, fill=SKY)
    # Sky + field
    sp.rect(0, 0, 95, 19, SKY)
    sp.rect(0, 20, 95, 39, GREEN)
    compose_sand_strip(sp, 40)
    # Goalposts both ends
    for x_base in (6, 86):
        sp.line(x_base, 12, x_base, 24, TRUNK)
        sp.line(x_base + 1, 12, x_base + 1, 24, TRUNK)
        sp.line(x_base - 4, 12, x_base + 5, 12, TRUNK)
        sp.line(x_base - 4, 8, x_base - 4, 12, TRUNK)
        sp.line(x_base + 5, 8, x_base + 5, 12, TRUNK)
    # Yard lines on field
    for y in (26, 32):
        sp.line(0, y, 95, y, WHITE)
    # Football mid-field
    sp.ellipse(44, 30, 52, 34, TRUNK, outline=BLACK)
    sp.line(46, 32, 50, 32, WHITE)
    # Three Johnnys cheering on sand (different shirts)
    for i, x in enumerate([18, 44, 70]):
        shirt = [GREEN, WHITE, GREEN][i]
        compose_johnny_simple(sp, x, 52, hat_color=None, shirt_color=shirt)
        # Face-paint streak
        sp.px(x + 1, 42, GREEN); sp.px(x + 4, 42, GREEN)
    # Foam finger on the rightmost Johnny
    sp.rect(78, 38, 84, 46, RED, outline=BLACK)
    sp.rect(80, 32, 84, 40, RED, outline=BLACK)
    # Confetti in air
    for x, y, c in [(10, 4, WHITE), (30, 8, RED), (50, 4, WHITE),
                    (70, 6, GREEN), (88, 10, RED)]:
        sp.px(x, y, c); sp.px(x + 1, y, c)
    return sp


# ---------------------------------------------------------------------------
# id 10: Presidents' Day  (80×64, palette: navy / red / cream)
# Concept: Johnny in tricorn hat saluting tiny stars-and-stripes;
# cherry-tree sapling next to the palm.
# ---------------------------------------------------------------------------

def presidents_v1(h):
    sp = Sprite(80, 64, fill=DEEPBLUE)
    # Sky deep blue top, sand bottom
    sp.rect(0, 0, 79, 39, DEEPBLUE)
    compose_sand_strip(sp, 40)
    # Palm on left
    compose_palm_tree(sp, 10, 40, trunk_h=24, frond_r=8)
    # Cherry-tree sapling next to palm — short trunk + red dots
    sp.line(20, 40, 20, 32, TRUNK)
    sp.line(21, 40, 21, 32, TRUNK)
    sp.ellipse(15, 26, 26, 34, GREEN, outline=DGREEN)
    for cx, cy in [(17, 28), (22, 27), (19, 31), (24, 30)]:
        sp.px(cx, cy, RED); sp.px(cx + 1, cy, RED)
    # Flag on a pole — center-right
    sp.line(48, 18, 48, 50, TRUNK)
    sp.rect(49, 18, 64, 30, WHITE, outline=BLACK)
    # Stripes
    for y in (20, 22, 24, 26, 28):
        sp.line(56, y, 64, y, RED)
    # Canton
    sp.rect(49, 18, 56, 24, DEEPBLUE)
    # Tiny stars on canton
    for cx, cy in [(51, 20), (54, 20), (51, 22), (54, 22)]:
        sp.px(cx, cy, WHITE)
    # Johnny saluting on right
    compose_johnny_simple(sp, 70, 56, hat_color=DEEPBLUE, shirt_color=RED)
    # Tricorn hat — wider points on either side
    sp.px(69, 46, DEEPBLUE); sp.px(76, 46, DEEPBLUE)
    sp.px(68, 47, DEEPBLUE); sp.px(77, 47, DEEPBLUE)
    # Saluting hand — small line at brow
    sp.px(72, 49, SKIN); sp.px(73, 49, SKIN)
    return sp


def presidents_v2(h):
    """Minimalist — single tricorn-hat silhouette + a star."""
    sp = Sprite(80, 64, fill=DEEPBLUE)
    compose_sand_strip(sp, 56)
    # Big tricorn hat centered
    cx, cy = 40, 32
    # Brim — wide black
    sp.ellipse(cx - 24, cy + 4, cx + 24, cy + 14, BLACK)
    # Crown — black with a peak
    sp.rect(cx - 14, cy - 10, cx + 14, cy + 6, BLACK)
    sp.line(cx - 14, cy - 10, cx, cy - 18, BLACK)
    sp.line(cx, cy - 18, cx + 14, cy - 10, BLACK)
    # Cockade (red/white)
    sp.ellipse(cx - 4, cy - 4, cx + 4, cy + 4, RED, outline=WHITE)
    sp.px(cx, cy, WHITE)
    # Star above
    compose_star(sp, cx, 8, 3, WHITE)
    return sp


def presidents_v3(h):
    """Busy — patriotic island scene with multiple flags + cherry tree."""
    sp = Sprite(80, 64, fill=DEEPBLUE)
    # Sky gradient
    for y in range(0, 36):
        sp.line(0, y, 79, y, DEEPBLUE if y < 20 else SKY)
    compose_sand_strip(sp, 36)
    # Stars in sky
    for cx, cy in [(8, 6), (24, 4), (40, 8), (60, 4), (74, 8)]:
        compose_star(sp, cx, cy, 2, WHITE)
    # Palm + cherry sapling on left
    compose_palm_tree(sp, 8, 36, trunk_h=22, frond_r=7)
    sp.line(20, 36, 20, 28, TRUNK)
    sp.ellipse(15, 22, 26, 30, GREEN, outline=DGREEN)
    for cx, cy in [(17, 24), (22, 25), (19, 27), (23, 26)]:
        sp.px(cx, cy, RED)
    # Bunting along top — alternating red/white/blue triangles
    for i, x in enumerate(range(2, 80, 8)):
        c = [RED, WHITE, DEEPBLUE][i % 3]
        sp.line(x, 14, x + 4, 20, c)
        sp.line(x + 4, 20, x + 8, 14, c)
    # Center flag pole + flag
    sp.line(40, 22, 40, 50, TRUNK)
    sp.rect(41, 22, 56, 32, WHITE, outline=BLACK)
    for y in (24, 26, 28, 30):
        sp.line(48, y, 56, y, RED)
    sp.rect(41, 22, 48, 27, DEEPBLUE)
    for cx, cy in [(43, 24), (46, 24), (43, 26), (46, 26)]:
        sp.px(cx, cy, WHITE)
    # Johnny saluting on right
    compose_johnny_simple(sp, 64, 56, hat_color=DEEPBLUE, shirt_color=RED)
    sp.px(63, 46, DEEPBLUE); sp.px(70, 46, DEEPBLUE)
    sp.px(66, 49, SKIN); sp.px(67, 49, SKIN)
    # Smaller secondary flag held aloft on right
    sp.line(72, 50, 72, 42, TRUNK)
    sp.rect(73, 42, 78, 46, RED, outline=BLACK)
    return sp


# ---------------------------------------------------------------------------
# id 12: Pi Day  (48×40, palette: cream / brown / blue)
# Concept: Pie cooling on a rock; pi symbol drawn in sand;
# Johnny in nerd glasses holding slide rule.
# ---------------------------------------------------------------------------

def piday_v1(h):
    sp = Sprite(48, 40, fill=SKY)
    sp.rect(0, 0, 47, 19, SKY)
    compose_sand_strip(sp, 20)
    # Rock (gray) on left
    sp.ellipse(2, 18, 18, 26, GRAY, outline=BLACK)
    # Pie on the rock — circular crust
    sp.ellipse(4, 14, 16, 22, TRUNK, outline=BLACK)
    sp.ellipse(6, 16, 14, 20, ORANGE)  # filling
    # Steam wisps
    for cx in (8, 10, 12):
        sp.px(cx, 12, WHITE)
        sp.px(cx, 10, WHITE)
    # Pi symbol drawn in sand (right side, dark sand-brown lines)
    px = 30
    py = 30
    sp.line(px, py, px + 10, py, BLACK)         # top bar
    sp.line(px + 2, py, px + 2, py + 6, BLACK)  # left leg
    sp.line(px + 8, py, px + 8, py + 6, BLACK)  # right leg
    # Johnny on far right with glasses
    compose_johnny_simple(sp, 38, 36, hat_color=None, shirt_color=PURPLE)
    # Glasses — overdraw on eye line
    sp.rect(38, 27, 40, 29, BLACK)
    sp.rect(42, 27, 44, 29, BLACK)
    sp.line(40, 28, 42, 28, BLACK)
    # Slide rule (small white rectangle in hand)
    sp.rect(36, 32, 39, 33, WHITE)
    return sp


def piday_v2(h):
    """Minimalist — giant pi symbol over sand."""
    sp = Sprite(48, 40, fill=SKY)
    compose_sand_strip(sp, 32)
    # Big pi symbol centered
    cx = 24
    # Top bar
    sp.rect(cx - 14, 10, cx + 14, 14, BLACK)
    # Two legs
    sp.rect(cx - 10, 14, cx - 6, 30, BLACK)
    sp.rect(cx + 6, 14, cx + 10, 30, BLACK)
    # Curl on right leg foot (decorative)
    sp.px(cx + 11, 30, BLACK)
    sp.px(cx + 12, 29, BLACK)
    return sp


def piday_v3(h):
    """Busy — multiple pies, Johnny calculating, palm, big pi sky-writing."""
    sp = Sprite(48, 40, fill=SKY)
    sp.rect(0, 0, 47, 19, SKY)
    compose_sand_strip(sp, 20)
    # Pi sky-written by clouds (white pixels)
    sp.line(4, 4, 14, 4, WHITE)
    sp.line(6, 4, 6, 10, WHITE)
    sp.line(12, 4, 12, 10, WHITE)
    # Palm
    compose_palm_tree(sp, 4, 20, trunk_h=12, frond_r=4)
    # Two pies on rocks
    sp.ellipse(12, 22, 22, 28, GRAY, outline=BLACK)
    sp.ellipse(14, 18, 20, 24, TRUNK, outline=BLACK)
    sp.ellipse(15, 19, 19, 23, ORANGE)
    sp.ellipse(26, 26, 36, 32, GRAY, outline=BLACK)
    sp.ellipse(28, 22, 34, 28, TRUNK, outline=BLACK)
    sp.ellipse(29, 23, 33, 27, RED)  # cherry pie
    # Steam from both
    for cx in (16, 18, 30, 32):
        sp.px(cx, 17, WHITE); sp.px(cx, 15, WHITE)
    # Pi drawn in sand under the right pie
    sp.line(38, 33, 44, 33, BLACK)
    sp.px(39, 34, BLACK); sp.px(39, 35, BLACK)
    sp.px(43, 34, BLACK); sp.px(43, 35, BLACK)
    # Tiny Johnny tucked between pies
    compose_johnny_simple(sp, 22, 38, hat_color=None, shirt_color=PURPLE)
    sp.rect(22, 29, 23, 30, BLACK)
    sp.rect(25, 29, 26, 30, BLACK)
    return sp


# ---------------------------------------------------------------------------
# id 13: First Day of Spring  (96×80, palette: pink / green / blue)
# Concept: Cherry blossoms blooming on the palm; butterflies; Johnny
# stretching in the sun.
# ---------------------------------------------------------------------------

def spring_v1(h):
    sp = Sprite(96, 80, fill=PINK)
    # Sky pale blue, sand bottom
    sp.rect(0, 0, 95, 55, SKY)
    compose_sand_strip(sp, 56)
    # Sun in upper right
    sp.ellipse(76, 6, 90, 20, YELLOW, outline=ORANGE)
    # Palm with blossoms instead of fronds
    compose_palm_tree(sp, 24, 56, trunk_h=36, frond_r=12)
    # Pink blossom dots all around the palm crown
    for cx, cy in [(16, 18), (22, 14), (28, 16), (32, 22),
                   (12, 24), (36, 28), (20, 28), (30, 12)]:
        sp.px(cx, cy, PINK); sp.px(cx + 1, cy, PINK)
        sp.px(cx, cy + 1, PINK); sp.px(cx + 1, cy + 1, PINK)
        sp.px(cx + 1, cy + 1, WHITE)  # center highlight
    # Grass tufts along the sand
    for x in range(2, 96, 8):
        sp.px(x, 56, GREEN); sp.px(x + 1, 55, GREEN); sp.px(x + 2, 56, GREEN)
    # Butterflies — two-circle bodies with antennae
    for cx, cy, c in [(50, 18, YELLOW), (66, 28, PINK), (78, 38, PURPLE)]:
        sp.ellipse(cx - 3, cy - 2, cx, cy + 2, c)
        sp.ellipse(cx, cy - 2, cx + 3, cy + 2, c)
        sp.px(cx, cy, BLACK)
        sp.px(cx - 1, cy - 3, BLACK); sp.px(cx + 1, cy - 3, BLACK)
    # Johnny center-stretching — arms up
    compose_johnny_simple(sp, 56, 70, hat_color=None, shirt_color=GREEN)
    # Arms raised (skin pixels above shoulders)
    sp.px(55, 62, SKIN); sp.px(54, 60, SKIN); sp.px(53, 58, SKIN)
    sp.px(62, 62, SKIN); sp.px(63, 60, SKIN); sp.px(64, 58, SKIN)
    return sp


def spring_v2(h):
    """Minimalist — single cherry blossom branch + butterfly."""
    sp = Sprite(96, 80, fill=SKY)
    compose_sand_strip(sp, 70)
    # Single curved branch from lower left to upper right
    for i in range(30):
        x = 8 + i * 2
        y = 60 - i
        sp.px(x, y, TRUNK)
        sp.px(x, y + 1, TRUNK)
    # Big blossom clusters along branch
    for cx, cy in [(20, 52), (36, 42), (52, 32), (68, 22)]:
        sp.ellipse(cx - 6, cy - 6, cx + 6, cy + 6, PINK, outline=BLACK)
        sp.ellipse(cx - 2, cy - 2, cx + 2, cy + 2, WHITE)
        sp.px(cx, cy, YELLOW)
    # Single big butterfly upper-left
    cx, cy = 16, 16
    sp.ellipse(cx - 6, cy - 5, cx, cy + 5, PURPLE, outline=BLACK)
    sp.ellipse(cx, cy - 5, cx + 6, cy + 5, PURPLE, outline=BLACK)
    sp.px(cx, cy, BLACK)
    sp.px(cx - 1, cy - 6, BLACK); sp.px(cx + 1, cy - 6, BLACK)
    return sp


def spring_v3(h):
    """Busy — full vernal scene: blossoms, butterflies, tulips, Johnny."""
    sp = Sprite(96, 80, fill=SKY)
    sp.rect(0, 0, 95, 55, SKY)
    compose_sand_strip(sp, 56)
    # Big sun
    sp.ellipse(80, 4, 94, 18, YELLOW, outline=ORANGE)
    # Sun rays
    for dx, dy in [(-10, 0), (-7, -7), (0, -10), (7, -7)]:
        sp.line(87, 11, 87 + dx, 11 + dy, YELLOW)
    # Two palms with blossoms
    compose_palm_tree(sp, 16, 56, trunk_h=36, frond_r=10)
    compose_palm_tree(sp, 80, 56, trunk_h=32, frond_r=10)
    # Blossom clusters
    blossoms = [(8, 18), (14, 14), (20, 18), (24, 22), (12, 24),
                (74, 24), (80, 18), (86, 22), (78, 28)]
    for cx, cy in blossoms:
        sp.ellipse(cx - 1, cy - 1, cx + 1, cy + 1, PINK)
        sp.px(cx, cy, WHITE)
    # Tulips on the sand row
    for i, x in enumerate(range(34, 70, 6)):
        c = [RED, YELLOW, PINK, PURPLE, ORANGE, WHITE][i % 6]
        sp.line(x, 60, x, 66, GREEN)
        sp.ellipse(x - 2, 58, x + 2, 62, c, outline=BLACK)
        # Two leaves
        sp.px(x - 2, 64, GREEN); sp.px(x + 2, 64, GREEN)
    # Butterflies dotted around
    for cx, cy, c in [(32, 16, YELLOW), (48, 8, PINK), (60, 20, PURPLE),
                      (44, 30, ORANGE)]:
        sp.ellipse(cx - 3, cy - 2, cx, cy + 2, c)
        sp.ellipse(cx, cy - 2, cx + 3, cy + 2, c)
        sp.px(cx, cy, BLACK)
        sp.px(cx - 1, cy - 3, BLACK); sp.px(cx + 1, cy - 3, BLACK)
    # Johnny center stretching
    compose_johnny_simple(sp, 48, 72, hat_color=None, shirt_color=GREEN)
    sp.px(47, 64, SKIN); sp.px(46, 62, SKIN); sp.px(45, 60, SKIN)
    sp.px(54, 64, SKIN); sp.px(55, 62, SKIN); sp.px(56, 60, SKIN)
    # Grass tufts
    for x in range(2, 96, 5):
        sp.px(x, 56, GREEN); sp.px(x + 1, 55, GREEN)
    return sp


# ---------------------------------------------------------------------------
# v4 PLAYFUL variants — exaggerated, comedic, character-forward
# ---------------------------------------------------------------------------

def elvis_v4(h):
    """PLAYFUL — Elvis-Johnny mid hip-swivel: gigantic pompadour, sweat
    drops, motion lines, microphone tossed, swooning crowd dots."""
    sp = Sprite(56, 70, fill=PINK)
    for y in range(0, 48):
        sp.line(0, y, 55, y, PINK if y < 24 else ORANGE)
    compose_sand_strip(sp, 48)
    # Spotlights crisscrossing dramatically
    for x in range(8, 50, 4):
        sp.line(28, 0, x, 22, YELLOW)
    # Stars exploding around stage
    compose_star(sp, 6, 6, 3, YELLOW)
    compose_star(sp, 50, 4, 3, WHITE)
    compose_star(sp, 8, 22, 2, WHITE)
    compose_star(sp, 48, 24, 2, YELLOW)
    # Johnny mid-swivel, tilted
    jx = 26
    compose_johnny_simple(sp, jx, 60, hat_color=None, shirt_color=WHITE)
    # GIGANTIC pompadour — towering black mass
    sp.rect(jx - 4, 38, jx + 8, 44, BLACK)
    sp.rect(jx - 2, 34, jx + 6, 40, BLACK)
    sp.ellipse(jx - 5, 36, jx + 9, 42, BLACK)
    # Curl flick sticking out the side
    sp.px(jx + 9, 40, BLACK); sp.px(jx + 10, 41, BLACK)
    sp.px(jx + 11, 42, BLACK)
    # Sweat drops flying off
    sp.px(jx - 6, 46, SKY); sp.px(jx - 7, 45, SKY)
    sp.px(jx + 11, 46, SKY); sp.px(jx + 12, 45, SKY)
    # Comically wide grin
    sp.line(jx + 1, 51, jx + 4, 51, BLACK)
    sp.px(jx, 52, BLACK); sp.px(jx + 5, 52, BLACK)
    # Motion lines around legs (swiveling hips)
    sp.line(jx - 3, 58, jx - 5, 58, BLACK)
    sp.line(jx - 3, 60, jx - 6, 60, BLACK)
    sp.line(jx + 7, 58, jx + 9, 58, BLACK)
    sp.line(jx + 7, 60, jx + 10, 60, BLACK)
    # Microphone tossed up to the side, with arc lines
    sp.ellipse(40, 18, 44, 22, BLACK)
    sp.line(42, 22, 42, 26, GRAY)
    # Arc trail (dotted)
    for x, y in [(38, 24), (36, 28), (34, 32), (33, 36)]:
        sp.px(x, y, WHITE)
    # Music notes BIGGER, exaggerated
    for cx, cy in [(8, 14), (46, 38)]:
        sp.line(cx, cy, cx, cy + 6, BLACK)
        sp.ellipse(cx - 3, cy + 4, cx, cy + 7, BLACK)
        sp.line(cx + 1, cy - 2, cx + 4, cy, BLACK)  # extra flag
    # Swooning crowd hearts on near-side sand
    for cx in (4, 14, 38, 50):
        compose_heart(sp, cx, 65, 1, RED)
    # Big comedic exclamation
    sp.text(2, 32, "!?", BLACK)
    return sp


def mlk_v4(h):
    """PLAYFUL — Johnny passionately speaking, mouth wide open, hands
    flailing, banner streaming, oversized exclamation marks."""
    sp = Sprite(88, 56, fill=YELLOW)
    sp.rect(0, 0, 87, 39, YELLOW)
    compose_sand_strip(sp, 40)
    # Sun rays shooting outward (big motion)
    for x in range(8, 80, 4):
        sp.line(44, 4, x, 16, YELLOW)
    # Tilted podium (knocked askew by passion)
    px = 38
    sp.rect(px, 26, px + 14, 42, RED, outline=BLACK)
    sp.rect(px - 3, 22, px + 17, 28, RED, outline=BLACK)
    sp.line(px - 2, 22, px + 16, 21, BLACK)  # tilt
    # Banner streaming behind with motion squiggles
    sp.rect(px + 2, 32, px + 12, 40, WHITE, outline=BLACK)
    for ty in (34, 36, 38):
        sp.line(px + 4, ty, px + 10, ty, BLACK)
    # Streaming end of banner (motion strips)
    sp.line(px + 14, 33, px + 22, 32, WHITE)
    sp.line(px + 14, 36, px + 24, 36, WHITE)
    sp.line(px + 14, 39, px + 22, 40, WHITE)
    # Microphone with motion lines (gripped intensely)
    sp.line(px + 7, 18, px + 7, 22, GRAY)
    sp.ellipse(px + 6, 14, px + 9, 19, BLACK)
    sp.px(px + 4, 14, BLACK); sp.px(px + 11, 14, BLACK)  # speed lines
    sp.px(px + 4, 17, BLACK); sp.px(px + 11, 17, BLACK)
    # Johnny popping up behind podium, head HUGE & expressive
    sp.ellipse(px + 3, 12, px + 11, 22, SKIN, outline=BLACK)
    # Eyes scrunched, eyebrows up
    sp.line(px + 4, 14, px + 6, 13, BLACK)
    sp.line(px + 8, 13, px + 10, 14, BLACK)
    # Wide open mouth (yelling)
    sp.ellipse(px + 5, 17, px + 9, 21, BLACK)
    sp.line(px + 6, 19, px + 8, 19, RED)  # tongue
    # Sweat drop flying
    sp.px(px - 1, 14, SKY); sp.px(px - 2, 13, SKY)
    # Hands waving above (tiny skin blobs with motion)
    sp.px(px - 4, 18, SKIN); sp.px(px - 5, 16, SKIN); sp.px(px - 6, 18, SKIN)
    sp.px(px + 16, 18, SKIN); sp.px(px + 17, 16, SKIN); sp.px(px + 18, 18, SKIN)
    # Giant exclamation marks bursting around
    sp.rect(8, 6, 10, 14, RED)
    sp.rect(8, 16, 10, 18, RED)
    sp.rect(76, 4, 78, 12, RED)
    sp.rect(76, 14, 78, 16, RED)
    # Big star bursts in sky — bg is YELLOW so use WHITE/ORANGE
    compose_star(sp, 18, 26, 3, WHITE)
    compose_star(sp, 70, 28, 3, ORANGE)
    return sp


def groundhog_v4(h):
    """PLAYFUL — Groundhog with comically bugged-out eyes screaming at
    its own shadow; Johnny doing a spit-take, sweat drops everywhere."""
    sp = Sprite(64, 48, fill=ORANGE)
    for y in range(0, 24):
        sp.line(0, y, 63, y, ORANGE if y < 14 else YELLOW)
    compose_sand_strip(sp, 24)
    # Burrow with kicked-up sand bits
    sp.ellipse(10, 22, 36, 34, TRUNK, outline=BLACK)
    sp.ellipse(14, 24, 32, 32, BLACK)
    # Sand chunks flying out
    sp.px(8, 20, TRUNK); sp.px(7, 18, TRUNK)
    sp.px(38, 20, TRUNK); sp.px(40, 18, TRUNK)
    sp.px(38, 22, SAND); sp.px(8, 22, SAND)
    # Groundhog mid-pop, BIG bug eyes
    sp.ellipse(18, 14, 30, 26, TRUNK, outline=BLACK)
    # Huge googly eyes
    sp.ellipse(19, 17, 23, 21, WHITE, outline=BLACK)
    sp.ellipse(25, 17, 29, 21, WHITE, outline=BLACK)
    sp.px(21, 19, BLACK); sp.px(27, 19, BLACK)  # pupils askew
    # Eyebrows raised in panic
    sp.line(19, 16, 22, 15, BLACK)
    sp.line(26, 15, 29, 16, BLACK)
    # Buck teeth chattering, mouth open wide
    sp.ellipse(22, 22, 26, 25, BLACK)
    sp.px(23, 23, WHITE); sp.px(25, 23, WHITE)
    # Ears straight up in alarm
    sp.line(20, 13, 20, 11, TRUNK)
    sp.line(28, 13, 28, 11, TRUNK)
    # Sweat drops flying
    sp.px(16, 14, SKY); sp.px(15, 12, SKY)
    sp.px(32, 14, SKY); sp.px(33, 12, SKY)
    # Long jagged shadow stretching ominously
    sp.line(30, 30, 56, 30, GRAY)
    sp.line(32, 31, 58, 31, GRAY)
    sp.line(34, 32, 60, 32, GRAY)
    sp.line(36, 33, 62, 33, GRAY)
    # Shadow has an evil eye
    sp.px(54, 31, RED)
    # Johnny on right doing a spit-take
    jx = 50
    compose_johnny_simple(sp, jx, 42, hat_color=None, shirt_color=RED)
    # Spit/water spraying from his mouth back at the groundhog
    for x, y in [(48, 32), (46, 31), (44, 32), (42, 33), (40, 32)]:
        sp.px(x, y, SKY); sp.px(x, y + 1, SKY)
    # Wide eyes
    sp.px(jx + 1, 32, BLACK); sp.px(jx + 4, 32, BLACK)
    # Hands up in shock (motion blur lines)
    sp.line(jx - 2, 36, jx - 4, 34, BLACK)
    sp.line(jx + 7, 36, jx + 9, 34, BLACK)
    # Question marks above
    sp.text(2, 4, "?!", BLACK)
    sp.text(40, 6, "!", BLACK)
    return sp


def superbowl_v4(h):
    """PLAYFUL — Football mid-spiral with motion blur, Johnny celebrating
    overhead, foam finger HUGE, confetti, comically tiny goalpost wobble."""
    sp = Sprite(96, 56, fill=SKY)
    sp.rect(0, 0, 95, 23, SKY)
    sp.rect(0, 24, 95, 55, GREEN)
    for y in (32, 40, 48):
        sp.line(0, y, 95, y, WHITE)
    # Wobbly goalposts (drawn at angles)
    sp.line(8, 18, 6, 32, TRUNK)
    sp.line(9, 18, 7, 32, TRUNK)
    sp.line(4, 18, 12, 18, TRUNK)
    sp.line(4, 14, 4, 18, TRUNK)
    sp.line(12, 14, 12, 18, TRUNK)
    # Wobble motion lines
    sp.line(2, 22, 4, 22, BLACK); sp.line(2, 26, 4, 26, BLACK)
    # Right goalpost also wobbly
    sp.line(86, 18, 88, 32, TRUNK)
    sp.line(87, 18, 89, 32, TRUNK)
    sp.line(82, 18, 90, 18, TRUNK)
    sp.line(82, 14, 82, 18, TRUNK)
    sp.line(90, 14, 90, 18, TRUNK)
    sp.line(92, 22, 94, 22, BLACK); sp.line(92, 26, 94, 26, BLACK)
    # Football mid-spiral with motion arc
    sp.ellipse(38, 14, 54, 22, TRUNK, outline=BLACK)
    sp.line(42, 18, 50, 18, WHITE)
    sp.px(44, 17, WHITE); sp.px(46, 17, WHITE); sp.px(48, 17, WHITE)
    # Spiral motion arc (curved trail)
    for x, y in [(34, 24), (30, 28), (28, 32), (28, 36)]:
        sp.px(x, y, WHITE); sp.px(x + 1, y, WHITE)
    # Speed lines behind ball
    sp.line(20, 16, 36, 18, BLACK)
    sp.line(20, 20, 36, 21, BLACK)
    # Johnny center, jumping with arms up celebrating
    jx = 50
    base_y = 48
    compose_johnny_simple(sp, jx, base_y, hat_color=None, shirt_color=GREEN)
    # Raised arms
    sp.px(jx - 1, base_y - 9, SKIN); sp.px(jx - 2, base_y - 11, SKIN)
    sp.px(jx + 6, base_y - 9, SKIN); sp.px(jx + 7, base_y - 11, SKIN)
    # Open mouth screaming
    sp.ellipse(jx + 1, base_y - 9, jx + 4, base_y - 7, BLACK)
    # Face paint zigzag
    sp.line(jx, base_y - 10, jx + 5, base_y - 10, GREEN)
    sp.line(jx + 1, base_y - 12, jx + 4, base_y - 12, GREEN)
    # Motion lines under feet (jumping)
    sp.line(jx, base_y + 2, jx + 5, base_y + 2, BLACK)
    sp.line(jx - 2, base_y + 4, jx + 7, base_y + 4, BLACK)
    # GIANT foam finger overhead
    sp.rect(70, 8, 88, 24, RED, outline=BLACK)
    sp.rect(76, 0, 84, 12, RED, outline=BLACK)  # extended finger super tall
    # White "#1" on finger
    sp.line(78, 4, 78, 8, WHITE)
    sp.line(82, 4, 82, 8, WHITE)
    # Confetti shower
    for x, y, c in [(8, 4, RED), (24, 8, WHITE), (40, 6, GREEN),
                    (60, 4, RED), (78, 6, WHITE), (88, 8, GREEN),
                    (16, 12, RED), (44, 14, WHITE), (66, 16, GREEN)]:
        sp.px(x, y, c); sp.px(x + 1, y, c)
        sp.px(x, y + 1, c)
    # Star bursts
    compose_star(sp, 14, 28, 2, YELLOW)
    compose_star(sp, 80, 30, 2, YELLOW)
    return sp


def presidents_v4(h):
    """PLAYFUL — Tiny Johnny in absurdly oversized tricorn (covering most of
    head) saluting comically, flag flapping wildly with motion, cherry tree
    cartoonishly leaning."""
    sp = Sprite(80, 64, fill=DEEPBLUE)
    sp.rect(0, 0, 79, 39, DEEPBLUE)
    compose_sand_strip(sp, 40)
    # Stars galore in sky
    for cx, cy in [(8, 6), (20, 10), (32, 4), (50, 12), (66, 6), (76, 14)]:
        compose_star(sp, cx, cy, 2, WHITE)
    # Cherry tree LEANING dramatically (axed?)
    sp.line(18, 40, 26, 28, TRUNK)
    sp.line(19, 40, 27, 28, TRUNK)
    sp.ellipse(20, 22, 36, 32, GREEN, outline=DGREEN)
    # Cherries flying off (motion!)
    for cx, cy in [(28, 24), (30, 28), (38, 22), (40, 26), (44, 20)]:
        sp.px(cx, cy, RED); sp.px(cx + 1, cy, RED)
    # Motion lines from tree (it just got chopped at)
    sp.line(15, 36, 17, 38, BLACK)
    sp.line(13, 38, 16, 40, BLACK)
    # Flag flapping wildly with squiggly edge
    sp.line(50, 14, 50, 50, TRUNK)
    sp.rect(51, 14, 68, 28, WHITE, outline=BLACK)
    for y in (16, 18, 20, 22, 24, 26):
        sp.line(58, y, 68, y, RED)
    sp.rect(51, 14, 58, 22, DEEPBLUE)
    for cx, cy in [(53, 16), (56, 16), (53, 19), (56, 19)]:
        sp.px(cx, cy, WHITE)
    # Wavy flag end (squiggle)
    sp.px(69, 16, WHITE); sp.px(70, 17, WHITE); sp.px(71, 16, WHITE)
    sp.px(69, 22, WHITE); sp.px(70, 23, WHITE); sp.px(71, 22, WHITE)
    sp.px(69, 26, WHITE); sp.px(70, 27, WHITE); sp.px(71, 26, WHITE)
    # Wind speed lines
    sp.line(72, 18, 76, 18, BLACK)
    sp.line(72, 22, 78, 22, BLACK)
    sp.line(72, 26, 76, 26, BLACK)
    # Johnny on right with ABSURDLY oversized tricorn
    jx = 70
    compose_johnny_simple(sp, jx, 56, hat_color=None, shirt_color=RED)
    # Massive tricorn — wider and taller than head
    sp.rect(jx - 6, 46, jx + 11, 47, DEEPBLUE)
    sp.rect(jx - 4, 42, jx + 9, 46, DEEPBLUE)
    sp.line(jx - 6, 46, jx - 4, 41, DEEPBLUE)  # left peak
    sp.line(jx + 11, 46, jx + 9, 41, DEEPBLUE)  # right peak
    sp.line(jx + 1, 41, jx + 3, 38, DEEPBLUE)  # center peak (tall)
    sp.px(jx + 2, 38, YELLOW)  # cockade
    # Eyes peeking out from under hat
    sp.px(jx + 1, 49, BLACK); sp.px(jx + 4, 49, BLACK)
    # Comically rigid salute (forearm horizontal)
    sp.line(jx + 5, 50, jx + 9, 48, SKIN)
    sp.px(jx + 9, 47, SKIN)
    # Sweat drop (trying to keep hat on)
    sp.px(jx - 2, 49, SKY); sp.px(jx - 3, 48, SKY)
    # Floor pile of fallen wigs (white blobs)
    sp.ellipse(2, 56, 12, 60, WHITE, outline=BLACK)
    sp.px(6, 56, GRAY); sp.px(8, 56, GRAY)
    return sp


def piday_v4(h):
    """PLAYFUL — pie LAUNCHED in air mid-throw, Johnny with steam-cloud
    glasses askew, math symbols flying everywhere, crumb explosion."""
    sp = Sprite(48, 40, fill=SKY)
    sp.rect(0, 0, 47, 19, SKY)
    compose_sand_strip(sp, 20)
    # Pie airborne mid-throw, slightly tilted
    sp.ellipse(18, 4, 30, 12, TRUNK, outline=BLACK)
    sp.ellipse(20, 6, 28, 10, ORANGE)
    sp.px(24, 7, RED)  # cherry
    # Pie motion arc (dotted curve)
    for x, y in [(8, 14), (12, 10), (16, 8)]:
        sp.px(x, y, WHITE)
    # Crumbs flying off
    for x, y in [(32, 6), (34, 8), (16, 6), (14, 4), (30, 14)]:
        sp.px(x, y, ORANGE)
    # Speed lines behind pie
    sp.line(8, 4, 16, 4, BLACK)
    sp.line(6, 8, 14, 8, BLACK)
    # Math symbols flying around (pi, +, =, etc.)
    # Big π upper-left
    sp.line(2, 14, 6, 14, BLACK)
    sp.line(3, 14, 3, 18, BLACK)
    sp.line(5, 14, 5, 18, BLACK)
    # = sign
    sp.line(36, 14, 40, 14, BLACK)
    sp.line(36, 16, 40, 16, BLACK)
    # +
    sp.line(38, 4, 38, 8, BLACK)
    sp.line(36, 6, 40, 6, BLACK)
    # Johnny on right, dodging/crouched
    jx = 36
    compose_johnny_simple(sp, jx, 36, hat_color=None, shirt_color=PURPLE)
    # Glasses ASKEW (one lens lower)
    sp.rect(jx, 27, jx + 2, 29, BLACK)
    sp.rect(jx + 3, 28, jx + 5, 30, BLACK)
    sp.line(jx + 2, 28, jx + 3, 29, BLACK)
    # Sweat drops flying
    sp.px(jx - 2, 28, SKY); sp.px(jx - 3, 27, SKY)
    sp.px(jx + 7, 28, SKY); sp.px(jx + 8, 27, SKY)
    # Open mouth surprise
    sp.ellipse(jx + 1, 30, jx + 4, 32, BLACK)
    # Slide rule dropping with motion
    sp.rect(33, 34, 36, 35, WHITE)
    sp.line(33, 36, 36, 36, BLACK)  # falling line
    # Pi etched in sand with WIGGLE energy
    sp.line(8, 30, 18, 30, BLACK)
    sp.line(10, 30, 10, 36, BLACK)
    sp.line(15, 30, 15, 36, BLACK)
    # Pie splat on sand (left)
    sp.ellipse(2, 34, 8, 38, ORANGE, outline=BLACK)
    sp.px(0, 36, ORANGE); sp.px(1, 38, ORANGE)
    sp.px(9, 36, ORANGE); sp.px(10, 38, ORANGE)
    # Big "?!" exclamation
    sp.text(20, 22, "?!", BLACK)
    return sp


def spring_v4(h):
    """PLAYFUL — Johnny SNEEZING (huge AAACHOO), pollen clouds, butterflies
    fleeing in panic, blossoms blowing off the palm."""
    sp = Sprite(96, 80, fill=PINK)
    sp.rect(0, 0, 95, 55, SKY)
    compose_sand_strip(sp, 56)
    # Sun beaming (with face?)
    sp.ellipse(76, 6, 90, 20, YELLOW, outline=ORANGE)
    sp.px(80, 12, BLACK); sp.px(86, 12, BLACK)  # sun eyes
    sp.line(81, 16, 85, 16, BLACK)  # smile
    # Sun rays
    for dx, dy in [(-6, 0), (8, 0), (0, -6), (0, 8)]:
        sp.line(83, 13, 83 + dx, 13 + dy, YELLOW)
    # Palm with blossoms BLOWING off
    compose_palm_tree(sp, 24, 56, trunk_h=36, frond_r=12)
    # Blossoms airborne (motion direction: rightward)
    for cx, cy in [(36, 14), (44, 18), (52, 12), (60, 16),
                   (68, 22), (76, 28)]:
        sp.px(cx, cy, PINK); sp.px(cx + 1, cy, PINK)
        sp.px(cx, cy + 1, WHITE)
        # Motion trail
        sp.px(cx - 2, cy, PINK)
    # Bare-ish palm crown (some pink remaining)
    for cx, cy in [(20, 18), (28, 14), (16, 22)]:
        sp.px(cx, cy, PINK)
    # Wind/sneeze gust lines
    for y in [20, 26, 32]:
        sp.line(38, y, 70, y, WHITE)
    # Butterflies fleeing in panic (tilted, motion lines)
    for cx, cy, c in [(56, 36, YELLOW), (72, 40, PURPLE), (84, 44, PINK)]:
        sp.ellipse(cx - 3, cy - 2, cx, cy + 2, c)
        sp.ellipse(cx, cy - 2, cx + 3, cy + 2, c)
        sp.px(cx, cy, BLACK)
        # Panic motion lines
        sp.line(cx - 5, cy, cx - 7, cy, BLACK)
    # Johnny center with HUGE sneeze cloud
    jx = 44
    compose_johnny_simple(sp, jx, 76, hat_color=None, shirt_color=GREEN)
    # Giant sneeze cloud (white explosion)
    sp.ellipse(40, 50, 64, 66, WHITE, outline=BLACK)
    sp.ellipse(36, 54, 46, 62, WHITE, outline=BLACK)
    sp.ellipse(58, 52, 70, 62, WHITE, outline=BLACK)
    # "ACHOO!" inside cloud
    sp.text(44, 56, "AH!", BLACK)
    # Snot bits / pollen flying
    for cx, cy in [(34, 50), (66, 48), (28, 58), (72, 58)]:
        sp.px(cx, cy, YELLOW)
        sp.px(cx + 1, cy, YELLOW)
    # Hands clutched to face (skin pixels)
    sp.px(jx - 2, 68, SKIN); sp.px(jx - 3, 70, SKIN)
    sp.px(jx + 7, 68, SKIN); sp.px(jx + 8, 70, SKIN)
    # Tulips comically squashed flat
    for i, x in enumerate(range(60, 92, 6)):
        c = [RED, YELLOW, PINK, PURPLE][i % 4]
        sp.line(x, 60, x, 64, GREEN)
        sp.line(x - 2, 64, x + 2, 64, c)  # squashed flower
    # Pollen swirls in sky
    for cx, cy in [(8, 10), (14, 22), (20, 8)]:
        sp.px(cx, cy, YELLOW); sp.px(cx + 1, cy, YELLOW)
    return sp


# ---------------------------------------------------------------------------
# Public registry — runner imports this dict and invokes per-id variants.
# ---------------------------------------------------------------------------

RENDERERS_BATCH1 = {
    5:  (elvis_v1, elvis_v2, elvis_v3, elvis_v4),
    6:  (mlk_v1, mlk_v2, mlk_v3, mlk_v4),
    7:  (groundhog_v1, groundhog_v2, groundhog_v3, groundhog_v4),
    9:  (superbowl_v1, superbowl_v2, superbowl_v3, superbowl_v4),
    10: (presidents_v1, presidents_v2, presidents_v3, presidents_v4),
    12: (piday_v1, piday_v2, piday_v3, piday_v4),
    13: (spring_v1, spring_v2, spring_v3, spring_v4),
}
