#!/usr/bin/env python3
"""
Generate the C holiday table + the art-pipeline spec from holidays.yml.

Inputs:
  /home/hunter/workspace/jc_reborn/holidays.yml

Outputs:
  /home/hunter/workspace/jc_reborn/src/holidays_table.c
      C source with `gHolidays[]` static const array + gHolidayCount.
      Linked alongside src/holidays.c which contains the date-algorithm
      core. Schema must match struct Holiday in src/holidays.h.

  /home/hunter/workspace/jc_reborn/scripts/holidays-art-spec.json
      JSON list of art tasks: one entry per holiday that needs new
      AI-generated pixel art (existing_sprite is null). Consumed by
      the next phase's holidays-art-agent.py.

Run:
  python3 scripts/holidays-codegen.py
"""
import json
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("error: PyYAML not installed. pip install pyyaml\n")
    sys.exit(1)

REPO = Path(__file__).resolve().parent.parent
YAML_PATH = REPO / "holidays.yml"
TABLE_OUT = REPO / "src" / "holidays_table.c"
ART_SPEC_OUT = REPO / "scripts" / "holidays-art-spec.json"

KIND_MAP = {
    "fixed":           "HOLIDAY_KIND_FIXED",
    "nth_weekday":     "HOLIDAY_KIND_NTH_WEEKDAY",
    "easter_offset":   "HOLIDAY_KIND_EASTER_OFFSET",
    "solstice_winter": "HOLIDAY_KIND_SOLSTICE_WIN",
    "solstice_summer": "HOLIDAY_KIND_SOLSTICE_SUM",
    "equinox_vernal":  "HOLIDAY_KIND_EQUINOX_VER",
    "equinox_autumnal":"HOLIDAY_KIND_EQUINOX_AUT",
    "election_day":    "HOLIDAY_KIND_ELECTION_DAY",
}


def normalize_kind(rule: dict) -> dict:
    """Accept loose kind names from the design doc and map to our specific
    enum values using `month` to disambiguate the season."""
    rule = dict(rule or {})
    k = rule.get("kind")
    m = rule.get("month")
    if k == "equinox":
        rule["kind"] = "equinox_vernal" if m == 3 else "equinox_autumnal"
    elif k == "solstice":
        rule["kind"] = "solstice_summer" if m == 6 else "solstice_winter"
    return rule


def cstring(s: str) -> str:
    """Return a C string literal for `s`, escaping quotes and backslashes."""
    if s is None:
        return '""'
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def emit_table(holidays):
    lines = []
    lines.append("/*")
    lines.append(" * GENERATED by scripts/holidays-codegen.py from holidays.yml.")
    lines.append(" * DO NOT EDIT by hand — re-run the codegen instead.")
    lines.append(" */")
    lines.append("")
    lines.append('#include "holidays.h"')
    lines.append("")
    lines.append("const struct Holiday gHolidays[] = {")
    for h in holidays:
        rule  = normalize_kind(h.get("date_rule", {}) or {})
        kind  = KIND_MAP.get(rule.get("kind", "fixed"), "HOLIDAY_KIND_FIXED")
        month = int(rule.get("month", 0))
        day   = int(rule.get("day", 0))
        n     = int(rule.get("n", 0))
        weekday = int(rule.get("weekday", 0))
        easter_offset = int(rule.get("offset", 0))
        spr   = h.get("sprite", {}) or {}
        sw    = int(spr.get("width", 64))
        sh    = int(spr.get("height", 64))
        ix    = int(spr.get("island_x", 320))
        iy    = int(spr.get("island_y", 240))
        existing = h.get("existing_sprite")
        existing_idx = int(existing) if existing is not None else -1
        lines.append("    {")
        lines.append(f"        .id            = {int(h['id'])},")
        lines.append(f"        .short_name    = {cstring(h.get('short_name', h.get('name', '?')))},")
        lines.append(f"        .kind          = {kind},")
        lines.append(f"        .month         = {month},")
        lines.append(f"        .day           = {day},")
        lines.append(f"        .n             = {n},")
        lines.append(f"        .weekday       = {weekday},")
        lines.append(f"        .easter_offset = {easter_offset},")
        lines.append(f"        .sprite_w      = {sw},")
        lines.append(f"        .sprite_h      = {sh},")
        lines.append(f"        .island_x      = {ix},")
        lines.append(f"        .island_y      = {iy},")
        lines.append(f"        .existing_sprite_index = {existing_idx},")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append(f"const int gHolidayCount = {len(holidays)};")
    lines.append("")
    return "\n".join(lines)


def emit_art_spec(holidays):
    """List of holidays that need new AI-generated art."""
    spec = []
    for h in holidays:
        if h.get("existing_sprite") is not None:
            continue  # original 4 — sprite already exists
        spec.append({
            "id":          h["id"],
            "name":        h.get("name"),
            "short_name":  h.get("short_name"),
            "description": h.get("description"),
            "sprite": {
                "width":  int(h.get("sprite", {}).get("width",  64)),
                "height": int(h.get("sprite", {}).get("height", 64)),
            },
            "island_xy": [
                int(h.get("sprite", {}).get("island_x", 320)),
                int(h.get("sprite", {}).get("island_y", 240)),
            ],
            "palette":   h.get("palette", []),
        })
    return spec


def validate(holidays):
    """Sanity checks on the YAML data."""
    seen_ids = {}
    seen_names = {}
    issues = []
    for h in holidays:
        i = h.get("id")
        if not isinstance(i, int):
            issues.append(f"holiday {h.get('name', '?')}: missing/invalid id")
            continue
        if i in seen_ids:
            issues.append(f"duplicate id {i}: {seen_ids[i]} and {h.get('name')}")
        seen_ids[i] = h.get("name")
        n = h.get("name", "")
        if n in seen_names:
            issues.append(f"duplicate name {n!r}")
        seen_names[n] = i
        sn = h.get("short_name", "")
        if len(sn) > 12:
            issues.append(f"id {i} {n!r}: short_name {sn!r} >12 chars")
        rule = normalize_kind(h.get("date_rule") or {})
        kind = rule.get("kind")
        if kind not in KIND_MAP:
            issues.append(f"id {i} {n!r}: unknown date_rule.kind {kind!r}")
        if kind in ("fixed", "nth_weekday"):
            m = rule.get("month", 0)
            if not (1 <= m <= 12):
                issues.append(f"id {i} {n!r}: month {m} out of range")
        if kind == "fixed":
            d = rule.get("day", 0)
            if not (1 <= d <= 31):
                issues.append(f"id {i} {n!r}: day {d} out of range")
        if kind == "nth_weekday":
            nn = rule.get("n", 0)
            if not (nn == -1 or 1 <= nn <= 5):
                issues.append(f"id {i} {n!r}: n {nn} out of range (-1 or 1..5)")
            wd = rule.get("weekday", -1)
            if not (0 <= wd <= 6):
                issues.append(f"id {i} {n!r}: weekday {wd} out of range")
    return issues


def main():
    if not YAML_PATH.exists():
        sys.stderr.write(f"error: {YAML_PATH} not found\n")
        sys.exit(1)
    with open(YAML_PATH, "r", encoding="utf-8") as f:
        holidays = yaml.safe_load(f)
    if not isinstance(holidays, list):
        sys.stderr.write("error: holidays.yml must be a YAML list\n")
        sys.exit(1)
    holidays.sort(key=lambda h: int(h.get("id", 0)))

    issues = validate(holidays)
    if issues:
        sys.stderr.write("VALIDATION ISSUES:\n")
        for s in issues:
            sys.stderr.write(f"  - {s}\n")
        sys.stderr.write("(continuing — fix these in holidays.yml)\n\n")

    table_src = emit_table(holidays)
    TABLE_OUT.write_text(table_src, encoding="utf-8")
    print(f"wrote {TABLE_OUT.relative_to(REPO)}  ({len(holidays)} holidays)")

    art_spec = emit_art_spec(holidays)
    ART_SPEC_OUT.write_text(json.dumps(art_spec, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {ART_SPEC_OUT.relative_to(REPO)}  ({len(art_spec)} need art)")


if __name__ == "__main__":
    main()
