"""
Batch 3 holiday renderers — IDs 20..26 (Memorial through Watermelon).

Each render function takes a single arg: the holiday entry dict from
holidays.yml. It returns a `Sprite` (16-color indexed) at the dimensions
specified in the entry.

Four hand-authored variants per holiday:
  v1 — literal:    closest reading of the design doc concept
  v2 — minimalist: stripped-down silhouette / icon style
  v3 — busy:       full island scene with palm + sand + Johnny
  v4 — playful:    exaggerated/comedic — sweat drops, tilted, expressive

(v5 night is auto-generated by holidays_concepts.py from v1.)
"""

from holidays_art_lib import (
    Sprite, PALETTE,
    TRANSPARENT, WHITE, BLACK, SKIN, TRUNK, GREEN, DGREEN,
    SKY, DEEPBLUE, SAND, RED, YELLOW, ORANGE, PINK, PURPLE, GRAY,
    compose_sand_strip, compose_sky, compose_palm_tree,
    compose_johnny_simple, compose_speech_bubble, compose_outlined_rect,
    compose_star, compose_heart, compose_horizon,
)


# ---------------------------------------------------------------------------
# id 20: Memorial Day  (56×80, palette: navy/red/cream)
# Concept: American flag at half-mast on a driftwood pole; Johnny saluting;
# small white crosses in the sand.
# ---------------------------------------------------------------------------

def memorial_v1(h):
    sp = Sprite(56, 80, fill=SKY)
    compose_sand_strip(sp, 56)
    compose_horizon(sp, 56)
    # Driftwood flagpole — left side, weathered (TRUNK color)
    pole_x = 14
    sp.line(pole_x,     8, pole_x,     56, TRUNK)
    sp.line(pole_x + 1, 8, pole_x + 1, 56, TRUNK)
    # Knob on top
    sp.px(pole_x, 7, YELLOW); sp.px(pole_x + 1, 7, YELLOW)
    # Flag at half-mast — drawn at mid-pole, not the top
    fx, fy = pole_x + 2, 28
    sp.rect(fx,      fy,     fx + 18, fy + 11, WHITE, outline=BLACK)
    # Red stripes
    for i, sy in enumerate(range(fy + 1, fy + 11, 2)):
        sp.line(fx + 1, sy, fx + 17, sy, RED)
    # Blue canton
    sp.rect(fx + 1, fy + 1, fx + 8, fy + 5, DEEPBLUE)
    # Tiny stars on canton
    for sx in range(fx + 2, fx + 8, 2):
        for sy in range(fy + 2, fy + 5, 2):
            sp.px(sx, sy, WHITE)
    # Johnny saluting (right side)
    compose_johnny_simple(sp, 36, 56, hat_color=DEEPBLUE, shirt_color=DEEPBLUE)
    # Salute arm — diagonal line from shoulder up to forehead
    sp.line(40, 49, 42, 46, SKIN)
    sp.px(42, 45, SKIN)
    # Three small white crosses in the sand
    for cx in [6, 26, 48]:
        cy = 66
        sp.line(cx, cy, cx, cy + 5, WHITE)
        sp.line(cx - 1, cy + 2, cx + 1, cy + 2, WHITE)
    return sp


def memorial_v2(h):
    """Minimalist — single big flag silhouette over a horizon."""
    sp = Sprite(56, 80, fill=SKY)
    compose_horizon(sp, 56)
    compose_sand_strip(sp, 56)
    # Large centered flag
    fx, fy = 8, 18
    sp.rect(fx, fy, fx + 38, fy + 24, WHITE, outline=BLACK)
    # Red stripes
    for i in range(7):
        sy = fy + 1 + i * 3
        if sy < fy + 24:
            sp.rect(fx + 1, sy, fx + 37, sy + 1, RED)
    # Blue canton
    sp.rect(fx + 1, fy + 1, fx + 16, fy + 12, DEEPBLUE)
    # Stars on canton (5 dots)
    for cx, cy in [(fx + 4, fy + 4), (fx + 8, fy + 4), (fx + 12, fy + 4),
                   (fx + 6, fy + 8), (fx + 10, fy + 8)]:
        sp.px(cx, cy, WHITE)
    # Pole
    sp.line(fx - 1, fy - 4, fx - 1, 56, TRUNK)
    return sp


def memorial_v3(h):
    """Busy — full memorial scene with flag, Johnny, multiple crosses, palm."""
    sp = Sprite(56, 80, fill=SKY)
    # Sky gradient — pale top to fuller blue at horizon
    for y in range(0, 50):
        sp.line(0, y, 55, y, SKY)
    compose_horizon(sp, 50)
    # Sea band
    sp.rect(0, 50, 55, 55, DEEPBLUE)
    compose_sand_strip(sp, 56)
    # Palm tree on the right
    compose_palm_tree(sp, 46, 56, trunk_h=20, frond_r=8)
    # Flagpole (driftwood)
    pole_x = 12
    sp.line(pole_x,     6, pole_x,     56, TRUNK)
    sp.line(pole_x + 1, 6, pole_x + 1, 56, TRUNK)
    sp.px(pole_x, 5, YELLOW); sp.px(pole_x + 1, 5, YELLOW)
    # Flag half-mast
    fx, fy = pole_x + 2, 24
    sp.rect(fx, fy, fx + 16, fy + 10, WHITE, outline=BLACK)
    for sy in range(fy + 1, fy + 10, 2):
        sp.line(fx + 1, sy, fx + 15, sy, RED)
    sp.rect(fx + 1, fy + 1, fx + 7, fy + 4, DEEPBLUE)
    sp.px(fx + 3, fy + 2, WHITE); sp.px(fx + 5, fy + 2, WHITE)
    sp.px(fx + 4, fy + 3, WHITE)
    # Johnny saluting
    compose_johnny_simple(sp, 26, 64, hat_color=DEEPBLUE, shirt_color=DEEPBLUE)
    sp.line(30, 57, 32, 54, SKIN)
    # Crosses in sand
    for cx in [4, 18, 36, 50]:
        cy = 70
        sp.line(cx, cy, cx, cy + 5, WHITE)
        sp.line(cx - 1, cy + 2, cx + 1, cy + 2, WHITE)
    # Floating poppy specks
    for x, y in [(8, 60), (40, 62), (52, 68)]:
        sp.px(x, y, RED)
    return sp


# ---------------------------------------------------------------------------
# id 21: Father's Day  (80×56, palette: blue/brown/orange)
# Concept: Grilling barbecue on the beach; Johnny in 'World's Best Dad' apron
# flipping a coconut burger.
# ---------------------------------------------------------------------------

def fathersday_v1(h):
    sp = Sprite(80, 56, fill=SKY)
    compose_sand_strip(sp, 38)
    compose_horizon(sp, 38)
    # Palm tree on right
    compose_palm_tree(sp, 68, 38, trunk_h=20, frond_r=8)
    # Grill — brown body on three legs
    gx0, gy0, gx1, gy1 = 30, 26, 50, 36
    sp.rect(gx0, gy0, gx1, gy1, TRUNK, outline=BLACK)
    # Grill grate lines
    for sy in range(gy0 + 2, gy0 + 5, 2):
        sp.line(gx0 + 1, sy, gx1 - 1, sy, BLACK)
    # Legs
    sp.line(gx0 + 2, gy1, gx0 + 2, gy1 + 8, BLACK)
    sp.line(gx1 - 2, gy1, gx1 - 2, gy1 + 8, BLACK)
    # Flames/smoke rising orange
    for x, y in [(34, 22), (38, 20), (42, 22), (46, 19)]:
        sp.px(x, y, ORANGE)
        sp.px(x, y - 1, YELLOW)
    # Coconut burger on top of grill
    sp.ellipse(38, 23, 44, 26, TRUNK, outline=BLACK)
    # Johnny on the left, with apron
    compose_johnny_simple(sp, 12, 38, hat_color=None, shirt_color=ORANGE)
    # Apron (orange overlay across body)
    sp.rect(12, 30, 17, 35, ORANGE)
    # Apron straps
    sp.px(13, 28, ORANGE); sp.px(16, 28, ORANGE)
    # Spatula in his "hand" extended toward grill
    sp.line(18, 32, 28, 28, GRAY)
    sp.rect(27, 26, 30, 28, GRAY, outline=BLACK)
    return sp


def fathersday_v2(h):
    """Minimalist — a single grill icon + tie."""
    sp = Sprite(80, 56, fill=SKY)
    compose_sand_strip(sp, 40)
    # Big centered grill
    sp.ellipse(28, 18, 52, 30, TRUNK, outline=BLACK)
    sp.rect(28, 22, 52, 36, TRUNK, outline=BLACK)
    # Grate lines
    for sy in range(24, 36, 3):
        sp.line(30, sy, 50, sy, BLACK)
    # Legs
    sp.line(32, 36, 30, 46, BLACK)
    sp.line(48, 36, 50, 46, BLACK)
    # Flame coming over top — orange teardrop
    sp.ellipse(36, 8, 44, 18, ORANGE, outline=BLACK)
    sp.ellipse(38, 4, 42, 12, YELLOW)
    # Tie under the grill (necktie shape on the apron)
    sp.line(40, 36, 38, 44, ORANGE)
    sp.line(40, 36, 42, 44, ORANGE)
    sp.rect(37, 44, 43, 50, ORANGE, outline=BLACK)
    return sp


def fathersday_v3(h):
    """Busy — full beach BBQ scene with table, drink, smoke trails."""
    sp = Sprite(80, 56, fill=SKY)
    # Sky gradient
    for y in range(0, 38):
        sp.line(0, y, 79, y, SKY)
    compose_horizon(sp, 38)
    sp.rect(0, 38, 79, 40, DEEPBLUE)
    compose_sand_strip(sp, 40)
    # Two palms
    compose_palm_tree(sp, 8, 40, trunk_h=20, frond_r=8)
    compose_palm_tree(sp, 72, 40, trunk_h=22, frond_r=8)
    # Smoke puffs trailing up
    for x, y in [(36, 8), (40, 4), (44, 10), (48, 6), (52, 12)]:
        sp.ellipse(x, y, x + 3, y + 3, GRAY, outline=BLACK)
    # Grill
    sp.rect(34, 28, 52, 38, TRUNK, outline=BLACK)
    for sy in range(30, 36, 2):
        sp.line(35, sy, 51, sy, BLACK)
    sp.line(36, 38, 36, 46, BLACK)
    sp.line(50, 38, 50, 46, BLACK)
    # Flames/coals
    for x, y in [(38, 24), (42, 22), (46, 24), (40, 20), (44, 18)]:
        sp.px(x, y, ORANGE); sp.px(x, y - 1, YELLOW)
    # Burger on grill
    sp.ellipse(40, 26, 46, 29, TRUNK, outline=BLACK)
    # Side table on the left with a drink
    sp.rect(14, 34, 22, 40, TRUNK, outline=BLACK)
    sp.line(15, 40, 15, 46, TRUNK)
    sp.line(21, 40, 21, 46, TRUNK)
    # Drink
    sp.rect(16, 28, 20, 34, ORANGE, outline=BLACK)
    sp.line(18, 24, 18, 28, BLACK)  # straw
    # Johnny center-left in apron
    compose_johnny_simple(sp, 26, 46, hat_color=None, shirt_color=ORANGE)
    sp.rect(26, 38, 31, 43, ORANGE)
    # Spatula
    sp.line(32, 40, 38, 34, GRAY)
    sp.rect(37, 32, 40, 34, GRAY, outline=BLACK)
    # "DAD" sash hint — tiny heart on apron
    compose_heart(sp, 28, 41, 1, RED)
    return sp


# ---------------------------------------------------------------------------
# id 22: Summer Solstice  (112×96, palette: yellow/blue/orange)
# Concept: Bright noon sun directly overhead; Johnny napping in a hammock
# between palms; thermometer about to burst.
# ---------------------------------------------------------------------------

def summer_v1(h):
    sp = Sprite(112, 96, fill=SKY)
    compose_sand_strip(sp, 70)
    compose_horizon(sp, 70)
    # Big sun centered overhead
    sun_cx, sun_cy = 56, 18
    sp.ellipse(sun_cx - 12, sun_cy - 12, sun_cx + 12, sun_cy + 12,
               YELLOW, outline=ORANGE)
    # Sun rays radiating
    for dx, dy in [(-20, 0), (20, 0), (0, -18), (0, 18),
                   (-14, -14), (14, -14), (-14, 14), (14, 14)]:
        sp.line(sun_cx, sun_cy, sun_cx + dx, sun_cy + dy, YELLOW)
    # Inner highlight
    sp.ellipse(sun_cx - 4, sun_cy - 6, sun_cx, sun_cy - 2, WHITE)
    # Two palms — left and right
    compose_palm_tree(sp, 14, 70, trunk_h=36, frond_r=10)
    compose_palm_tree(sp, 98, 70, trunk_h=36, frond_r=10)
    # Hammock — sagging line + striped cloth
    hy = 56
    sp.line(16, hy - 4, 96, hy + 2, TRUNK)  # top rope
    sp.line(16, hy + 4, 96, hy + 10, TRUNK) # bottom rope
    # Hammock body — orange/yellow stripes (sagging curve approximated)
    for x in range(20, 94):
        # parabolic sag
        t = (x - 56) / 38
        ys = int(hy + 4 + (1 - t * t) * 6)
        c = ORANGE if ((x // 4) % 2 == 0) else YELLOW
        sp.line(x, hy + 1, x, ys, c)
    # Johnny napping in hammock
    sp.rect(48, 56, 64, 60, RED)  # body
    sp.ellipse(46, 52, 52, 58, SKIN, outline=BLACK)  # head
    sp.px(48, 54, BLACK); sp.px(50, 54, BLACK)  # closed eyes (Z's region)
    # ZZZ above
    sp.text(40, 44, "z", BLACK)
    sp.text(44, 40, "Z", BLACK)
    # Thermometer on right post — nearly bursting
    tx = 102
    sp.rect(tx, 50, tx + 4, 80, WHITE, outline=BLACK)
    sp.rect(tx + 1, 52, tx + 3, 78, RED)
    sp.ellipse(tx - 1, 78, tx + 5, 84, RED, outline=BLACK)
    # Burst ticks
    sp.px(tx + 6, 50, RED); sp.px(tx - 2, 50, RED)
    sp.px(tx + 7, 48, RED); sp.px(tx - 3, 48, RED)
    return sp


def summer_v2(h):
    """Minimalist — giant sun on a clean blue sky, single horizon."""
    sp = Sprite(112, 96, fill=SKY)
    compose_horizon(sp, 76)
    compose_sand_strip(sp, 76)
    # Massive sun centered
    sun_cx, sun_cy = 56, 36
    sp.ellipse(sun_cx - 24, sun_cy - 24, sun_cx + 24, sun_cy + 24,
               YELLOW, outline=ORANGE)
    # Inner core
    sp.ellipse(sun_cx - 14, sun_cy - 14, sun_cx + 14, sun_cy + 14, ORANGE)
    sp.ellipse(sun_cx - 8, sun_cy - 8, sun_cx + 8, sun_cy + 8, YELLOW)
    # Long rays
    for dx, dy in [(-40, 0), (40, 0), (0, -34), (0, 34),
                   (-28, -28), (28, -28), (-28, 28), (28, 28),
                   (-36, -16), (36, -16), (-36, 16), (36, 16)]:
        sp.line(sun_cx, sun_cy, sun_cx + dx, sun_cy + dy, YELLOW)
    # Highlight
    sp.ellipse(sun_cx - 6, sun_cy - 10, sun_cx - 2, sun_cy - 6, WHITE)
    return sp


def summer_v3(h):
    """Busy — full midday beach scene with sun, palms, hammock, drinks, thermometer."""
    sp = Sprite(112, 96, fill=SKY)
    # Sky gradient — brighter near horizon
    for y in range(0, 70):
        sp.line(0, y, 111, y, SKY)
    compose_horizon(sp, 70)
    sp.rect(0, 70, 111, 74, DEEPBLUE)
    compose_sand_strip(sp, 74)
    # Sun overhead
    sun_cx, sun_cy = 56, 16
    sp.ellipse(sun_cx - 10, sun_cy - 10, sun_cx + 10, sun_cy + 10,
               YELLOW, outline=ORANGE)
    for dx, dy in [(-16, 0), (16, 0), (0, -14), (0, 14),
                   (-12, -12), (12, -12), (-12, 12), (12, 12)]:
        sp.line(sun_cx, sun_cy, sun_cx + dx, sun_cy + dy, YELLOW)
    # Heat ripples (orange wavy lines)
    for y in [62, 66]:
        for x in range(20, 100, 8):
            sp.line(x, y, x + 3, y - 1, ORANGE)
            sp.line(x + 3, y - 1, x + 6, y, ORANGE)
    # Two palms
    compose_palm_tree(sp, 14, 74, trunk_h=38, frond_r=10)
    compose_palm_tree(sp, 98, 74, trunk_h=38, frond_r=10)
    # Hammock
    hy = 56
    sp.line(16, hy - 4, 96, hy + 2, TRUNK)
    sp.line(16, hy + 4, 96, hy + 10, TRUNK)
    for x in range(20, 94):
        t = (x - 56) / 38
        ys = int(hy + 4 + (1 - t * t) * 6)
        c = ORANGE if ((x // 4) % 2 == 0) else YELLOW
        sp.line(x, hy + 1, x, ys, c)
    # Johnny napping
    sp.rect(46, 56, 66, 60, RED)
    sp.ellipse(44, 52, 52, 58, SKIN, outline=BLACK)
    sp.px(46, 54, BLACK); sp.px(48, 54, BLACK)
    # Sunglasses on Johnny
    sp.rect(46, 53, 50, 55, BLACK)
    # Drink hanging off hammock
    sp.rect(70, 62, 74, 68, ORANGE, outline=BLACK)
    sp.line(72, 58, 72, 62, BLACK)
    # Thermometer right side
    tx = 104
    sp.rect(tx, 40, tx + 4, 78, WHITE, outline=BLACK)
    sp.rect(tx + 1, 42, tx + 3, 76, RED)
    sp.ellipse(tx - 1, 76, tx + 5, 82, RED, outline=BLACK)
    # Bursting at top
    for dx, dy in [(-3, -4), (-1, -6), (2, -6), (5, -4), (7, -2)]:
        sp.px(tx + 2 + dx, 40 + dy, RED)
    # ZZZ floating
    sp.text(36, 44, "z", BLACK)
    sp.text(40, 40, "Z", BLACK)
    sp.text(46, 36, "Z", BLACK)
    # Sand starfish
    for cx in [22, 88]:
        compose_star(sp, cx, 86, 3, ORANGE)
    return sp


# ---------------------------------------------------------------------------
# id 23: Pride Day  (112×64, palette: red/orange/purple)
# Concept: A rainbow flag flying above the palm; Johnny waving a smaller
# rainbow flag of his own.
# ---------------------------------------------------------------------------

_PRIDE_STRIPES = [RED, ORANGE, YELLOW, GREEN, SKY, PURPLE]


def pride_v1(h):
    sp = Sprite(112, 64, fill=SKY)
    compose_sand_strip(sp, 48)
    compose_horizon(sp, 48)
    # Single tall palm with rainbow flag at top
    px = 56
    compose_palm_tree(sp, px, 48, trunk_h=34, frond_r=10)
    # Rainbow flag attached to palm — to the right of trunk top
    fx, fy = px + 2, 8
    fw, fh = 28, 18
    # 6 stripes
    stripe_h = fh // 6
    for i, c in enumerate(_PRIDE_STRIPES):
        sp.rect(fx, fy + i * stripe_h, fx + fw, fy + (i + 1) * stripe_h - 1, c)
    # Flag outline
    sp.outline_rect(fx, fy, fx + fw, fy + fh, BLACK)
    # Flag pole already drawn by palm trunk; add little flutter
    sp.line(fx + fw, fy, fx + fw + 3, fy + 3, BLACK)
    sp.line(fx + fw, fy + fh, fx + fw + 3, fy + fh - 3, BLACK)
    # Johnny on right, waving smaller flag
    compose_johnny_simple(sp, 84, 48, hat_color=PURPLE, shirt_color=PINK)
    # Small flag in his hand
    sp.line(92, 38, 92, 46, TRUNK)
    mini_h = 1
    for i, c in enumerate(_PRIDE_STRIPES):
        sp.rect(93, 38 + i * mini_h, 100, 38 + i * mini_h, c)
    sp.outline_rect(93, 38, 100, 38 + 5, BLACK)
    return sp


def pride_v2(h):
    """Minimalist — one big rainbow flag filling the frame."""
    sp = Sprite(112, 64, fill=SKY)
    # Rainbow stripes filling the whole sprite
    stripe_h = 64 // 6
    for i, c in enumerate(_PRIDE_STRIPES):
        sp.rect(0, i * stripe_h, 111, (i + 1) * stripe_h - 1, c)
    # Border drawn as 4 lines (a rect with TRANSPARENT fill would erase
    # the stripes — this was a bug that left the sprite 94% transparent)
    sp.line(0, 0, 111, 0, BLACK)
    sp.line(0, 63, 111, 63, BLACK)
    sp.line(0, 0, 0, 63, BLACK)
    sp.line(111, 0, 111, 63, BLACK)
    # Tiny heart in the center for affection
    compose_heart(sp, 56, 32, 5, WHITE)
    return sp


def pride_v3(h):
    """Busy — parade scene with flag, multiple Johnnys, confetti, bunting."""
    sp = Sprite(112, 64, fill=SKY)
    compose_sand_strip(sp, 48)
    compose_horizon(sp, 48)
    # Bunting strung across the top — each segment a rainbow color
    for i, x in enumerate(range(4, 108, 8)):
        c = _PRIDE_STRIPES[i % 6]
        sp.line(x, 2, x + 3, 8, c)
        sp.line(x + 3, 8, x + 6, 2, c)
    # Palm with flag (left side)
    compose_palm_tree(sp, 16, 48, trunk_h=34, frond_r=10)
    fx, fy, fw, fh = 18, 12, 20, 12
    stripe_h = fh // 6
    for i, c in enumerate(_PRIDE_STRIPES):
        sp.rect(fx, fy + i * stripe_h, fx + fw, fy + (i + 1) * stripe_h - 1, c)
    sp.outline_rect(fx, fy, fx + fw, fy + fh, BLACK)
    # Three Johnnys parading
    for i, x in enumerate([48, 70, 92]):
        hat = _PRIDE_STRIPES[i * 2]
        shirt = _PRIDE_STRIPES[i * 2 + 1]
        compose_johnny_simple(sp, x, 56, hat_color=hat, shirt_color=shirt)
        # Each waving a tiny flag
        sp.line(x + 6, 46, x + 6, 52, TRUNK)
        for j, c in enumerate(_PRIDE_STRIPES):
            sp.px(x + 7, 46 + j, c)
            sp.px(x + 8, 46 + j, c)
    # Confetti rainbow dots
    confetti = [(8, 14, RED), (24, 18, ORANGE), (44, 12, YELLOW),
                (60, 22, GREEN), (78, 14, SKY), (98, 20, PURPLE),
                (32, 30, RED), (84, 32, YELLOW), (104, 28, PURPLE)]
    for x, y, c in confetti:
        sp.px(x, y, c); sp.px(x + 1, y, c)
    # Hearts floating
    compose_heart(sp, 60, 6, 2, PINK)
    compose_heart(sp, 80, 4, 2, RED)
    return sp


# ---------------------------------------------------------------------------
# id 24: Independence Day  (144×80, palette: navy/red/white)
# Concept: Sparklers held by Johnny; fireworks blooming in the sky over the
# ocean; tiny stars-and-stripes.
# ---------------------------------------------------------------------------

def july4th_v1(h):
    sp = Sprite(144, 80, fill=DEEPBLUE)
    # Night sky already set by fill
    compose_sand_strip(sp, 60)
    # Horizon (ocean reflecting deep blue)
    sp.rect(0, 56, 143, 60, DEEPBLUE)
    sp.line(0, 56, 143, 56, BLACK)
    # Two firework bursts in the sky
    def burst(cx, cy, color, r=8):
        for k in range(8):
            import math
            ang = k * 3.14159 / 4
            dx = int(r * (1 if k in (0,) else (0.7 if k in (1,3,5,7) else 1)) * (1 if k in (0,4) else 0))
        # Use radial line strokes
        sp.px(cx, cy, WHITE)
        for dx, dy in [(-r, 0), (r, 0), (0, -r), (0, r),
                       (-r * 3 // 4, -r * 3 // 4), (r * 3 // 4, -r * 3 // 4),
                       (-r * 3 // 4, r * 3 // 4), (r * 3 // 4, r * 3 // 4)]:
            sp.line(cx, cy, cx + dx, cy + dy, color)
        # tip dots
        for dx, dy in [(-r, 0), (r, 0), (0, -r), (0, r)]:
            sp.px(cx + dx, cy + dy, WHITE)
    burst(32, 18, RED, r=10)
    burst(96, 14, WHITE, r=8)
    burst(120, 26, RED, r=6)
    # Tiny stars sprinkled
    for x, y in [(8, 6), (60, 8), (80, 4), (140, 8), (52, 30), (108, 36)]:
        sp.px(x, y, WHITE)
    # Palm silhouette right side
    compose_palm_tree(sp, 130, 60, trunk_h=24, frond_r=8)
    # Johnny holding sparklers, center-left
    compose_johnny_simple(sp, 60, 60, hat_color=RED, shirt_color=WHITE)
    # Sparkler stick (left hand)
    sp.line(58, 50, 50, 42, GRAY)
    sp.line(50, 42, 48, 40, YELLOW)
    sp.px(46, 38, WHITE); sp.px(48, 36, YELLOW); sp.px(44, 40, RED)
    # Sparkler stick (right hand)
    sp.line(66, 50, 74, 42, GRAY)
    sp.line(74, 42, 76, 40, YELLOW)
    sp.px(78, 38, WHITE); sp.px(76, 36, YELLOW); sp.px(80, 40, RED)
    # Tiny stars-and-stripes flag planted in sand
    pole_x = 100
    sp.line(pole_x, 50, pole_x, 70, TRUNK)
    sp.rect(pole_x + 1, 50, pole_x + 14, 58, WHITE, outline=BLACK)
    for sy in range(51, 58, 2):
        sp.line(pole_x + 1, sy, pole_x + 14, sy, RED)
    sp.rect(pole_x + 1, 50, pole_x + 7, 54, DEEPBLUE)
    sp.px(pole_x + 3, 52, WHITE); sp.px(pole_x + 5, 52, WHITE)
    return sp


def july4th_v2(h):
    """Minimalist — one big firework burst on a night-sky field."""
    sp = Sprite(144, 80, fill=DEEPBLUE)
    compose_sand_strip(sp, 70)
    # Single huge firework
    cx, cy = 72, 36
    # Long radial rays, alternating colors
    rays = [(-32, 0, RED), (32, 0, RED), (0, -28, WHITE), (0, 28, WHITE),
            (-24, -24, RED), (24, -24, RED), (-24, 24, WHITE), (24, 24, WHITE),
            (-30, -12, WHITE), (30, -12, WHITE), (-30, 12, RED), (30, 12, RED),
            (-12, -30, RED), (12, -30, RED), (-12, 28, WHITE), (12, 28, WHITE)]
    for dx, dy, c in rays:
        sp.line(cx, cy, cx + dx, cy + dy, c)
    # Central core
    sp.ellipse(cx - 4, cy - 4, cx + 4, cy + 4, YELLOW, outline=WHITE)
    # Tip stars
    for dx, dy in [(-32, 0), (32, 0), (0, -28), (0, 28),
                   (-24, -24), (24, -24), (-24, 24), (24, 24)]:
        sp.px(cx + dx, cy + dy, WHITE)
    return sp


def july4th_v3(h):
    """Busy — multiple fireworks, Johnny, palms, ocean, flag, crowd-feel."""
    sp = Sprite(144, 80, fill=DEEPBLUE)
    # Night gradient — slightly lighter near bottom for ocean glow
    for y in range(54, 60):
        sp.line(0, y, 143, y, DEEPBLUE)
    compose_sand_strip(sp, 60)
    sp.line(0, 55, 143, 55, BLACK)
    # Stars in night sky
    star_pts = [(6, 4), (16, 10), (28, 6), (44, 4), (58, 12), (72, 6),
                (86, 4), (100, 10), (118, 6), (132, 4), (140, 12),
                (10, 24), (50, 28), (90, 26), (130, 28)]
    for x, y in star_pts:
        sp.px(x, y, WHITE)
    # Multiple firework bursts in different colors
    def burst(cx, cy, color, r=8):
        for dx, dy in [(-r, 0), (r, 0), (0, -r), (0, r),
                       (-r * 3 // 4, -r * 3 // 4), (r * 3 // 4, -r * 3 // 4),
                       (-r * 3 // 4, r * 3 // 4), (r * 3 // 4, r * 3 // 4)]:
            sp.line(cx, cy, cx + dx, cy + dy, color)
        for dx, dy in [(-r, 0), (r, 0), (0, -r), (0, r)]:
            sp.px(cx + dx, cy + dy, WHITE)
        sp.px(cx, cy, YELLOW)
    burst(20, 16, RED, r=10)
    burst(50, 8, WHITE, r=6)
    burst(78, 18, RED, r=8)
    burst(108, 10, WHITE, r=8)
    burst(132, 22, RED, r=6)
    # Two palm silhouettes
    compose_palm_tree(sp, 12, 60, trunk_h=24, frond_r=8)
    compose_palm_tree(sp, 134, 60, trunk_h=24, frond_r=8)
    # Johnny center, sparklers
    compose_johnny_simple(sp, 70, 60, hat_color=RED, shirt_color=WHITE)
    sp.line(68, 50, 60, 42, GRAY)
    sp.px(58, 40, YELLOW); sp.px(56, 38, WHITE); sp.px(60, 38, RED)
    sp.line(76, 50, 84, 42, GRAY)
    sp.px(86, 40, YELLOW); sp.px(88, 38, WHITE); sp.px(84, 38, RED)
    # Multiple tiny flags in sand
    for fx0 in [34, 100, 120]:
        sp.line(fx0, 60, fx0, 72, TRUNK)
        sp.rect(fx0 + 1, 60, fx0 + 9, 65, WHITE, outline=BLACK)
        for sy in range(61, 65, 2):
            sp.line(fx0 + 1, sy, fx0 + 9, sy, RED)
        sp.rect(fx0 + 1, 60, fx0 + 4, 62, DEEPBLUE)
    # Sand text scrawl: USA dot trail
    for x, y in [(40, 76), (44, 76), (48, 76), (54, 75), (58, 76), (62, 75)]:
        sp.px(x, y, RED)
    return sp


# ---------------------------------------------------------------------------
# id 25: Moon Landing Day  (128×80, palette: night/gray/white)
# Concept: Tiny astronaut figure with American flag planted in the sand;
# oversized full moon hanging behind the palm.
# ---------------------------------------------------------------------------

def moonland_v1(h):
    sp = Sprite(128, 80, fill=DEEPBLUE)
    compose_sand_strip(sp, 56)
    compose_horizon(sp, 56)
    # Oversized full moon — left of center
    moon_cx, moon_cy = 44, 28
    sp.ellipse(moon_cx - 18, moon_cy - 18, moon_cx + 18, moon_cy + 18,
               WHITE, outline=GRAY)
    # Crater detail
    sp.ellipse(moon_cx - 8, moon_cy - 6, moon_cx - 4, moon_cy - 2, GRAY)
    sp.ellipse(moon_cx + 4, moon_cy + 2, moon_cx + 10, moon_cy + 8, GRAY)
    sp.px(moon_cx - 2, moon_cy + 6, GRAY)
    sp.px(moon_cx + 12, moon_cy - 8, GRAY)
    # Palm in front of moon (right side of moon)
    compose_palm_tree(sp, 64, 56, trunk_h=30, frond_r=10)
    # Stars in night sky
    for x, y in [(8, 6), (88, 4), (104, 10), (120, 6), (110, 22),
                 (96, 16), (16, 18), (76, 8)]:
        sp.px(x, y, WHITE)
    # Astronaut on right — tiny figure with helmet
    ax, ay = 96, 56
    # Body
    sp.rect(ax - 3, ay - 8, ax + 3, ay - 2, WHITE, outline=BLACK)
    # Helmet (round)
    sp.ellipse(ax - 4, ay - 14, ax + 4, ay - 6, WHITE, outline=BLACK)
    # Visor (dark)
    sp.rect(ax - 3, ay - 12, ax + 3, ay - 9, BLACK)
    sp.px(ax + 1, ay - 11, WHITE)  # reflection highlight
    # Backpack
    sp.rect(ax + 3, ay - 7, ax + 5, ay - 3, GRAY, outline=BLACK)
    # Legs
    sp.rect(ax - 3, ay - 1, ax - 1, ay + 2, WHITE)
    sp.rect(ax + 1, ay - 1, ax + 3, ay + 2, WHITE)
    # Flag planted by astronaut
    fp = ax - 12
    sp.line(fp, ay - 14, fp, ay, GRAY)
    sp.rect(fp + 1, ay - 14, fp + 10, ay - 8, WHITE, outline=BLACK)
    for sy in range(ay - 13, ay - 8, 2):
        sp.line(fp + 1, sy, fp + 10, sy, RED)
    sp.rect(fp + 1, ay - 14, fp + 5, ay - 11, DEEPBLUE)
    return sp


def moonland_v2(h):
    """Minimalist — single huge moon with one footprint."""
    sp = Sprite(128, 80, fill=DEEPBLUE)
    compose_sand_strip(sp, 70)
    # Massive moon
    moon_cx, moon_cy = 64, 36
    sp.ellipse(moon_cx - 30, moon_cy - 30, moon_cx + 30, moon_cy + 30,
               WHITE, outline=GRAY)
    # Several craters
    sp.ellipse(moon_cx - 14, moon_cy - 10, moon_cx - 6, moon_cy - 2, GRAY)
    sp.ellipse(moon_cx + 6, moon_cy + 4, moon_cx + 16, moon_cy + 14, GRAY)
    sp.ellipse(moon_cx - 18, moon_cy + 10, moon_cx - 12, moon_cy + 16, GRAY)
    sp.px(moon_cx + 18, moon_cy - 18, GRAY)
    sp.px(moon_cx - 24, moon_cy - 4, GRAY)
    sp.px(moon_cx + 22, moon_cy + 22, GRAY)
    # Footprint in sand
    sp.ellipse(58, 74, 66, 78, BLACK)
    sp.px(60, 73, BLACK); sp.px(62, 72, BLACK); sp.px(64, 73, BLACK)
    return sp


def moonland_v3(h):
    """Busy — full astronaut beach scene with moon, palms, stars, flag, footprints."""
    sp = Sprite(128, 80, fill=DEEPBLUE)
    compose_sand_strip(sp, 56)
    compose_horizon(sp, 56)
    sp.rect(0, 54, 127, 56, BLACK)
    # Stars
    star_pts = [(8, 4), (20, 10), (32, 4), (88, 6), (100, 12), (114, 4),
                (124, 10), (16, 22), (104, 26), (118, 18), (76, 4), (94, 18)]
    for x, y in star_pts:
        sp.px(x, y, WHITE)
    # Moon left
    mx, my = 32, 22
    sp.ellipse(mx - 16, my - 16, mx + 16, my + 16, WHITE, outline=GRAY)
    sp.ellipse(mx - 6, my - 4, mx - 2, my, GRAY)
    sp.ellipse(mx + 2, my + 4, mx + 8, my + 10, GRAY)
    sp.px(mx + 8, my - 10, GRAY)
    # Two palms
    compose_palm_tree(sp, 60, 56, trunk_h=28, frond_r=10)
    compose_palm_tree(sp, 120, 56, trunk_h=24, frond_r=8)
    # Astronaut center-right
    ax, ay = 88, 60
    sp.rect(ax - 3, ay - 10, ax + 3, ay - 4, WHITE, outline=BLACK)
    sp.ellipse(ax - 4, ay - 16, ax + 4, ay - 8, WHITE, outline=BLACK)
    sp.rect(ax - 3, ay - 14, ax + 3, ay - 11, BLACK)
    sp.px(ax + 1, ay - 13, WHITE)
    sp.rect(ax + 3, ay - 9, ax + 5, ay - 5, GRAY, outline=BLACK)
    sp.rect(ax - 3, ay - 3, ax - 1, ay, WHITE)
    sp.rect(ax + 1, ay - 3, ax + 3, ay, WHITE)
    # Flag planted next to astronaut
    fp = ax - 14
    sp.line(fp, ay - 18, fp, ay, GRAY)
    sp.rect(fp + 1, ay - 18, fp + 10, ay - 11, WHITE, outline=BLACK)
    for sy in range(ay - 17, ay - 11, 2):
        sp.line(fp + 1, sy, fp + 10, sy, RED)
    sp.rect(fp + 1, ay - 18, fp + 5, ay - 14, DEEPBLUE)
    sp.px(fp + 2, ay - 16, WHITE); sp.px(fp + 4, ay - 16, WHITE)
    # Footprints in sand trailing left
    for fx in [62, 70, 78]:
        sp.ellipse(fx, 70, fx + 4, 72, BLACK)
        sp.ellipse(fx + 1, 74, fx + 5, 76, BLACK)
    # Lunar lander silhouette in background?  small triangle shape on sand right
    sp.line(108, 64, 112, 58, GRAY)
    sp.line(112, 58, 116, 64, GRAY)
    sp.line(108, 64, 116, 64, GRAY)
    sp.px(112, 60, WHITE)
    return sp


# ---------------------------------------------------------------------------
# id 26: National Watermelon Day  (56×48, palette: green/red/white)
# Concept: Giant watermelon slice prop on the sand, Johnny taking a bite,
# seeds scattered.
# ---------------------------------------------------------------------------

def watermelon_v1(h):
    sp = Sprite(56, 48, fill=SKY)
    compose_sand_strip(sp, 32)
    compose_horizon(sp, 32)
    # Giant watermelon slice — semicircle, dome-down
    # Outer rind (dark green)
    sp.ellipse(4, 16, 40, 44, DGREEN, outline=BLACK)
    # Inner rind (light green)
    sp.ellipse(6, 18, 38, 42, GREEN)
    # Pink/red flesh
    sp.ellipse(8, 20, 36, 40, RED)
    # Mask out bottom half so it's a slice (cut-flat top)
    sp.rect(0, 16, 55, 28, SKY)
    compose_sand_strip(sp, 32)
    # Now redraw the bottom dome
    sp.ellipse(4, 22, 40, 44, DGREEN, outline=BLACK)
    sp.ellipse(6, 24, 38, 42, GREEN)
    sp.ellipse(8, 26, 36, 40, RED)
    # Flat top of the slice
    sp.line(4, 32, 40, 32, BLACK)
    sp.rect(4, 28, 40, 32, RED, outline=BLACK)
    # Seeds on flesh
    for sx, sy in [(14, 30), (20, 34), (26, 30), (32, 34),
                   (16, 38), (24, 40), (30, 38)]:
        sp.px(sx, sy, BLACK)
        sp.px(sx + 1, sy, BLACK)
    # Bite out of the slice (top edge)
    sp.ellipse(18, 26, 26, 32, SKY)
    # Johnny on the right, taking a bite
    compose_johnny_simple(sp, 44, 44, hat_color=GREEN, shirt_color=RED)
    # His head is biting toward the slice — small pink bite chunk near mouth
    sp.px(43, 35, RED); sp.px(42, 35, RED)
    # Scattered seeds in sand
    for x, y in [(6, 46), (44, 46), (28, 47), (50, 45)]:
        sp.px(x, y, BLACK)
    return sp


def watermelon_v2(h):
    """Minimalist — one big watermelon slice icon centered."""
    sp = Sprite(56, 48, fill=SKY)
    compose_sand_strip(sp, 40)
    # Big slice — semicircle pointing up (triangular slice shape)
    cx = 28
    # Rind arc
    sp.ellipse(cx - 22, 6, cx + 22, 40, DGREEN, outline=BLACK)
    sp.ellipse(cx - 20, 8, cx + 20, 38, GREEN)
    sp.ellipse(cx - 17, 11, cx + 17, 35, RED)
    # Cut the top half off to make a slice (flat bottom)
    sp.rect(0, 24, 55, 47, SAND)
    # Now redraw the top half as a dome
    sp.ellipse(cx - 22, 6, cx + 22, 28, DGREEN, outline=BLACK)
    sp.ellipse(cx - 20, 8, cx + 20, 26, GREEN)
    sp.ellipse(cx - 17, 11, cx + 17, 24, RED)
    # Flat bottom edge
    sp.line(cx - 22, 24, cx + 22, 24, BLACK)
    # Seeds
    for sx, sy in [(cx - 10, 16), (cx - 4, 20), (cx + 4, 18),
                   (cx + 10, 14), (cx, 14), (cx - 8, 22), (cx + 8, 22)]:
        sp.px(sx, sy, BLACK); sp.px(sx + 1, sy, BLACK)
    return sp


def watermelon_v3(h):
    """Busy — multiple slices, Johnny eating, palm, sand seed trail."""
    sp = Sprite(56, 48, fill=SKY)
    compose_sand_strip(sp, 30)
    compose_horizon(sp, 30)
    # Palm tree on the left
    compose_palm_tree(sp, 6, 30, trunk_h=14, frond_r=6)
    # Big slice on the sand (left-center)
    cx = 22
    sp.ellipse(cx - 12, 24, cx + 12, 42, DGREEN, outline=BLACK)
    sp.ellipse(cx - 10, 26, cx + 10, 40, GREEN)
    sp.ellipse(cx - 8, 28, cx + 8, 38, RED)
    sp.line(cx - 12, 30, cx + 12, 30, BLACK)
    sp.rect(cx - 12, 24, cx + 12, 30, RED, outline=BLACK)
    # Bite mark
    sp.ellipse(cx - 4, 24, cx + 4, 30, SKY)
    # Seeds inside slice
    for sx, sy in [(cx - 7, 32), (cx - 2, 34), (cx + 4, 33), (cx + 7, 36)]:
        sp.px(sx, sy, BLACK); sp.px(sx + 1, sy, BLACK)
    # Smaller slice on the right
    cx2 = 44
    sp.ellipse(cx2 - 6, 32, cx2 + 6, 42, DGREEN, outline=BLACK)
    sp.ellipse(cx2 - 5, 33, cx2 + 5, 41, GREEN)
    sp.ellipse(cx2 - 4, 34, cx2 + 4, 40, RED)
    sp.line(cx2 - 6, 36, cx2 + 6, 36, BLACK)
    sp.rect(cx2 - 6, 32, cx2 + 6, 36, RED, outline=BLACK)
    sp.px(cx2 - 2, 38, BLACK); sp.px(cx2 + 2, 38, BLACK)
    # Johnny center, eating
    compose_johnny_simple(sp, 32, 44, hat_color=GREEN, shirt_color=RED)
    sp.px(31, 35, RED); sp.px(30, 35, RED)
    # Seed trail across sand
    for x in [10, 16, 38, 50]:
        sp.px(x, 47, BLACK)
        sp.px(x + 1, 46, BLACK)
    # Tiny watermelon-rind crescent floating top
    sp.ellipse(40, 4, 50, 10, GREEN, outline=BLACK)
    sp.ellipse(41, 6, 49, 11, RED)
    return sp


# ---------------------------------------------------------------------------
# v4 PLAYFUL variants — exaggerated, comedic, character-forward
# ---------------------------------------------------------------------------

def memorial_v4(h):
    """PLAYFUL — Johnny saluting SO HARD his hat flies off, single comedic
    tear, oversized glistening flag, exaggerated reverence."""
    sp = Sprite(56, 80, fill=SKY)
    compose_sand_strip(sp, 56)
    compose_horizon(sp, 56)
    # Driftwood pole, slightly leaning from wind
    pole_x = 14
    sp.line(pole_x,     6, pole_x + 1,     56, TRUNK)
    sp.line(pole_x + 1, 6, pole_x + 2, 56, TRUNK)
    sp.px(pole_x, 5, YELLOW); sp.px(pole_x + 1, 5, YELLOW)
    # Flag dramatically flapping with squiggly edge
    fx, fy = pole_x + 2, 24
    sp.rect(fx, fy, fx + 22, fy + 14, WHITE, outline=BLACK)
    for sy in range(fy + 1, fy + 14, 2):
        sp.line(fx + 1, sy, fx + 21, sy, RED)
    sp.rect(fx + 1, fy + 1, fx + 9, fy + 6, DEEPBLUE)
    # Stars on canton (tiny sparkles)
    for sx, sy in [(fx + 2, fy + 2), (fx + 5, fy + 2), (fx + 8, fy + 2),
                   (fx + 3, fy + 4), (fx + 6, fy + 4)]:
        sp.px(sx, sy, WHITE)
    # Wavy flag end
    for y in (fy + 2, fy + 6, fy + 10):
        sp.px(fx + 23, y, WHITE)
        sp.px(fx + 24, y + 1, WHITE)
    # Wind motion lines
    sp.line(fx + 26, fy + 4, fx + 30, fy + 4, BLACK)
    sp.line(fx + 26, fy + 8, fx + 30, fy + 8, BLACK)
    # Glistening sparkle on flag
    compose_star(sp, fx + 12, fy + 7, 1, YELLOW)
    # Johnny saluting OVER-EARNESTLY on right
    jx = 36
    base_y = 56
    # Body
    sp.rect(jx, base_y - 8, jx + 5, base_y - 4, DEEPBLUE)
    # Legs at attention
    sp.rect(jx + 1, base_y - 3, jx + 2, base_y, TRUNK)
    sp.rect(jx + 3, base_y - 3, jx + 4, base_y, TRUNK)
    # Head — eyes shut tight in respect
    sp.rect(jx + 1, base_y - 11, jx + 4, base_y - 9, SKIN)
    sp.line(jx + 1, base_y - 10, jx + 2, base_y - 10, BLACK)
    sp.line(jx + 3, base_y - 10, jx + 4, base_y - 10, BLACK)
    # Single giant tear
    sp.px(jx, base_y - 9, SKY)
    sp.px(jx, base_y - 8, SKY)
    sp.px(jx - 1, base_y - 8, SKY)
    # Hat flying off above (motion arc)
    sp.rect(jx, base_y - 18, jx + 5, base_y - 17, DEEPBLUE)
    sp.line(jx + 1, base_y - 19, jx + 4, base_y - 19, DEEPBLUE)
    # Motion arc dots
    sp.px(jx + 5, base_y - 16, BLACK)
    sp.px(jx + 4, base_y - 15, BLACK)
    sp.px(jx + 3, base_y - 14, BLACK)
    # Salute arm — RIGID and overdrawn
    sp.line(jx + 5, base_y - 7, jx + 9, base_y - 11, SKIN)
    sp.px(jx + 9, base_y - 12, SKIN)
    # Arm motion line (saluting hard)
    sp.line(jx + 6, base_y - 9, jx + 11, base_y - 13, BLACK)
    # Crosses with TINY motion lines (placed reverently)
    for cx in [4, 24, 48]:
        cy = 64
        sp.line(cx, cy, cx, cy + 6, WHITE)
        sp.line(cx - 2, cy + 2, cx + 2, cy + 2, WHITE)
    # Floating poppies with sparkle
    for x, y in [(8, 70), (28, 72), (44, 70)]:
        sp.px(x, y, RED); sp.px(x + 1, y, RED)
        sp.px(x, y - 1, BLACK)
    return sp


def fathersday_v4(h):
    """PLAYFUL — Grill ON FIRE, smoke clouds, Johnny panicking with comically
    burnt apron, burger flying through air, dad-tie askew."""
    sp = Sprite(80, 56, fill=SKY)
    compose_sand_strip(sp, 38)
    compose_horizon(sp, 38)
    compose_palm_tree(sp, 70, 38, trunk_h=20, frond_r=8)
    # GIANT flames erupting from grill
    for x, y in [(34, 6), (38, 4), (42, 2), (46, 4), (50, 6),
                 (32, 12), (40, 8), (48, 12)]:
        sp.ellipse(x - 2, y, x + 2, y + 6, ORANGE, outline=RED)
        sp.ellipse(x - 1, y + 1, x + 1, y + 4, YELLOW)
    # Smoke clouds rising
    for cx, cy in [(28, 16), (54, 18), (44, 14)]:
        sp.ellipse(cx - 3, cy, cx + 3, cy + 4, GRAY, outline=BLACK)
        sp.px(cx, cy + 5, GRAY)
    # Grill (charred black overlay)
    sp.rect(30, 26, 50, 36, BLACK, outline=BLACK)
    sp.rect(31, 27, 49, 35, TRUNK)
    for sy in range(28, 34, 2):
        sp.line(32, sy, 48, sy, BLACK)
    sp.line(32, 36, 32, 44, BLACK)
    sp.line(48, 36, 48, 44, BLACK)
    # Burger LAUNCHED into the air with motion arc
    sp.ellipse(54, 16, 60, 19, TRUNK, outline=BLACK)
    sp.line(55, 17, 59, 17, ORANGE)  # cheese
    # Motion arc trail (curve dots)
    for x, y in [(50, 18), (47, 20), (44, 24)]:
        sp.px(x, y, WHITE); sp.px(x + 1, y, WHITE)
    # Speed lines behind burger
    sp.line(48, 14, 53, 16, BLACK)
    sp.line(50, 12, 53, 14, BLACK)
    # Johnny on left PANICKING
    jx = 12
    base_y = 44
    # Body
    sp.rect(jx, base_y - 8, jx + 5, base_y - 4, ORANGE)
    sp.rect(jx + 1, base_y - 3, jx + 2, base_y, TRUNK)
    sp.rect(jx + 3, base_y - 3, jx + 4, base_y, TRUNK)
    # Burnt apron (gray streaks)
    sp.px(jx, base_y - 7, BLACK); sp.px(jx + 5, base_y - 6, BLACK)
    sp.px(jx + 2, base_y - 5, BLACK)
    # Head — wide alarmed eyes
    sp.rect(jx + 1, base_y - 11, jx + 4, base_y - 9, SKIN)
    sp.ellipse(jx + 1, base_y - 11, jx + 2, base_y - 10, WHITE)
    sp.ellipse(jx + 3, base_y - 11, jx + 4, base_y - 10, WHITE)
    sp.px(jx + 1, base_y - 10, BLACK); sp.px(jx + 4, base_y - 10, BLACK)
    # Wide open mouth screaming
    sp.ellipse(jx + 1, base_y - 9, jx + 4, base_y - 8, BLACK)
    # Soot smudge on cheek
    sp.px(jx, base_y - 10, BLACK)
    # Hair sticking up from shock
    sp.px(jx + 1, base_y - 12, BLACK); sp.px(jx + 4, base_y - 12, BLACK)
    sp.px(jx + 2, base_y - 13, BLACK); sp.px(jx + 3, base_y - 13, BLACK)
    # Arms flailing with motion lines
    sp.line(jx, base_y - 6, jx - 4, base_y - 8, SKIN)
    sp.line(jx + 5, base_y - 6, jx + 9, base_y - 4, SKIN)
    # Motion squiggles around arms
    sp.line(jx - 6, base_y - 10, jx - 5, base_y - 8, BLACK)
    sp.line(jx - 6, base_y - 6, jx - 4, base_y - 6, BLACK)
    sp.line(jx + 11, base_y - 6, jx + 12, base_y - 4, BLACK)
    # Tie askew on apron
    sp.line(jx + 2, base_y - 4, jx, base_y - 2, ORANGE)
    sp.rect(jx - 1, base_y - 2, jx + 1, base_y, ORANGE)
    # Spatula thrown aside
    sp.line(56, 30, 62, 28, GRAY)
    sp.rect(61, 26, 64, 28, GRAY, outline=BLACK)
    sp.line(56, 30, 58, 32, BLACK)  # falling motion
    # Speech bubble "OH NO!"
    sp.ellipse(20, 4, 40, 16, WHITE, outline=BLACK)
    sp.text(22, 6, "!?!", BLACK)
    sp.line(22, 14, 18, 18, BLACK)  # tail
    return sp


def summer_v4(h):
    """PLAYFUL — Johnny MELTING in heat, sun has comedic face, thermometer
    EXPLODING with cartoon mercury squirt, hammock literally on fire."""
    sp = Sprite(112, 96, fill=SKY)
    compose_sand_strip(sp, 70)
    compose_horizon(sp, 70)
    # Cartoon sun with face
    sun_cx, sun_cy = 56, 18
    sp.ellipse(sun_cx - 14, sun_cy - 14, sun_cx + 14, sun_cy + 14,
               YELLOW, outline=ORANGE)
    # Sun tongue out, sweating
    sp.ellipse(sun_cx - 6, sun_cy - 4, sun_cx - 3, sun_cy - 1, WHITE, outline=BLACK)
    sp.ellipse(sun_cx + 3, sun_cy - 4, sun_cx + 6, sun_cy - 1, WHITE, outline=BLACK)
    sp.px(sun_cx - 4, sun_cy - 2, BLACK); sp.px(sun_cx + 4, sun_cy - 2, BLACK)
    # Tongue
    sp.ellipse(sun_cx - 3, sun_cy + 4, sun_cx + 3, sun_cy + 9, RED, outline=BLACK)
    # Sun's own sweat drops
    sp.px(sun_cx - 12, sun_cy + 4, SKY); sp.px(sun_cx - 13, sun_cy + 6, SKY)
    sp.px(sun_cx + 12, sun_cy + 4, SKY); sp.px(sun_cx + 13, sun_cy + 6, SKY)
    # WAVY sun rays (heat distortion)
    for dx, dy in [(-22, 0), (22, 0), (0, -20), (-16, -16), (16, -16)]:
        sp.line(sun_cx, sun_cy, sun_cx + dx, sun_cy + dy, YELLOW)
        # extra wiggle
        sp.px(sun_cx + dx // 2 + 1, sun_cy + dy // 2, YELLOW)
    # Heat ripples everywhere
    for y in [40, 50, 60]:
        for x in range(20, 100, 8):
            sp.line(x, y, x + 4, y - 1, ORANGE)
            sp.line(x + 4, y - 1, x + 8, y, ORANGE)
    # Two palms with DROOPING fronds (wilted)
    sp.line(14, 70, 14, 36, TRUNK)
    sp.line(15, 70, 15, 36, TRUNK)
    for dx, dy in [(-8, 8), (-4, 10), (0, 12), (4, 10), (8, 8)]:
        sp.line(14, 36, 14 + dx, 36 + dy, GREEN)  # drooping down
    sp.line(98, 70, 98, 36, TRUNK)
    sp.line(99, 70, 99, 36, TRUNK)
    for dx, dy in [(-8, 8), (-4, 10), (0, 12), (4, 10), (8, 8)]:
        sp.line(98, 36, 98 + dx, 36 + dy, GREEN)
    # Hammock with literal flames
    hy = 56
    sp.line(16, hy - 2, 96, hy + 2, TRUNK)
    sp.line(16, hy + 4, 96, hy + 10, TRUNK)
    for x in range(20, 94):
        t = (x - 56) / 38
        ys = int(hy + 4 + (1 - t * t) * 6)
        sp.line(x, hy + 1, x, ys, ORANGE)
    # Flames popping up from hammock
    for x, y in [(30, 50), (50, 48), (70, 50), (84, 52)]:
        sp.ellipse(x - 2, y - 4, x + 2, y, ORANGE, outline=RED)
        sp.ellipse(x - 1, y - 3, x + 1, y - 1, YELLOW)
    # Johnny MELTING — body droopy
    sp.ellipse(46, 56, 66, 64, RED)  # body sagging
    sp.ellipse(48, 52, 56, 60, SKIN, outline=BLACK)
    # Eyes wide with despair
    sp.ellipse(50, 54, 51, 56, WHITE)
    sp.ellipse(53, 54, 54, 56, WHITE)
    sp.px(50, 55, BLACK); sp.px(53, 55, BLACK)
    # Mouth — squiggly distress
    sp.line(49, 58, 51, 57, BLACK)
    sp.line(51, 57, 53, 58, BLACK)
    sp.line(53, 58, 55, 57, BLACK)
    # Sweat raining off Johnny
    for x, y in [(44, 54), (42, 58), (58, 54), (60, 58), (52, 64), (46, 66)]:
        sp.px(x, y, SKY); sp.px(x, y + 1, SKY)
    # Thermometer EXPLODING
    tx = 102
    sp.rect(tx, 38, tx + 4, 78, WHITE, outline=BLACK)
    sp.rect(tx + 1, 40, tx + 3, 76, RED)
    sp.ellipse(tx - 1, 76, tx + 5, 82, RED, outline=BLACK)
    # Mercury SQUIRTING out top in cartoon spray
    for dx, dy in [(-4, -8), (-2, -12), (1, -14), (4, -12), (7, -10),
                   (-6, -6), (8, -6), (-3, -16), (3, -16)]:
        sp.px(tx + 2 + dx, 38 + dy, RED)
        sp.px(tx + 2 + dx + 1, 38 + dy, RED)
    # Cracks in glass
    sp.line(tx, 50, tx + 4, 54, BLACK)
    sp.line(tx + 1, 60, tx + 3, 64, BLACK)
    # Big "ZZZZ" with X-ed out Z (passed out, not sleeping)
    sp.text(72, 38, "X_X", BLACK)
    # Speech bubble "HOT!"
    sp.ellipse(20, 36, 40, 50, WHITE, outline=BLACK)
    sp.text(22, 39, "HOT", BLACK)
    return sp


def pride_v4(h):
    """PLAYFUL — Johnny dancing in rainbow tutu, multiple flags swirling,
    hearts everywhere, comically jubilant, motion arcs."""
    sp = Sprite(112, 64, fill=SKY)
    compose_sand_strip(sp, 48)
    compose_horizon(sp, 48)
    # Bunting EVERYWHERE in zigzag layers
    for layer, by in [(0, 2), (1, 8)]:
        for i, x in enumerate(range(2, 112, 6)):
            c = _PRIDE_STRIPES[(i + layer) % 6]
            yoff = -1 if i % 2 == 0 else 1
            sp.line(x, by + yoff, x + 3, by + 4, c)
            sp.line(x + 3, by + 4, x + 6, by + yoff, c)
    # Johnny center, mid-twirl, in rainbow tutu
    jx = 56
    base_y = 56
    # Body
    sp.rect(jx, base_y - 8, jx + 5, base_y - 4, RED)
    # Tutu (rainbow stripe ring around hips)
    for i, c in enumerate(_PRIDE_STRIPES):
        sp.line(jx - 3 + i, base_y - 2, jx + 8 - i, base_y - 2, c)
    sp.outline_rect(jx - 4, base_y - 4, jx + 9, base_y - 2, BLACK)
    # Spinning legs with motion ghost
    sp.rect(jx + 1, base_y - 1, jx + 2, base_y + 2, TRUNK)
    sp.rect(jx + 3, base_y - 1, jx + 4, base_y + 2, TRUNK)
    sp.line(jx - 2, base_y, jx, base_y, BLACK)  # spin trail
    sp.line(jx + 5, base_y, jx + 7, base_y, BLACK)
    # Head — beaming smile
    sp.rect(jx + 1, base_y - 11, jx + 4, base_y - 9, SKIN)
    sp.px(jx + 1, base_y - 10, BLACK); sp.px(jx + 4, base_y - 10, BLACK)
    # Big grin
    sp.line(jx + 1, base_y - 9, jx + 4, base_y - 9, BLACK)
    # Arms thrown UP with flags
    sp.line(jx, base_y - 7, jx - 8, base_y - 16, SKIN)
    sp.line(jx + 5, base_y - 7, jx + 13, base_y - 16, SKIN)
    # Tiny flags in each hand
    for fx in [jx - 12, jx + 13]:
        for i, c in enumerate(_PRIDE_STRIPES):
            sp.line(fx, base_y - 22 + i, fx + 4, base_y - 22 + i, c)
        sp.line(fx + 5, base_y - 22, fx + 5, base_y - 16, TRUNK)
    # Massive rainbow flag streaming behind palm
    compose_palm_tree(sp, 16, 48, trunk_h=34, frond_r=10)
    fx, fy, fw, fh = 18, 10, 26, 16
    stripe_h = fh // 6
    for i, c in enumerate(_PRIDE_STRIPES):
        sp.rect(fx, fy + i * stripe_h, fx + fw, fy + (i + 1) * stripe_h - 1, c)
    sp.outline_rect(fx, fy, fx + fw, fy + fh, BLACK)
    # Wavy flag end
    for y in (fy + 2, fy + 6, fy + 10, fy + 14):
        sp.px(fx + fw + 1, y, _PRIDE_STRIPES[(y - fy) // stripe_h % 6])
        sp.px(fx + fw + 2, y + 1, _PRIDE_STRIPES[(y - fy) // stripe_h % 6])
    # Hearts BURSTING all around
    for cx, cy, c in [(38, 18, PINK), (74, 14, RED), (88, 22, PINK),
                      (96, 32, RED), (50, 36, PINK), (4, 24, RED)]:
        compose_heart(sp, cx, cy, 2, c)
    # Sparkle stars
    compose_star(sp, 100, 12, 2, YELLOW)
    compose_star(sp, 70, 30, 2, YELLOW)
    # Confetti rainbow shower
    for x, y, c in [(28, 30, RED), (60, 28, ORANGE), (84, 30, YELLOW),
                    (104, 28, GREEN), (32, 40, SKY), (96, 40, PURPLE)]:
        sp.px(x, y, c); sp.px(x + 1, y, c)
        sp.px(x, y + 1, c)
    # "YAY!" speech bubble
    sp.ellipse(76, 38, 100, 50, WHITE, outline=BLACK)
    sp.text(80, 41, "YAY", BLACK)
    return sp


def july4th_v4(h):
    """PLAYFUL — Johnny lit the giant firework wrong and is fleeing; sparks
    chase him, flag salutes itself, comically smoking dud, fireworks make faces."""
    sp = Sprite(144, 80, fill=DEEPBLUE)
    compose_sand_strip(sp, 60)
    sp.rect(0, 56, 143, 60, DEEPBLUE)
    sp.line(0, 56, 143, 56, BLACK)
    # Stars in night sky
    for x, y in [(8, 4), (24, 10), (42, 4), (60, 8), (76, 4), (92, 10),
                 (108, 4), (126, 8), (140, 4)]:
        sp.px(x, y, WHITE)
    # Firework with comedic FACE
    cx, cy = 32, 22
    for dx, dy in [(-12, 0), (12, 0), (0, -10), (0, 10),
                   (-9, -9), (9, -9), (-9, 9), (9, 9)]:
        sp.line(cx, cy, cx + dx, cy + dy, RED)
    sp.ellipse(cx - 6, cy - 6, cx + 6, cy + 6, YELLOW, outline=WHITE)
    # Face on firework
    sp.px(cx - 3, cy - 2, BLACK); sp.px(cx + 3, cy - 2, BLACK)
    sp.line(cx - 2, cy + 2, cx + 2, cy + 2, BLACK)
    # Second firework
    cx2, cy2 = 96, 16
    for dx, dy in [(-10, 0), (10, 0), (0, -8), (0, 8),
                   (-7, -7), (7, -7), (-7, 7), (7, 7)]:
        sp.line(cx2, cy2, cx2 + dx, cy2 + dy, WHITE)
    sp.ellipse(cx2 - 4, cy2 - 4, cx2 + 4, cy2 + 4, YELLOW)
    sp.px(cx2 - 2, cy2 - 1, BLACK); sp.px(cx2 + 2, cy2 - 1, BLACK)
    sp.ellipse(cx2 - 1, cy2 + 1, cx2 + 1, cy2 + 2, BLACK)  # surprised mouth
    # SMOKING DUD on the sand (cartoonish)
    dx_d = 70
    sp.rect(dx_d, 64, dx_d + 8, 72, RED, outline=BLACK)
    sp.rect(dx_d + 2, 60, dx_d + 6, 64, GRAY, outline=BLACK)
    # Smoke wisps
    for ox, oy in [(0, 56), (3, 52), (-2, 50), (5, 48), (1, 44)]:
        sp.ellipse(dx_d + 4 + ox - 2, oy, dx_d + 4 + ox + 2, oy + 3, GRAY,
                   outline=BLACK)
    # Lit fuse with sparks
    sp.line(dx_d + 4, 60, dx_d + 8, 56, BLACK)
    sp.px(dx_d + 9, 55, YELLOW); sp.px(dx_d + 10, 56, ORANGE)
    sp.px(dx_d + 11, 54, YELLOW); sp.px(dx_d + 12, 55, RED)
    # Johnny fleeing right with motion blur
    jx = 100
    base_y = 76
    # Body slanted forward (running)
    sp.rect(jx, base_y - 8, jx + 5, base_y - 4, WHITE)
    # Legs splayed (running)
    sp.line(jx + 1, base_y - 4, jx - 1, base_y, TRUNK)
    sp.line(jx + 4, base_y - 4, jx + 6, base_y, TRUNK)
    # Head looking BACK (eyes on left side)
    sp.rect(jx + 1, base_y - 11, jx + 4, base_y - 9, SKIN)
    sp.px(jx + 1, base_y - 10, WHITE)
    sp.px(jx + 1, base_y - 10, BLACK)
    sp.px(jx + 2, base_y - 10, BLACK)
    # Hat flying off
    sp.rect(jx - 3, base_y - 16, jx + 2, base_y - 15, RED)
    sp.line(jx - 2, base_y - 17, jx + 1, base_y - 17, RED)
    # Wide-open mouth
    sp.ellipse(jx + 1, base_y - 9, jx + 4, base_y - 8, BLACK)
    # Arms flailing
    sp.line(jx, base_y - 7, jx - 4, base_y - 5, SKIN)
    sp.line(jx + 5, base_y - 7, jx + 9, base_y - 9, SKIN)
    # Speed lines behind Johnny
    for y in (base_y - 9, base_y - 5, base_y - 1):
        sp.line(jx - 6, y, jx - 12, y, BLACK)
        sp.line(jx - 8, y - 2, jx - 14, y - 2, BLACK)
    # Sparks chasing
    for x, y in [(86, 70), (90, 68), (84, 74), (80, 72)]:
        sp.px(x, y, YELLOW); sp.px(x + 1, y, RED)
    # Flag SALUTING itself (animated, with little arm)
    pole_x = 130
    sp.line(pole_x, 60, pole_x, 76, TRUNK)
    sp.rect(pole_x + 1, 60, pole_x + 12, 68, WHITE, outline=BLACK)
    for sy in range(61, 68, 2):
        sp.line(pole_x + 1, sy, pole_x + 12, sy, RED)
    sp.rect(pole_x + 1, 60, pole_x + 6, 64, DEEPBLUE)
    sp.px(pole_x + 3, 62, WHITE); pole_y = 62
    # Tiny arm coming off flag, saluting
    sp.line(pole_x + 13, 64, pole_x + 16, 60, SKIN)
    # Eyes on flag
    sp.px(pole_x + 8, 62, BLACK); sp.px(pole_x + 10, 62, BLACK)
    # Speech bubble from Johnny "AAH!"
    sp.ellipse(108, 36, 138, 50, WHITE, outline=BLACK)
    sp.text(112, 39, "AH!", BLACK)
    sp.line(110, 50, 106, 56, BLACK)
    return sp


def moonland_v4(h):
    """PLAYFUL — Tiny astronaut faceplanted in sand, legs kicking;
    moon has a face (waving); palm gawking; sparkle stars."""
    sp = Sprite(128, 80, fill=DEEPBLUE)
    compose_sand_strip(sp, 56)
    compose_horizon(sp, 56)
    # Cartoon moon with face WAVING
    moon_cx, moon_cy = 44, 28
    sp.ellipse(moon_cx - 18, moon_cy - 18, moon_cx + 18, moon_cy + 18,
               WHITE, outline=GRAY)
    # Crater detail
    sp.ellipse(moon_cx - 10, moon_cy - 8, moon_cx - 4, moon_cy - 2, GRAY)
    sp.ellipse(moon_cx + 4, moon_cy + 6, moon_cx + 10, moon_cy + 12, GRAY)
    # Face: smile and one open eye one wink
    sp.ellipse(moon_cx + 4, moon_cy - 6, moon_cx + 7, moon_cy - 3, BLACK)
    sp.line(moon_cx - 6, moon_cy - 4, moon_cx - 2, moon_cy - 4, BLACK)  # winking
    # Big curved smile
    sp.line(moon_cx - 5, moon_cy + 2, moon_cx + 5, moon_cy + 2, BLACK)
    sp.line(moon_cx - 4, moon_cy + 3, moon_cx + 4, moon_cy + 3, BLACK)
    # Tiny waving "arm" coming off moon
    sp.line(moon_cx + 18, moon_cy, moon_cx + 22, moon_cy - 4, GRAY)
    sp.px(moon_cx + 23, moon_cy - 5, GRAY); sp.px(moon_cx + 24, moon_cy - 4, GRAY)
    sp.line(moon_cx + 22, moon_cy - 6, moon_cx + 24, moon_cy - 8, BLACK)  # motion
    # Palm GAWKING (with eyes)
    compose_palm_tree(sp, 70, 56, trunk_h=30, frond_r=10)
    sp.ellipse(67, 26, 70, 29, WHITE, outline=BLACK)
    sp.ellipse(72, 26, 75, 29, WHITE, outline=BLACK)
    sp.px(68, 28, BLACK); sp.px(73, 28, BLACK)
    # Astronaut FACEPLANTED (head down in sand, legs kicking up)
    ax, ay = 100, 70
    # Body sticking up out of sand (legs waving)
    sp.rect(ax - 2, ay - 6, ax + 2, ay - 2, WHITE)  # body
    sp.line(ax - 2, ay - 8, ax - 4, ay - 12, WHITE)  # leg 1
    sp.line(ax - 2, ay - 9, ax - 5, ay - 13, WHITE)
    sp.line(ax + 2, ay - 8, ax + 4, ay - 12, WHITE)  # leg 2
    sp.line(ax + 2, ay - 9, ax + 5, ay - 13, WHITE)
    # Boots
    sp.px(ax - 4, ay - 13, BLACK); sp.px(ax - 5, ay - 13, BLACK)
    sp.px(ax + 4, ay - 13, BLACK); sp.px(ax + 5, ay - 13, BLACK)
    # Helmet half-buried (curved bit visible)
    sp.ellipse(ax - 3, ay - 2, ax + 3, ay + 2, WHITE, outline=BLACK)
    # Sand splash around head
    for x, y in [(ax - 5, ay), (ax + 5, ay), (ax - 6, ay - 1), (ax + 6, ay - 1)]:
        sp.px(x, y, SAND); sp.px(x, y + 1, SAND)
    # Flag fallen over next to astronaut
    sp.line(ax + 8, ay - 4, ax + 14, ay - 8, GRAY)
    sp.rect(ax + 14, ay - 12, ax + 22, ay - 8, WHITE, outline=BLACK)
    for sy in range(ay - 11, ay - 8, 2):
        sp.line(ax + 14, sy, ax + 22, sy, RED)
    sp.rect(ax + 14, ay - 12, ax + 17, ay - 10, DEEPBLUE)
    # Stars sparkling
    for x, y in [(8, 4), (88, 8), (110, 12), (16, 18), (76, 6),
                 (118, 6), (54, 14)]:
        sp.px(x, y, WHITE)
    compose_star(sp, 24, 12, 2, YELLOW)
    compose_star(sp, 110, 22, 2, WHITE)
    # Speech bubble from astronaut
    sp.ellipse(60, 50, 86, 64, WHITE, outline=BLACK)
    sp.text(64, 53, "OOF", BLACK)
    sp.line(76, 64, 95, 70, BLACK)
    # Footprints leading up to faceplant
    for fx in [78, 86, 94]:
        sp.ellipse(fx, 72, fx + 4, 74, BLACK)
    return sp


def watermelon_v4(h):
    """PLAYFUL — Johnny mid-bite with seeds spitting out, watermelon slice
    with face, juice splatter, oversized smile, motion lines."""
    sp = Sprite(56, 48, fill=SKY)
    compose_sand_strip(sp, 32)
    compose_horizon(sp, 32)
    # Watermelon slice with FACE (about to be eaten)
    cx = 18
    sp.ellipse(cx - 12, 22, cx + 12, 42, DGREEN, outline=BLACK)
    sp.ellipse(cx - 10, 24, cx + 10, 40, GREEN)
    sp.ellipse(cx - 8, 26, cx + 8, 38, RED)
    sp.line(cx - 12, 28, cx + 12, 28, BLACK)
    sp.rect(cx - 12, 22, cx + 12, 28, RED, outline=BLACK)
    # Face on melon (terrified)
    sp.ellipse(cx - 5, 30, cx - 3, 32, WHITE)
    sp.ellipse(cx + 1, 30, cx + 3, 32, WHITE)
    sp.px(cx - 4, 31, BLACK); sp.px(cx + 2, 31, BLACK)
    # Squiggly worried mouth
    sp.line(cx - 3, 35, cx - 1, 34, BLACK)
    sp.line(cx - 1, 34, cx + 1, 35, BLACK)
    sp.line(cx + 1, 35, cx + 3, 34, BLACK)
    # BIG bite mark out of top
    sp.ellipse(cx - 2, 22, cx + 8, 30, SKY)
    # Seeds inside flying out
    for sx, sy in [(cx + 2, 26), (cx + 6, 24), (cx + 8, 22), (cx + 10, 20)]:
        sp.px(sx, sy, BLACK); sp.px(sx + 1, sy, BLACK)
    # Juice splatter dots
    for x, y in [(cx + 4, 18), (cx + 10, 18), (cx + 12, 20), (cx + 14, 22)]:
        sp.px(x, y, RED); sp.px(x + 1, y, RED)
    # Johnny on the right with HUGE grin, juice on face
    jx = 38
    base_y = 44
    # Body
    sp.rect(jx, base_y - 8, jx + 5, base_y - 4, RED)
    sp.rect(jx + 1, base_y - 3, jx + 2, base_y, TRUNK)
    sp.rect(jx + 3, base_y - 3, jx + 4, base_y, TRUNK)
    # Hat
    sp.rect(jx, base_y - 13, jx + 5, base_y - 12, GREEN)
    sp.rect(jx + 1, base_y - 12, jx + 4, base_y - 12, GREEN)
    # Head
    sp.rect(jx + 1, base_y - 11, jx + 4, base_y - 9, SKIN)
    # Comically wide squinty-eyes (happy)
    sp.line(jx + 1, base_y - 10, jx + 2, base_y - 10, BLACK)
    sp.line(jx + 3, base_y - 10, jx + 4, base_y - 10, BLACK)
    # MASSIVE grin (mouth full of melon)
    sp.rect(jx, base_y - 9, jx + 5, base_y - 8, BLACK)
    sp.rect(jx + 1, base_y - 9, jx + 4, base_y - 8, RED)  # melon in mouth
    # Juice running down chin
    sp.px(jx + 1, base_y - 7, RED); sp.px(jx + 2, base_y - 6, RED)
    sp.px(jx + 3, base_y - 7, RED); sp.px(jx + 4, base_y - 6, RED)
    # Cheeks puffed (red dots)
    sp.px(jx, base_y - 9, PINK); sp.px(jx + 5, base_y - 9, PINK)
    # Seeds being SPIT out
    for sx, sy in [(jx - 2, base_y - 12), (jx - 4, base_y - 14), (jx - 6, base_y - 12)]:
        sp.px(sx, sy, BLACK); sp.px(sx + 1, sy, BLACK)
    # Spit motion lines from mouth
    sp.line(jx - 1, base_y - 10, jx - 7, base_y - 12, BLACK)
    # Both hands holding melon (skin lines)
    sp.line(jx, base_y - 6, jx - 6, base_y - 8, SKIN)
    sp.line(jx + 5, base_y - 6, jx + 8, base_y - 4, SKIN)
    # Sweat drop of joy
    sp.px(jx - 2, base_y - 11, SKY)
    # Big "YUM!" speech bubble
    sp.ellipse(36, 4, 54, 16, WHITE, outline=BLACK)
    sp.text(38, 6, "YUM", BLACK)
    sp.line(40, 14, 38, 18, BLACK)  # bubble tail
    # Seeds scattered everywhere
    for x, y in [(2, 44), (10, 46), (32, 47), (50, 46), (4, 38), (52, 42)]:
        sp.px(x, y, BLACK)
    return sp


# ---------------------------------------------------------------------------
# Batch 3 RENDERERS dict
# ---------------------------------------------------------------------------

RENDERERS_BATCH3 = {
    20: (memorial_v1, memorial_v2, memorial_v3, memorial_v4),
    21: (fathersday_v1, fathersday_v2, fathersday_v3, fathersday_v4),
    22: (summer_v1, summer_v2, summer_v3, summer_v4),
    23: (pride_v1, pride_v2, pride_v3, pride_v4),
    24: (july4th_v1, july4th_v2, july4th_v3, july4th_v4),
    25: (moonland_v1, moonland_v2, moonland_v3, moonland_v4),
    26: (watermelon_v1, watermelon_v2, watermelon_v3, watermelon_v4),
}
