#!/bin/bash
#
# release.sh - Build, version bump, and release PS1 build
#
# Usage: ./scripts/release.sh [--version X.Y.Z] [message]
#        RELEASE_VERSION=X.Y.Z ./scripts/release.sh [message]
#   message: Optional release message (default: "PS1 release")
#
# This script:
#   1. Runs the full rebuild
#   2. Increments the patch version (e.g., 0.3.0 -> 0.3.1), or uses
#      an explicit --version / RELEASE_VERSION value
#   3. Copies build artifacts to release/ folder for GitHub Release upload
#   4. Updates VERSION and website release metadata
#   5. Rebuilds the portable website under docs/
#   6. Commits changes and creates a git tag
#   7. Pushes to GitHub

if [ "$(id -u)" = "0" ]; then
    echo "ERROR: Do not run this script as root/sudo." >&2
    exit 1
fi

set -e  # Exit on error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
VERSION_FILE="$PROJECT_DIR/VERSION"
RELEASE_DIR="$PROJECT_DIR/release"
SITE_CONFIG="$PROJECT_DIR/site/_config.yml"
SITE_BUILD_SCRIPT="$SCRIPT_DIR/site-build-static-root.sh"
SITE_REDTEAM_SCRIPT="$SCRIPT_DIR/site-redteam.py"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}======================================"
echo "PS1 Release Script"
echo -e "======================================${NC}"

# Parse release arguments.
REQUESTED_VERSION="${RELEASE_VERSION:-}"
RELEASE_MSG_PARTS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --version)
            if [[ $# -lt 2 ]]; then
                echo -e "${RED}ERROR: --version requires X.Y.Z${NC}"
                exit 1
            fi
            REQUESTED_VERSION="$2"
            shift 2
            ;;
        --version=*)
            REQUESTED_VERSION="${1#--version=}"
            shift
            ;;
        *)
            RELEASE_MSG_PARTS+=("$1")
            shift
            ;;
    esac
done

if [[ ${#RELEASE_MSG_PARTS[@]} -gt 0 ]]; then
    RELEASE_MSG="${RELEASE_MSG_PARTS[*]}"
else
    RELEASE_MSG="PS1 release"
fi

# Read current version
if [[ ! -f "$VERSION_FILE" ]]; then
    echo -e "${RED}ERROR: VERSION file not found at $VERSION_FILE${NC}"
    exit 1
fi

CURRENT_VERSION=$(cat "$VERSION_FILE" | tr -d '[:space:]')
echo -e "${YELLOW}Current version: $CURRENT_VERSION${NC}"

# Parse version components (MAJOR.MINOR.PATCH)
IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

if [[ -n "$REQUESTED_VERSION" ]]; then
    if [[ ! "$REQUESTED_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo -e "${RED}ERROR: --version must be X.Y.Z, got '$REQUESTED_VERSION'${NC}"
        exit 1
    fi
    NEW_VERSION="$REQUESTED_VERSION"
else
    # Increment patch version
    NEW_PATCH=$((PATCH + 1))
    NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
fi
TAG_NAME="v${NEW_VERSION}-ps1"

echo -e "${GREEN}New version: $NEW_VERSION${NC}"
echo -e "${GREEN}Tag name: $TAG_NAME${NC}"

cd "$PROJECT_DIR"

# Release commits need to contain only files generated by this script.
if [[ -n "$(git status --porcelain)" ]]; then
    echo -e "${RED}ERROR: Working tree is not clean. Commit or stash changes before releasing.${NC}"
    exit 1
fi

# Check if tag already exists
if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
    echo -e "${RED}ERROR: Tag $TAG_NAME already exists!${NC}"
    exit 1
fi

# Step 1: Run the build (build + CD image only; do not launch the emulator)
echo ""
echo -e "${YELLOW}=== Step 1: Building PS1 executable ===${NC}"
"$SCRIPT_DIR/build-ps1.sh" clean
"$SCRIPT_DIR/make-cd-image.sh"

# Check build artifacts exist
if [[ ! -f "$PROJECT_DIR/johnnycastawayps1.bin" ]] || [[ ! -f "$PROJECT_DIR/johnnycastawayps1.cue" ]]; then
    echo -e "${RED}ERROR: Build artifacts not found (johnnycastawayps1.bin/cue)${NC}"
    exit 1
fi

# Step 2: Copy artifacts to release folder
echo ""
echo -e "${YELLOW}=== Step 2: Copying build artifacts to release/ ===${NC}"
mkdir -p "$RELEASE_DIR"
cp "$PROJECT_DIR/johnnycastawayps1.bin" "$RELEASE_DIR/"
cp "$PROJECT_DIR/johnnycastawayps1.cue" "$RELEASE_DIR/"
echo "Copied johnnycastawayps1.bin and johnnycastawayps1.cue to release/"

SHA256_BIN=$(sha256sum "$RELEASE_DIR/johnnycastawayps1.bin" | awk '{print $1}')
SHA256_CUE=$(sha256sum "$RELEASE_DIR/johnnycastawayps1.cue" | awk '{print $1}')
RELEASE_DATE=$(date +%F)
echo "johnnycastawayps1.bin sha256: $SHA256_BIN"
echo "johnnycastawayps1.cue sha256: $SHA256_CUE"

# Step 3: Update VERSION file
echo ""
echo -e "${YELLOW}=== Step 3: Updating VERSION file ===${NC}"
echo "$NEW_VERSION" > "$VERSION_FILE"
echo "Updated VERSION to $NEW_VERSION"

# Step 4: Update website release metadata and rebuild the static site.
echo ""
echo -e "${YELLOW}=== Step 4: Updating website release metadata ===${NC}"
python3 - "$SITE_CONFIG" "$NEW_VERSION" "$TAG_NAME" "$RELEASE_DATE" "$SHA256_BIN" "$SHA256_CUE" <<'PY'
from pathlib import Path
import sys

config_path = Path(sys.argv[1])
version = sys.argv[2]
tag = sys.argv[3]
release_date = sys.argv[4]
sha256_bin = sys.argv[5]
sha256_cue = sys.argv[6]

lines = config_path.read_text().splitlines(keepends=True)
in_release = False
changed_version = False
changed_tag = False
changed_release_date = False
changed_sha256_bin = False
changed_sha256_cue = False

for idx, line in enumerate(lines):
    if line.startswith("release:"):
        in_release = True
        continue
    if not in_release:
        continue
    if line and not line.startswith(" "):
        in_release = False
        continue
    newline = "\n" if line.endswith("\n") else ""
    if line.startswith("  version:"):
        lines[idx] = f'  version: "{version}"{newline}'
        changed_version = True
    elif line.startswith("  tag:"):
        lines[idx] = f'  tag: "{tag}"{newline}'
        changed_tag = True
    elif line.startswith("  release_date:"):
        lines[idx] = f'  release_date: "{release_date}"{newline}'
        changed_release_date = True
    elif line.startswith("  sha256_bin:"):
        lines[idx] = f'  sha256_bin: "{sha256_bin}"{newline}'
        changed_sha256_bin = True
    elif line.startswith("  sha256_cue:"):
        lines[idx] = f'  sha256_cue: "{sha256_cue}"{newline}'
        changed_sha256_cue = True

if not (
    changed_version
    and changed_tag
    and changed_release_date
    and changed_sha256_bin
    and changed_sha256_cue
):
    raise SystemExit(
        "site/_config.yml release.version/tag/date/sha256 fields were not found"
    )

config_path.write_text("".join(lines))
PY
echo "Updated site release metadata to $TAG_NAME"

echo ""
echo -e "${YELLOW}=== Step 5: Rebuilding website ===${NC}"
"$SITE_BUILD_SCRIPT"
python3 "$SITE_REDTEAM_SCRIPT" "$PROJECT_DIR/docs" \
    --require-relative \
    --exclude 'ps1/archaeology/**'

# Step 6: Git commit
echo ""
echo -e "${YELLOW}=== Step 6: Committing changes ===${NC}"
git add VERSION site/_config.yml site/source site/resources docs

git commit -m "$(cat <<EOF
release: $TAG_NAME - $RELEASE_MSG
EOF
)"

# Step 7: Create a normal annotated source tag. The ISO is larger than
# GitHub's 100 MB Git blob limit, so johnnycastawayps1.bin/cue are uploaded as
# GitHub Release assets in Step 9 instead of being placed in the tag tree.
echo ""
echo -e "${YELLOW}=== Step 7: Creating source release tag ===${NC}"
git tag -a "$TAG_NAME" -m "$RELEASE_MSG" HEAD
echo "Created tag: $TAG_NAME"

# Step 8: Push to GitHub
echo ""
echo -e "${YELLOW}=== Step 8: Pushing to GitHub ===${NC}"
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
git push origin "$CURRENT_BRANCH"
git push origin "$TAG_NAME"

# Step 9: Publish a GitHub Release with johnnycastawayps1.bin + johnnycastawayps1.cue as
# direct-download assets. The release assets are the canonical binary
# distribution because the ISO is too large to store as a Git blob.
echo ""
echo -e "${YELLOW}=== Step 9: Publishing GitHub Release ===${NC}"
GH_BIN="$(command -v gh 2>/dev/null || echo "$HOME/bin/gh")"
if [ -x "$GH_BIN" ] && "$GH_BIN" auth status >/dev/null 2>&1; then
    RELEASE_NOTES="$RELEASE_MSG

Download \`johnnycastawayps1.bin\` and \`johnnycastawayps1.cue\` from this release's
attached assets, then load \`johnnycastawayps1.cue\` in DuckStation or another
PS1 emulator."
    "$GH_BIN" release create "$TAG_NAME" \
        "$RELEASE_DIR/johnnycastawayps1.bin" \
        "$RELEASE_DIR/johnnycastawayps1.cue" \
        --title "$TAG_NAME" \
        --notes "$RELEASE_NOTES"
else
    echo -e "${YELLOW}gh not available or not authed — skipping GitHub Release.${NC}"
    echo -e "${YELLOW}The tag was pushed, but the large ISO assets still need a GitHub Release upload:${NC}"
    echo -e "${YELLOW}  gh release create $TAG_NAME $RELEASE_DIR/johnnycastawayps1.bin $RELEASE_DIR/johnnycastawayps1.cue --title \"$TAG_NAME\" --notes \"$RELEASE_MSG\"${NC}"
fi

echo ""
echo -e "${GREEN}======================================"
echo "Release complete!"
echo "======================================"
echo -e "Version: $NEW_VERSION"
echo -e "Tag: $TAG_NAME"
echo -e "Message: $RELEASE_MSG${NC}"
