/*
 * Auto-generated PSB registry — maps BMP names to PSB file sizes.
 * Generated by scripts/transcode-bmp-ps1.py --all
 * DO NOT EDIT BY HAND.
 */

#ifndef PSB_REGISTRY_H
#define PSB_REGISTRY_H

#ifdef PS1_BUILD

#include <stdint.h>
#include <string.h>

typedef struct PsbRegistryEntry {
    const char *bmpName;   /* e.g. "JOHNWALK.BMP" */
    uint32_t    psbSize;   /* File size of the .PSB on CD */
} PsbRegistryEntry;

#define PSB_REGISTRY_COUNT 117

/* Sorted by name for binary search. */
static const PsbRegistryEntry psbRegistry[PSB_REGISTRY_COUNT] = {
    { "BACKGRND.BMP", 93176 },
    { "BOAT.BMP", 7592 },
    { "CLOUDS.BMP", 10904 },
    { "COCOHEAD.BMP", 4176 },
    { "COCONUTS.BMP", 952 },
    { "DRUNKJON.BMP", 41372 },
    { "ENDCRDTS.BMP", 7716 },
    { "FIRE.BMP", 27124 },
    { "FIRE1.BMP", 8544 },
    { "FIRE2.BMP", 7116 },
    { "FIRE3.BMP", 4916 },
    { "FIRE4.BMP", 37276 },
    { "FIRE5.BMP", 1036 },
    { "FISHMAN.BMP", 6952 },
    { "GJANGRY.BMP", 39172 },
    { "GJBIPLAN.BMP", 25752 },
    { "GJCASTLE.BMP", 10192 },
    { "GJCATCH1.BMP", 56660 },
    { "GJCATCH2.BMP", 106152 },
    { "GJCATCH3.BMP", 13576 },
    { "GJDIVE.BMP", 83792 },
    { "GJFFFOOD.BMP", 139128 },
    { "GJGULL1.BMP", 17412 },
    { "GJGULL1A.BMP", 39172 },
    { "GJGULL2.BMP", 29152 },
    { "GJGULL2A.BMP", 14336 },
    { "GJGULL3.BMP", 43584 },
    { "GJGULL3A.BMP", 57400 },
    { "GJHOT.BMP", 34604 },
    { "GJKINGKO.BMP", 43168 },
    { "GJNAT1.BMP", 53980 },
    { "GJNAT1LI.BMP", 36196 },
    { "GJNAT3.BMP", 80548 },
    { "GJPROW.BMP", 20432 },
    { "GJRUNAWA.BMP", 43740 },
    { "GJVIS3.BMP", 34928 },
    { "GJVIS5.BMP", 47220 },
    { "GJVIS52.BMP", 49040 },
    { "GJVIS6.BMP", 47840 },
    { "HOLIDAY.BMP", 8956 },
    { "JATA.BMP", 3388 },
    { "JCHANGE.BMP", 7560 },
    { "JOHNWALK.BMP", 48924 },
    { "JOHNWOUL.BMP", 22872 },
    { "LILFISH.BMP", 2284 },
    { "LILIPUTS.BMP", 20784 },
    { "LITEBULB.BMP", 5292 },
    { "MEANWHIL.BMP", 8868 },
    { "MEXCWALK.BMP", 11828 },
    { "MJBATH.BMP", 54124 },
    { "MJBOTTLE.BMP", 27760 },
    { "MJBTL2.BMP", 33224 },
    { "MJCOCO.BMP", 47904 },
    { "MJDIVE.BMP", 40504 },
    { "MJFISH1.BMP", 76972 },
    { "MJFISH2.BMP", 44508 },
    { "MJFISH3.BMP", 16104 },
    { "MJJOG1.BMP", 30164 },
    { "MJJOG2.BMP", 37156 },
    { "MJRAFT2.BMP", 23752 },
    { "MJREAD.BMP", 45720 },
    { "MJSANDC.BMP", 22244 },
    { "MJTELE.BMP", 24104 },
    { "MJTELE2.BMP", 7440 },
    { "MJ_AMB.BMP", 27920 },
    { "MRAFT.BMP", 10716 },
    { "SANDCAST.BMP", 34380 },
    { "SA_DEMO.BMP", 764 },
    { "SBREAKUP.BMP", 60172 },
    { "SHARK.BMP", 91600 },
    { "SHARKWLK.BMP", 7892 },
    { "SHIPS.BMP", 43592 },
    { "SHKNFIST.BMP", 6752 },
    { "SJBRAKUP.BMP", 2064 },
    { "SJGFTASK.BMP", 19668 },
    { "SJGFTJMP.BMP", 9828 },
    { "SJGFTSHY.BMP", 15160 },
    { "SJGFTXCH.BMP", 29988 },
    { "SJMSUZY1.BMP", 16284 },
    { "SJMSUZY2.BMP", 43860 },
    { "SJMSUZY3.BMP", 72588 },
    { "SJRAFT1.BMP", 13340 },
    { "SJWORK.BMP", 12976 },
    { "SLEEP.BMP", 24328 },
    { "SLEVEJC1.BMP", 21540 },
    { "SLEVEJC2.BMP", 21116 },
    { "SLEVEJC3.BMP", 41980 },
    { "SLEVEJM1.BMP", 13032 },
    { "SLEVEJM2.BMP", 33452 },
    { "SLEVEJM3.BMP", 20984 },
    { "SMDATE1.BMP", 19908 },
    { "SMDATE10.BMP", 35508 },
    { "SMDATE11.BMP", 27184 },
    { "SMDATE12.BMP", 4740 },
    { "SMDATE2.BMP", 17788 },
    { "SMDATE3.BMP", 32020 },
    { "SMDATE4.BMP", 35944 },
    { "SMDATE5.BMP", 48392 },
    { "SMDATE6.BMP", 29920 },
    { "SMDATE7.BMP", 4388 },
    { "SMDATE8.BMP", 16352 },
    { "SMDATE9.BMP", 67824 },
    { "SMGFTWAV.BMP", 2064 },
    { "SMGIFT.BMP", 53168 },
    { "SMGLIMSE.BMP", 31020 },
    { "SPLASH.BMP", 21612 },
    { "SRAFT.BMP", 3600 },
    { "SSUZY1.BMP", 31556 },
    { "SSUZY2.BMP", 48416 },
    { "SSUZY3.BMP", 77132 },
    { "STNDLAY.BMP", 19116 },
    { "TANKER.BMP", 10392 },
    { "THEEND1.BMP", 16020 },
    { "THNKBUBL.BMP", 53500 },
    { "TRUNK.BMP", 7480 },
    { "WOULDBE.BMP", 58712 },
    { "ZZZZS.BMP", 248 },
};

/*
 * Look up a BMP name in the PSB registry.
 * Returns the PSB file size if found, 0 if not found.
 * Uses binary search since the table is sorted alphabetically.
 */
static uint32_t psbRegistryLookup(const char *bmpName)
{
    int lo = 0, hi = PSB_REGISTRY_COUNT - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int cmp = strcmp(bmpName, psbRegistry[mid].bmpName);
        if (cmp == 0) return psbRegistry[mid].psbSize;
        if (cmp < 0) hi = mid - 1;
        else lo = mid + 1;
    }
    return 0;
}

#endif /* PS1_BUILD */

#endif /* PSB_REGISTRY_H */
