/* Generated by scripts/build-scene-explorer-data.py.
 * Sources: docs/ps1/scene-status.md, site/scenes/<slug>/index.md,
 *          generated/ps1/foreground/<SLUG>.FG2.
 * Re-run as part of release.sh; do not edit by hand. */

#ifndef SCENE_EXPLORER_DATA_H
#define SCENE_EXPLORER_DATA_H

#include "mytypes.h"

struct TSceneExplorerEntry {
    const char *slug;          /* internal scene identifier (e.g. "fishing1") */
    const char *display_name;  /* shown on the menu line */
    const char *family;        /* display family group */
    const char *pack;          /* CD-relative FG2 path */
    const char *thumb_psb;     /* CD-relative thumbnail PSB path */
    uint16      frame_count;   /* from FG2 header */
    uint8       validated;     /* 1 if scene-status visuals are checked */
    uint8       _pad;
};

static const struct TSceneExplorerEntry gSceneExplorer[] = {
    { "fishing1", "FISHING 1  -  Johnny casts a line", "Fishing", "FG/FISHING1.FG2", "BMP/SCEXPL_FISHING1.PSB", 156, 1, 0 },
    { "fishing2", "FISHING 2  -  A life raft drifts past", "Fishing", "FG/FISHING2.FG2", "BMP/SCEXPL_FISHING2.PSB", 295, 1, 0 },
    { "fishing3", "FISHING 3  -  An octopus interlude", "Fishing", "FG/FISHING3.FG2", "BMP/SCEXPL_FISHING3.PSB", 329, 1, 0 },
    { "fishing4", "FISHING 4  -  Caught by a shark", "Fishing", "FG/FISHING4.FG2", "BMP/SCEXPL_FISHING4.PSB", 133, 1, 0 },
    { "fishing5", "FISHING 5  -  Eaten by a shark", "Fishing", "FG/FISHING5.FG2", "BMP/SCEXPL_FISHING5.PSB", 69, 1, 0 },
    { "fishing6", "FISHING 6  -  Big green fish", "Fishing", "FG/FISHING6.FG2", "BMP/SCEXPL_FISHING6.PSB", 112, 1, 0 },
    { "fishing7", "FISHING 7  -  Octopus chokes Johnny", "Fishing", "FG/FISHING7.FG2", "BMP/SCEXPL_FISHING7.PSB", 80, 1, 0 },
    { "fishing8", "FISHING 8  -  Another boot", "Fishing", "FG/FISHING8.FG2", "BMP/SCEXPL_FISHING8.PSB", 133, 1, 0 },
    { "johnny1", "JOHNNY 1  -  The End", "Johnny", "FG/JOHNNY1.FG2", "BMP/SCEXPL_JOHNNY1.PSB", 112, 1, 0 },
    { "johnny2", "JOHNNY 2  -  First SOS bottle", "Johnny", "FG/JOHNNY2.FG2", "BMP/SCEXPL_JOHNNY2.PSB", 146, 1, 0 },
    { "johnny3", "JOHNNY 3  -  His own SOS returns", "Johnny", "FG/JOHNNY3.FG2", "BMP/SCEXPL_JOHNNY3.PSB", 210, 1, 0 },
    { "johnny4", "JOHNNY 4  -  Writes a fresh SOS", "Johnny", "FG/JOHNNY4.FG2", "BMP/SCEXPL_JOHNNY4.PSB", 94, 1, 0 },
    { "johnny5", "JOHNNY 5  -  Imagines a 3pm date", "Johnny", "FG/JOHNNY5.FG2", "BMP/SCEXPL_JOHNNY5.PSB", 91, 1, 0 },
    { "johnny6", "JOHNNY 6  -  Office daydream", "Johnny", "FG/JOHNNY6.FG2", "BMP/SCEXPL_JOHNNY6.PSB", 82, 1, 0 },
    { "mary1", "MARY 1  -  Fancy dinner", "Mary", "FG/MARY1.FG2", "BMP/SCEXPL_MARY1.PSB", 821, 1, 0 },
    { "mary2", "MARY 2  -  First encounter", "Mary", "FG/MARY2.FG2", "BMP/SCEXPL_MARY2.PSB", 234, 1, 0 },
    { "mary3", "MARY 3  -  Mermaid sneak-up", "Mary", "FG/MARY3.FG2", "BMP/SCEXPL_MARY3.PSB", 256, 1, 0 },
    { "mary4", "MARY 4  -  Heartbroken at the raft", "Mary", "FG/MARY4.FG2", "BMP/SCEXPL_MARY4.PSB", 154, 1, 0 },
    { "mary5", "MARY 5  -  Goodbye", "Mary", "FG/MARY5.FG2", "BMP/SCEXPL_MARY5.PSB", 150, 1, 0 },
    { "visitor1", "VISITOR 1  -  Lilliputians arrive", "Visitors", "FG/VISITOR1.FG2", "BMP/SCEXPL_VISITOR1.PSB", 120, 0, 0 },
    { "visitor3", "VISITOR 3  -  Yacht couple, photos", "Visitors", "FG/VISITOR3.FG2", "BMP/SCEXPL_VISITOR3.PSB", 190, 0, 0 },
    { "visitor4", "VISITOR 4  -  Red boat circles", "Visitors", "FG/VISITOR4.FG2", "BMP/SCEXPL_VISITOR4.PSB", 67, 0, 0 },
    { "visitor5", "VISITOR 5  -  Visitor takes Johnny", "Visitors", "FG/VISITOR5.FG2", "BMP/SCEXPL_VISITOR5.PSB", 228, 0, 0 },
    { "visitor6", "VISITOR 6  -  Schooner with partygoers", "Visitors", "FG/VISITOR6.FG2", "BMP/SCEXPL_VISITOR6.PSB", 277, 0, 0 },
    { "visitor7", "VISITOR 7  -  Plane overhead", "Visitors", "FG/VISITOR7.FG2", "BMP/SCEXPL_VISITOR7.PSB", 218, 0, 0 },
    { "activity1", "ACTIVITY 1  -  Climbs the palm and dives", "Activities", "FG/ACTIVITY1.FG2", "BMP/SCEXPL_ACTIVITY1.PSB", 376, 0, 0 },
    { "activity10", "ACTIVITY 10  -  Reads; seagull steals book", "Activities", "FG/ACTIVITY10.FG2", "BMP/SCEXPL_ACTIVITY10.PSB", 256, 0, 0 },
    { "activity11", "ACTIVITY 11  -  Rain dance", "Activities", "FG/ACTIVITY11.FG2", "BMP/SCEXPL_ACTIVITY11.PSB", 194, 0, 0 },
    { "activity12", "ACTIVITY 12  -  Belly-flop dive", "Activities", "FG/ACTIVITY12.FG2", "BMP/SCEXPL_ACTIVITY12.PSB", 252, 0, 0 },
    { "activity4", "ACTIVITY 4  -  Reads, seagull on head", "Activities", "FG/ACTIVITY4.FG2", "BMP/SCEXPL_ACTIVITY4.PSB", 190, 0, 0 },
    { "activity5", "ACTIVITY 5  -  Climb / look / dive", "Activities", "FG/ACTIVITY5.FG2", "BMP/SCEXPL_ACTIVITY5.PSB", 301, 0, 0 },
    { "activity6", "ACTIVITY 6  -  Reads, falls asleep, coconut bonk", "Activities", "FG/ACTIVITY6.FG2", "BMP/SCEXPL_ACTIVITY6.PSB", 105, 0, 0 },
    { "activity7", "ACTIVITY 7  -  Bathes; seagull steals clothes", "Activities", "FG/ACTIVITY7.FG2", "BMP/SCEXPL_ACTIVITY7.PSB", 108, 0, 0 },
    { "activity8", "ACTIVITY 8  -  Reads book upside down", "Activities", "FG/ACTIVITY8.FG2", "BMP/SCEXPL_ACTIVITY8.PSB", 87, 0, 0 },
    { "activity9", "ACTIVITY 9  -  Bathes with a brush", "Activities", "FG/ACTIVITY9.FG2", "BMP/SCEXPL_ACTIVITY9.PSB", 288, 0, 0 },
    { "miscgag1", "MISCGAG 1  -  Pocket fan, melts", "Misc & Suzy", "FG/MISCGAG1.FG2", "BMP/SCEXPL_MISCGAG1.PSB", 69, 1, 0 },
    { "miscgag2", "MISCGAG 2  -  Towel, toe, shark", "Misc & Suzy", "FG/MISCGAG2.FG2", "BMP/SCEXPL_MISCGAG2.PSB", 84, 1, 0 },
    { "suzy1", "SUZY 1  -  Sunbathing daydream", "Misc & Suzy", "FG/SUZY1.FG2", "BMP/SCEXPL_SUZY1.PSB", 177, 1, 0 },
    { "suzy2", "SUZY 2  -  Raft drifts to her", "Misc & Suzy", "FG/SUZY2.FG2", "BMP/SCEXPL_SUZY2.PSB", 133, 0, 0 },
    { "stand1", "STAND 1  -  Edge of the island", "Standing", "FG/STAND1.FG2", "BMP/SCEXPL_STAND1.PSB", 18, 1, 0 },
    { "stand10", "STAND 10  -  Looks at his raft", "Standing", "FG/STAND10.FG2", "BMP/SCEXPL_STAND10.PSB", 87, 1, 0 },
    { "stand11", "STAND 11  -  Shades under the palm", "Standing", "FG/STAND11.FG2", "BMP/SCEXPL_STAND11.PSB", 87, 1, 0 },
    { "stand12", "STAND 12  -  Looks out over the right water", "Standing", "FG/STAND12.FG2", "BMP/SCEXPL_STAND12.PSB", 238, 1, 0 },
    { "stand15", "STAND 15  -  Spyglass, left edge", "Standing", "FG/STAND15.FG2", "BMP/SCEXPL_STAND15.PSB", 34, 1, 0 },
    { "stand16", "STAND 16  -  Spyglass, center", "Standing", "FG/STAND16.FG2", "BMP/SCEXPL_STAND16.PSB", 36, 1, 0 },
    { "stand2", "STAND 2  -  Adjusts pants", "Standing", "FG/STAND2.FG2", "BMP/SCEXPL_STAND2.PSB", 78, 1, 0 },
    { "stand3", "STAND 3  -  Lifts hat", "Standing", "FG/STAND3.FG2", "BMP/SCEXPL_STAND3.PSB", 91, 1, 0 },
    { "stand4", "STAND 4  -  Taps foot", "Standing", "FG/STAND4.FG2", "BMP/SCEXPL_STAND4.PSB", 107, 1, 0 },
    { "stand5", "STAND 5  -  Looks out over the ocean", "Standing", "FG/STAND5.FG2", "BMP/SCEXPL_STAND5.PSB", 131, 1, 0 },
    { "stand6", "STAND 6  -  Looks at the palm", "Standing", "FG/STAND6.FG2", "BMP/SCEXPL_STAND6.PSB", 118, 1, 0 },
    { "stand7", "STAND 7  -  Lifts hat, looks around", "Standing", "FG/STAND7.FG2", "BMP/SCEXPL_STAND7.PSB", 47, 1, 0 },
    { "stand8", "STAND 8  -  Tap, lift, look", "Standing", "FG/STAND8.FG2", "BMP/SCEXPL_STAND8.PSB", 44, 1, 0 },
    { "stand9", "STAND 9  -  Looks back inland", "Standing", "FG/STAND9.FG2", "BMP/SCEXPL_STAND9.PSB", 47, 1, 0 },
    { "walkstuf1", "WALKSTUF 1  -  Jogs around the island", "Walking", "FG/WALKSTUF1.FG2", "BMP/SCEXPL_WALKSTUF1.PSB", 354, 0, 0 },
    { "walkstuf2", "WALKSTUF 2  -  Walk transition", "Walking", "FG/WALKSTUF2.FG2", "BMP/SCEXPL_WALKSTUF2.PSB", 57, 0, 0 },
    { "walkstuf3", "WALKSTUF 3  -  Walk transition", "Walking", "FG/WALKSTUF3.FG2", "BMP/SCEXPL_WALKSTUF3.PSB", 439, 0, 0 },
    { "building1", "BUILDING 1  -  Sand castle (crumbles)", "Building", "FG/BUILDING1.FG2", "BMP/SCEXPL_BUILDING1.PSB", 149, 0, 0 },
    { "building2", "BUILDING 2  -  Roasts a boot", "Building", "FG/BUILDING2.FG2", "BMP/SCEXPL_BUILDING2.PSB", 320, 0, 0 },
    { "building3", "BUILDING 3  -  Builds a fire", "Building", "FG/BUILDING3.FG2", "BMP/SCEXPL_BUILDING3.PSB", 219, 0, 0 },
    { "building4", "BUILDING 4  -  Sand castle vs. lilliputians", "Building", "FG/BUILDING4.FG2", "BMP/SCEXPL_BUILDING4.PSB", 383, 0, 0 },
    { "building5", "BUILDING 5  -  Fixes the raft (mermaid)", "Building", "FG/BUILDING5.FG2", "BMP/SCEXPL_BUILDING5.PSB", 666, 0, 0 },
    { "building6", "BUILDING 6  -  Edge sleep", "Building", "FG/BUILDING6.FG2", "BMP/SCEXPL_BUILDING6.PSB", 283, 0, 0 },
    { "building7", "BUILDING 7  -  Builds up the raft", "Building", "FG/BUILDING7.FG2", "BMP/SCEXPL_BUILDING7.PSB", 711, 0, 0 },
};
#define gSceneExplorerCount ((int)(sizeof(gSceneExplorer) / sizeof(gSceneExplorer[0])))

static const int gSceneExplorerFamilyStart[] = {
    0,
    8,
    14,
    19,
    25,
    35,
    39,
    53,
    56,
};
#define gSceneExplorerFamilyCount ((int)(sizeof(gSceneExplorerFamilyStart) / sizeof(gSceneExplorerFamilyStart[0])))

#endif
